wildfly-security/wildfly-elytron

src/main/java/org/wildfly/security/sasl/util/ByteStringBuilder.java, src/main/java/org/wildfly/security/sasl/util/StringPrep.java, src/test/java/org/wildfly/security/sasl/gssapi/BaseGssapiTests.java, src/test/java/org/wildfly/security/sasl/gssapi/GssapiUtilsUnitTest.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/AbstractTest.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/BasicAuthTest.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/BasicConfidenceTest.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/BasicIntegrityTest.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/NoServerAuthTest.java, src/test/java/org/wildfly/security/sasl/test/ByteStringBuilderTest.java, src/test/java/org/wildfly/security/sasl/test/StringPrepTest.java
Trivial fixes of bugs in tests which was invisible in Java 7 and prevent compilation in Java 8.
* Bad name of SASL server caused usuccessful initialization (`GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos credentails)`) - was ignored by Java 7
* `ByteStringBuilder` cannot append codepoints 0xD8xx (lonely surrogates) - cannot be used to complete test of StringPrep validation - was replaced.
=> Fixes of tests for Java 8

pom.xml, src/main/java/org/wildfly/security/auth/provider/CredentialDecoder.java, src/main/java/org/wildfly/security/auth/provider/X509CertificateCredentialDecoder.java, src/main/java/org/wildfly/security/permission/PermissionActions.java
Add a credential-decoding API.  Requires Java 8, includes build update to effect that change.
=> Credential decoders API

src/main/java/org/wildfly/security/password/impl/DigestPasswordImpl.java, src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java, src/main/java/org/wildfly/security/sasl/digest/DigestClientFactory.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java, src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java, src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java, src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java, src/test/java/org/wildfly/security/sasl/digest/CompatibilityServerTest.java, src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java
**Corrected version of #108:**
* Implemented step three (rspauth generation and checking)
* authzid checking (checking permission to use authorization id)
* QOP selection improved to select by client preferences (order of options in property)
* Fixed integrity (bad seqNum)
* Refactored cipher selection (exception when no common cipher)
* Utils from AbstractDigestMechanism moved into _private.DigestUtils and covered by tests
* Fixed bugs in encryption (+ refactoring)
* Integrity key calculation only at begin of communication, not in every wrap/unwrap
=> [ELY-145][ELY-90] Digest-MD5 - step three + integrity + encryption (corrected)

src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java, src/main/java/org/wildfly/security/password/spec/AlgorithmPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/SaltedSimpleDigestPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/ScramDigestPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/SunUnixMD5CryptPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/UnixSHACryptPasswordSpec.java
PasswordFactorySpi does not currently feel like a clean place to convert Password instances from an alternative PasswordFactorySpi implementation - maybe the correct approach is to go to KeySpec first anyway if using two different providers.
Without these checks if someone say requests a SHA PasswordFactorySpi and passed in a MD5 variant of a password we claim we can support conversion to SHA, we then pretend conversion happened but in the end we pass back the MD5 variant 
However where conversion is really possible (so far only for clear) then that can continue to be supported.
=> [ELY-157] Add checks that the algorithm does match where conversion to a different algorithm is not possible.

src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java, src/main/java/org/wildfly/security/util/NumericIterator.java
Fix of few minor build warnings:
* `[WARNING] .../WildFlySecurityManager.java:[532,17] checkMemberAccess(java.lang.Class<?>,int) in java.lang.SecurityManager has been deprecated`
* in JDK 8 is this method deprecated, so it must be deprecated in subclass too
* `No enclosing instance of type NumericIterator is available due to some intermediate constructor invocation`
* constructor must be called with `this`
=> Fix of few minor build warnings

src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtil.java, src/test/java/org/wildfly/security/apacheds/CryptCompatibilityTest.java, src/test/java/org/wildfly/security/ldap/UserPasswordSuiteChild.java, src/test/resources/Elytron.ldif
{crypt} passwords in Apache DS longer than 8 characters weren't compatible with Elytron because Apache DS uses the standard Unix DES Crypt algorithm instead of the BSD variant of the algorithm (the standard algorithm ignores all characters after the 8th character unlike the BSD variant). I've updated UserPasswordPasswordUtil so that it can now handle both of these password types. 
https://issues.jboss.org/browse/ELY-81
=> [ELY-81] Differentiate between Unix DES Crypt and the BSD variant of Unix DES Crypt in {crypt} userPassword representations

src/main/java/org/wildfly/security/sasl/util/ProtocolSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/ProtocolSaslServerFactory.java, src/main/java/org/wildfly/security/sasl/util/ServerNameSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/ServerNameSaslServerFactory.java
Makes client and server code somewhat more elegant.
=> Add SASL server and client factories which allow the server name and/or protocol to be overridden

src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java, src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java, src/test/java/org/wildfly/security/sasl/digest/DigestTest.java, src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java, src/test/java/org/wildfly/security/sasl/test/ClientCallbackHandler.java, src/test/java/org/wildfly/security/sasl/test/ServerCallbackHandler.java
Implemented pre-hashed passwords into SASL Digest.
Digest now by default try get hashed password using `CredentialCallback(DigestPassword.class)`, if not supported by user callback handler, `PasswordCallback` is used.
=> [ELY-68] Digest SASL - pre-hashed

src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java, src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java, src/main/java/org/wildfly/security/sasl/scram/ScramUtil.java, src/test/java/org/wildfly/security/sasl/digest/DigestTest.java, src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramClientCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramUtilTest.java, src/test/java/org/wildfly/security/sasl/test/ClientCallbackHandler.java, src/test/java/org/wildfly/security/sasl/test/ServerCallbackHandler.java
Scram fixes
* Integer endianing in Hi() calculation
* NameCallback usage (callback handlers use "defaultName" as input in other SASL mechanisms, setName() should be called only by callback handler, not by SaslServer)
Tests
* Basic scram client and server compatibility test by example in RFC
* Testing callback handlers in common sasl.test modified to support non-Digest CredentialCallback
* Digest test changed to work with modified testing callbacks
=> Scram tests and fix + testing callback handler scram support

pom.xml
"Got an exception - expecting EOF, found 'String'"
"unexpected token: >"
Upgrading to newer version of com.puppycrawl.tools.checkstyle and org.wildfly.checkstyle-config.
=> Checkstyle plugin issue with Java 8 syntax checking

src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java, src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java
Tests and fixes of Scram SASL server:
* checking of equality gs2-header in FIRST and FINAL message
* checking of user authorization (to act as given authorization id) (!)
Note: Checking of gs2-header equality could be more efficient, but it would require modification of ByteIterator (adding possibility of go through one field twice - setOffset or similar) or big changes of Scram server (all parsing of gs2-header in first message and only checking in parsing of final message).
=> Scram SASL server - gs2-header and authorization checking

src/main/java/org/wildfly/security/auth/spi/CredentialSupport.java
The only permutation not covered now is for a credential to be obtainable but possibly verifiable, I think by that point the realm will be making the verifiability decision based on the type of the credential type so if it is obtainable either the realm supports verification or it does not - no middle ground.
=> [ELY-193] Allow a credential type to be obtainable but not verifiable or possibly obtainable but not verifiable.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java, src/test/java/org/wildfly/security/auth/JaasSecurityRealmTest.java, src/test/java/org/wildfly/security/auth/TestLoginModule.java, src/test/java/org/wildfly/security/sasl/gs2/Gs2Test.java, src/test/java/org/wildfly/security/sasl/gssapi/BaseGssapiTests.java, src/test/java/org/wildfly/security/sasl/gssapi/JaasUtil.java, src/test/java/org/wildfly/security/sasl/gssapi/JdkClientJdkServer.java, src/test/java/org/wildfly/security/sasl/gssapi/JdkClientWildFlyServer.java, src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientJdkServer.java, src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientWildFlyServer.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/AbstractTest.java
- JAAS logout is now done when AuthenticatedRealmIdentity is disposed
- Subject "CallerPrincipal" group is now used to setup the authenticated identity principal
- Classes have been renamed to follow the convention for acronyms (Jaas instead of JAAS)
=> [ELY-194] JaasSecurityRealm enhancements

src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java, src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java, src/main/java/org/wildfly/security/sasl/util/StringPrep.java, src/main/java/org/wildfly/security/util/ByteStringBuilder.java, src/test/java/org/wildfly/security/sasl/scram/ScramClientCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/test/ClientCallbackHandler.java, src/test/java/org/wildfly/security/sasl/test/ServerCallbackHandler.java, src/test/java/org/wildfly/security/sasl/test/StringPrepTest.java, src/test/java/org/wildfly/security/util/Base64Test.java
Fixed version of #161 
* Added quoting/unquoting of username and authzid into Scram server and client
* Added unquoting into Stringprep
* Fixed missing `&0xFF` in ByteStringBuilder (discovered in Base64 tests)
* Scram server refactoring:
* loginName renamed to userName (could be confusing because in all other SASL mechanisms and RFC is username/userName)
* authorization check moved after checking equality of gs-header in client messages
* parsing of `y` and `n` is identical in final message, so I merged it into one part of switch
* added  checking of equality of parts gs-header (removed checking as one string from base64, because I I overlooked before, channel binding data are only in final client messages)
* More meaningful name of `s`/`proofOffset` variable
=> Scram - quoting, channel binding, gs-header checking fix

src/main/java/org/wildfly/security/auth/ElytronXmlParser.java
Class X509CertificateChainPrivateCredential has been renamed and moved to x500 package and
latest PR has been merged with this class in old location (and old name).
This is simple fix PR.
=> Fix for moved and renamed X509CertificateChainPrivateCredential class

src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java, src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java, src/main/java/org/wildfly/security/sasl/scram/ScramUtil.java, src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java
* Added support of PasswordCallback into scram server
* Refactored scram server to improve readability of handling different password callbacks
* **standalone private methods for different ways of getting salted password**
* Extended scram self test - testing various password callbacks combinations
Please check [getTwoWayPasswordChars()](https://github.com/wildfly-security/wildfly-elytron/pull/183/files#diff-ab25d5b4df92549e681b4c09b9e96bdbR124), if it is what we want to do in (all?) sasl servers/clients. Thanks
=> Scram server - PasswordCallback support + password callbacks into separated methods

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/asn1/DERDecoder.java, src/main/java/org/wildfly/security/auth/provider/jdbc/mapper/PasswordKeyMapper.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtil.java, src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java, src/main/java/org/wildfly/security/sasl/entity/EntityUtil.java, src/main/java/org/wildfly/security/sasl/external/ExternalSaslServer.java, src/main/java/org/wildfly/security/ssl/MechanismDatabase.java, src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java
* Internationalized forgotten warning messages
* More using of `StandardCharsets.UTF_8`
* Using causes of exceptions instead of takeovering only text of messages
* Removed debug printing of password hash to stdout in `UserPasswordCredentialLoader`
=> Missing  	i18n + clearing

src/main/java/org/wildfly/security/WildFlyElytronProvider.java, src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/callback/CredentialUpdateCallback.java, src/main/java/org/wildfly/security/auth/callback/TimeoutCallback.java, src/main/java/org/wildfly/security/auth/callback/TimeoutUpdateCallback.java, src/main/java/org/wildfly/security/password/impl/OneTimePasswordImpl.java, src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java, src/main/java/org/wildfly/security/password/interfaces/OneTimePassword.java, src/main/java/org/wildfly/security/password/interfaces/RawOneTimePassword.java, src/main/java/org/wildfly/security/password/spec/OneTimePasswordAlgorithmSpec.java, src/main/java/org/wildfly/security/password/spec/OneTimePasswordSpec.java, src/main/java/org/wildfly/security/sasl/WildFlySasl.java, src/main/java/org/wildfly/security/sasl/otp/OTP.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslServer.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslServerFactory.java, src/main/java/org/wildfly/security/sasl/otp/OTPUtil.java, src/main/java/org/wildfly/security/util/ByteIterator.java, src/main/java/org/wildfly/security/util/CodePointIterator.java, src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
https://issues.jboss.org/browse/ELY-189
=> [ELY-189] OTP SASL client and server implementation and tests

src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
* RealmCallback on server side should server give realm which client selected
* DigestSaslClient by default support only qop=auth, but I think there is no reason to forbit more secure qops. (If server support integrity and confidency, why should client by default require auth without it? If client want require qop=auth, can use same way by which now set auth-int,auth-conf)
=> Digest Sasl - fix and better default qop

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/SetRealmAuthenticationConfiguration.java
This 'turns on' handling of the RealmCallback on the client
https://issues.jboss.org/browse/ELY-237
=> Make it possible to configure the realm used on the client

pom.xml
JIRA: https://issues.jboss.org/browse/ELY-240
Add JBoss maven repository directly to `pom.xml`. This commit prevents "missing dependencies" build failures when users don't use a custom `.m2/settings.xml` with JBoss repositories defined.
=> [ELY-240] Public JBoss Repository Group added to pom.xml

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/KeyStoreBackedSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/jdbc/mapper/PasswordKeyMapper.java, src/main/java/org/wildfly/security/keystore/PasswordKeyStoreSpi.java, src/main/java/org/wildfly/security/password/impl/BCryptPasswordImpl.java, src/main/java/org/wildfly/security/password/impl/SaltedSimpleDigestPasswordImpl.java, src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java, src/main/java/org/wildfly/security/password/impl/SunUnixMD5CryptPasswordImpl.java, src/main/java/org/wildfly/security/password/impl/UnixMD5CryptPasswordImpl.java, src/main/java/org/wildfly/security/password/impl/UnixSHACryptPasswordImpl.java, src/main/java/org/wildfly/security/password/spec/BasicPasswordSpecEncoding.java, src/main/java/org/wildfly/security/password/util/ModularCrypt.java, src/main/java/org/wildfly/security/password/util/PasswordUtil.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java, src/test/java/org/wildfly/security/auth/provider/jdbc/PasswordSupportTest.java, src/test/java/org/wildfly/security/password/impl/BCryptPasswordTest.java, src/test/java/org/wildfly/security/password/impl/BSDUnixDESCryptTest.java, src/test/java/org/wildfly/security/password/impl/SunUnixMD5CryptTest.java, src/test/java/org/wildfly/security/password/impl/UnixCryptTest.java, src/test/java/org/wildfly/security/password/impl/UnixMD5CryptUtilTest.java, src/test/java/org/wildfly/security/password/impl/UnixSHACryptPasswordUtilTest.java
This pull request contains two commits:
* 6d7f443e48fb9482aacf20111d675133d11e5040 is all about supporting encoders and decoders for ```PasswordSpec``` types. It also contains enhancements to the ```PasswordUtil`` in order to better separate MCF and non-MCF helper methods.
* b7f8b01477f28b8dba34a6ce2299c42ccd0a980b is all about changes to to the ```FileSystemSecurityRealm``` in order to better support credential management and some minor fixes.
This PR depends on https://github.com/wildfly-security/wildfly-elytron/pull/248.
=> PasswordSpec encoders/decoders and filesystem-realm echancements.

src/test/java/org/wildfly/security/auth/client/ClientUtils.java, src/test/java/org/wildfly/security/sasl/plain/PlainTest.java, src/test/java/org/wildfly/security/sasl/scram/BasicScramSelfTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramCallbackHandlerUtils.java, src/test/java/org/wildfly/security/sasl/scram/ScramClientCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java, src/test/java/org/wildfly/security/sasl/test/AnonymousTest.java, src/test/java/org/wildfly/security/sasl/test/BaseTestCase.java, src/test/java/org/wildfly/security/sasl/test/ClientCallbackHandler.java, src/test/java/org/wildfly/security/sasl/test/LocalUserTest.java, src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java, src/test/java/org/wildfly/security/sasl/test/ServerCallbackHandler.java
This is an attempt to eliminate the usage of the test ClientCallbackHandler and the ServerCallbackHandler, and to instead use the real callback handlers. This PR contains the parts which I am happy/confident-ish about, and is a straight-forward port of the tests in question.
There are also parts where I had to change the main classes, mainly working on doing the same for sasl digest. For that I have opened https://github.com/wildfly-security/wildfly-elytron/pull/253, which can be the basis for discussion of what I have found.
=> Real callbacks in SASL tests

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
Support of OTP in FileSystemSecurityRealm + test + fixed parsing of multiple credentials.
Example of generated user XML:
```xml
<credentials>
<password algorithm="bcrypt" format="base64">BQoQo+P/+jgDfsaZrnzedeqqzZ9o088JV/5tatJ06XEMKVuAQCYCiFKr</password>
<otp algorithm="otp-sha1" hash="505d889f90085847" seed="ke1234" sequence="0000000500"></otp>
</credentials>
```
=> OTP in FileSystemSecurityRealm

src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/main/resources/schema/elytron-1_0.xsd
* https://issues.jboss.org/browse/ELY-254
When testing the filesystem realm using a running Wildfly instance, I've found some errors when reading attributes.
The error is related with the namespace validation, which must be changed in order to also consider empty namespaces.
Also, we can improve how the document and start elements are written and avoid specify the namespace all the time.
Basically, I've considered the same logic from Wildfly Core regarding how both ```XMLStreamReader``` and ```XMLStreamWriter``` are being used.
=> [ELY-254] - Improvements to FileSystemRealm regarding XML writing and namespace validation.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/PasswordValidationTest.java
* https://issues.jboss.org/browse/ELY-269
Accordingly with previous discussions, we should avoid using String values when verifying credentials.
Beside that, when using the JDBC and LDAP realms, the message is wrong, indicating that String values are also supported.
=> [ELY-269] - Wrong message when using a String to verify credentials.

src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/ModifiableRealmIdentity.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
Modified interface `ModifiableRealm` to allow change one of credentials and implemented into `FileSystemSecurityRealm`.
`setCredential(Object)` replace credential of the same type (and algorithm in case of Password/Key). If identity has not such credential yet, it is added.
Required for Kabirs implementation of OTP auth which need update `OneTimePassword` on every login. (And later for password change and similar.)
=> setCredential into ModifiableRealm and FileSystemSecurityRealm

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/ldap/CredentialPersister.java, src/main/java/org/wildfly/security/auth/provider/ldap/IdentityCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/IdentityCredentialPersister.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/auth/provider/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java, src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java, src/test/java/org/wildfly/security/ldap/PasswordSupportTest.java, src/test/resources/ldap/elytron-otp-tests.ldif
OTP credential loading from ldap (OtpCredentialLoader).
* Parts of OTP credential (hash, seed, iterations count) stored in standalone attributes.
* Binary attributes are stored in base64.
Used my testing ldap schema, because only schema I found similar to what we need is http://code.google.com/p/otpd/source/browse/trunk/userops/otp.schema?r=51 where would have to be same attribute names used in little different meaning (hash => key, seed => serial, algorithm => vendor) - I think using custom schema is better in such case.
Writing credentials back to LDAP is not implemented yet - do you have same comments about current way of storing otp credential before I start implement it?
=> LDAP OTP credential loading + persisting

pom.xml, src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/authz/jacc/ElytronPolicyConfiguration.java, src/main/java/org/wildfly/security/authz/jacc/ElytronPolicyConfigurationFactory.java, src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java, src/main/java/org/wildfly/security/authz/jacc/SecurityIdentityHandler.java, src/main/java/org/wildfly/security/authz/jacc/package-info.java, src/main/java/org/wildfly/security/authz/package-info.java, src/test/java/org/wildfly/security/authz/jacc/AbstractAuthorizationTestCase.java, src/test/java/org/wildfly/security/authz/jacc/ElytronPolicyEnforcementTest.java, src/test/java/org/wildfly/security/authz/jacc/LinkPolicyConfigurationTest.java, src/test/java/org/wildfly/security/authz/jacc/PolicyConfigurationTest.java, src/test/java/org/wildfly/security/authz/jacc/SecurityIdentityRule.java, src/test/java/org/wildfly/security/authz/jacc/StandardPolicyEnforcementTest.java, src/test/resources/org/wildfly/security/authz/jacc/clear.properties
* https://issues.jboss.org/browse/ELY-179
Provides an implementation of the JSR-115, Java Authorization Contract for Containers (JACC).
These changes were tested to check backward compatibility with the existing support provided by PicketBox in WildFly. Testes were executed based on:
* Wildfly 10.0.0.Beta1-SNAPSHOT (latest upstream)
* [TCK 7](https://developer.jboss.org/wiki/TCK7Guide)
* [JavaEE 7 Samples](https://github.com/javaee-samples/javaee7-samples/tree/master/jacc)
* Existing integration tests in WildFly test suite
=> [ELY-179] Initial implementation (JACC-based authorization)

src/test/java/org/wildfly/security/sasl/gs2/Gs2Test.java, src/test/java/org/wildfly/security/sasl/gssapi/BaseGssapiTests.java, src/test/java/org/wildfly/security/sasl/gssapi/GssapiTestSuite.java, src/test/java/org/wildfly/security/sasl/gssapi/JaasUtil.java, src/test/java/org/wildfly/security/sasl/gssapi/JdkClientJdkServer.java, src/test/java/org/wildfly/security/sasl/gssapi/JdkClientWildFlyServer.java, src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java, src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientJdkServer.java, src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientWildFlyServer.java, src/test/java/org/wildfly/security/sasl/gssapi/compatibility/AbstractTest.java, src/test/resources/logging.properties
This PR changes only tests. I have configured GssapiServer to use keyTab to get initial credential of the server. It contains also keyTab generation when KDC starts.
To get credentials for server from keyTab is usual use case.
=> [ELY-283] Add possibility to use keytab in GSS API tests

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtil.java, src/test/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtilTest.java, src/test/resources/ldap/elytron-otp-tests.ldif
* Persisting text passwords (attribute `userPassword`) into LDAP
* Loading password from LDAP case-insensitive for type prefix (`{CRYPT}`/`{SHA1}`/...)
* Checking of type loaded password separated from parsing
* +added timeout into OTP testing LDIF
=> LdapRealm - password persisting

src/main/java/org/wildfly/security/auth/callback/CredentialCallback.java, src/main/java/org/wildfly/security/auth/client/SetKeyManagerCredentialAuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/auth/util/ElytronAuthenticator.java, src/main/java/org/wildfly/security/mechanism/MechanismUtil.java, src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java, src/main/java/org/wildfly/security/sasl/entity/EntitySaslClient.java, src/main/java/org/wildfly/security/sasl/entity/EntitySaslServer.java, src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java, src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslServer.java, src/main/java/org/wildfly/security/sasl/util/KeyManagerCredentialSaslServerFactory.java
This means anything using the Callback does not need to understand the structure of the internal Map.
Also it felt like we were using 'Supported' and 'Allowed' interchangeable so have just switched to 'Supported'.
=> [ELY-326] Switch to use a Builder for creating CredentialCallback

src/main/java/org/wildfly/security/auth/callback/CredentialCallback.java, src/main/java/org/wildfly/security/auth/provider/AggregateSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/KeyStoreBackedSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/SimpleMapBackedSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/RealmIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Allow getCredential on the RealmIdentity to be able to reso…lve the full credential name list against the Map of supported credential types with their supported algorithms.
At the same time the getCredential method that realms are required to implement on their identity is reduced down to the most basic: -
Credential getCredential(String credentialName);
Realms can then optionally choose to implement the stronger variants if they make sense to the realm, otherwise default implementations are provided.
=> [ELY-345]  Enhancements to the getCredential API on the realm identities.

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-1_0.xsd, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
https://issues.jboss.org/browse/ELY-367
This is needed to be able to create a client from xml config using DIGEST authentication which seems to need a realm as shown in https://github.com/jboss-remoting/jboss-remoting/pull/53.
I went with 'use-mechanism-realm' rather than 'use-realm' or 'set-realm' as per David's suggestion.
=> Ability to set the realm via xml

src/main/java/org/wildfly/security/auth/provider/ldap/AttributeMapping.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java, src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingTest.java, src/test/java/org/wildfly/security/ldap/AttributeMappingTest.java, src/test/java/org/wildfly/security/ldap/GroupMappingTest.java, src/test/java/org/wildfly/security/ldap/RoleMappingTest.java
The class was only public as it contained a configuration class that is used elsewhere.
=> [ELY-380] Reduce visibility of LdapSecurityRealm.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java, src/test/java/org/wildfly/security/ldap/ModifiabilityTest.java, src/test/java/org/wildfly/security/ldap/TestEnvironmentTest.java
* Creating and removing identity in Ldap realm. (Usernames escaping in DN should be safe)
* Parent node and attributes (include objectClass) of new identities has to be set as part of IdentityMapping (Do you agree this a good place for this configuration?)
=> LDAP security realm - create + delete identity

src/main/java/org/wildfly/security/auth/server/MechanismConfiguration.java, src/main/java/org/wildfly/security/auth/server/MechanismRealmConfiguration.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Also created https://github.com/wildfly-security/elytron-subsystem/pull/136 for the corresponding Elytron subsystem changes.
=> [ELY-394] Allow MechanismConfiguration and MechanismRealmConfiguration to override the RealmMapper

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/ModifiabilityTest.java
* Setting attributes of identity in ldap realm
* Setting of RDN attribute (=renaming of node) supported
* Attributes defined in mapping by filter (loaded from other ldap node then user) ignored if enclosed
Just note, that if the username is in attribute mapping, it allow change it too, but it is not reflected by Identity object. (It cannot be updated, because "name" is final)
=> LDAP realm - attributes modifiable

src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
https://issues.jboss.org/browse/ELY-407
=> [ELY-407] Add the ability for SecurityIdentity.getRoles() to fall back to the default if the given category is undefined

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/provider/ldap/DirContextFactory.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/auth/provider/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/provider/ldap/SimpleDirContextFactoryBuilder.java, src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java, src/test/java/org/wildfly/security/ldap/ModifiabilityTest.java
This is exteded #361 with pagination.
Pagination require InitialLdapContext instead of InitialDirContext, because which was added standalone SimpleLdapContextFactoryBuilder, which is not ideal - should be discussed if make SimpleDirContextFactoryBuilder less private and allow subclassing.
=> LDAP security realm - iterability with pagination

pom.xml
Not all tests pass on JDK9 but mostly due bugs/issues in jmockit.
If I do use newer version of jmockit, it somewhat works on JDK9 but few tests completely fail on all jdks.
=> Make build work on JDK9

src/main/java/org/wildfly/security/auth/provider/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/CloseableIterator.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
* Added support of closing iterator of FileSystemRealm
* new interface **CloseableIterator**, which I suggest to start to use in all modifiable realms. To prevent collision with existing PRs can api changed gradually:
1. add interface (this PR)
2. gradually start using it in individual realms (only FileSystemRealm in this PR)
3. modify ModifiableSecurityRealm to force CloseableIterator as output of getRealmIdentityIterator()
=> FileSystem realm - correct iterator closing

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, src/main/java/org/wildfly/security/http/HttpServerCookie.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/HttpServerResponse.java, src/main/java/org/wildfly/security/http/HttpServerSession.java, src/main/java/org/wildfly/security/http/HttpSessionSpi.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java
* Added a SPI for Session Management
* Added new methods to ```HttpExchangeSpi``` to support things like cookies, request parameters, etc.
=> [ELY-431] - Changes to the Elytron HTTP API/SPI to support a broader range of authentication mechanisms

src/main/java/org/wildfly/security/ssl/MechanismDatabase.java
The scenario that was causing the WARN to be logged was: -
TLS_RSA_FIPS_WITH_DES_CBC_SHA           = alias:TLS_RSA_WITH_DES_CBC_SHA
TLS_RSA_WITH_DES_CBC_SHA                = alias:SSL_RSA_WITH_DES_CBC_SHA
SSL_RSA_WITH_DES_CBC_SHA                = DES-CBC-SHA,RSA,RSA,DES,SHA1,SSLv3,false,LOW,false,56,56
I did consider if we should just update the database and avoid the alias of an alias but if we need this in future I think safer to ensure the code can handle it.
Secondly at some point I think we should review the logging in this initialisation, this properties file is effectively part of our code - I am wondering if we should just fail to load on errors either using an exception or an assertion.  That way errors in the file can be easily detected in our testsuite instead of waiting all …
=> [ELY-385] Handle aliases of aliases in mechanism database.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/SimpleMapBackedSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/oauth2/OAuth2SecurityRealm.java, src/main/java/org/wildfly/security/auth/server/ModifiableRealmIdentity.java, src/main/java/org/wildfly/security/auth/server/RealmIdentity.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/evidence/SecurityIdentityEvidence.java, src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java
https://issues.jboss.org/browse/ELY-178
=> [ELY-178] Provide the ability to propagate an established security identity from one domain to another

src/test/java/org/wildfly/security/sasl/gssapi/JaasUtil.java
Fix for method used by Elytron tests.
https://issues.jboss.org/browse/ELY-482
=> [ELY-482] Fixed createGssProxyConfiguration from JaasUtil for IBM JDK

src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-475
=> [ELY-475] Update the CLIENT_CERT authentication mechanism to be able to make use of an established identity

src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
For the consistency principal name used in `SecurityDomain.mapPrincipal()` should be identical with `SecurityIdentity.createRunAsIdentity()`.
Added realm-info NameRewriter into mapPrincipal().
Related test:
https://github.com/wildfly-security/elytron-subsystem/pull/171/files#diff-984fedede558a8dc0c583a22962db97bR59
=> Principal name in Domain.mapPrincipal() by createRunAsIdentity()

src/main/java/org/wildfly/security/http/HttpScope.java
This is a very small change from the Elytron perspective, most of the real work is in our integration and in WildFly where we need to join all of the implementations together.
This PR also includes [ELY-492] which is a customisable GenericHttpScope implementation that the integration projects can use to assemble something with the features supported.
=> [ELY-464] Add access to resources under different HttpScopes

src/main/java/org/wildfly/security/auth/client/ConfigurationKeyManager.java, src/main/java/org/wildfly/security/x500/X500PrincipalUtil.java
The end result of this is that it can now be aggregated with different implementations so if this implementation does not support the Principal type another may be used.
=> [ELY-495] Only convert to an X500Principal if the Principal is already an X500Principal or X500Name.

src/main/java/org/wildfly/security/http/HttpScope.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/HttpServerScopes.java
Again a very tiny change in Elytron to add this API, most of the work being in the integration projects.
=> [ELY-468] Support registration of a Consumer to be called when a scope is being destroyed.

src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java
This PR also includes some refactoring to move the trust check from ```verifyEvidence``` in ```ServerAuthenticationContext``` to the ```verifyEvidence``` method in the ```State```.
=> [ELY-178] Add the ability to support inflow when the domains do not have a common realm

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
This will allow us to ensure that when propagating a security identity from one domain to another, any peer identities associated with the security identity also get propagated.
https://issues.jboss.org/browse/ELY-503
=> [ELY-503] Add a PeerIdentitiesAssignedState to the ServerAuthenticationContext state machine

pom.xml, src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java, src/test/java/org/wildfly/security/sasl/digest/CompatibilityServerTest.java
https://issues.jboss.org/browse/ELY-311
=> [ELY-311] JMockit upgrade (for JDK9)

src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java
:warning: This PR will break some changes in the integration project but I think better to get it in and then I will follow up getting those repos back up and running.
=> [ELY-511] Use Collections instead of arrays for information accessible from the request object.

src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java
Also add a set of methods for direct parameter access without requiring the full Map to be provided.
=> [ELY-510] Adjust documentation of getParameters so it will apply to both query parameters and form data parameters

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/HttpServerAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java, src/main/java/org/wildfly/security/http/util/SecurityIdentityServerMechanismFactory.java, src/main/java/org/wildfly/security/sasl/WildFlySasl.java
This pull request predominantly pulls the ServerAuthenticationContext out of the HTTP mechanism API and also some related clean up following on from the ServerAuthenticationContext clean up.
Once this one is merged I have fixes for Elytron Web and the Subsystem to get both of those projects building and running again.
I then need to get the PermissionMapper support enhanced so we can make the WildFly integration usable again before I finish off the other HTTP changes we have discussed.
=> [ELY-521] And related changes following ServerAuthenticationContext Clean Up

src/main/java/org/wildfly/security/auth/server/PrincipalDecoder.java, src/main/java/org/wildfly/security/x500/X500AttributePrincipalDecoder.java, src/main/java/org/wildfly/security/x500/X500PrincipalUtil.java, src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java, src/test/java/org/wildfly/security/x500/X500PrincipalUtilTest.java
Made the following changes:
* Added the ability to decode attribute values in reverse order
* Added the ability to specify where to start decoding from
* Added a constant principal decoder
* Added a concatenating principal decoder that combines the results of two or more principal decoders
* Added the ability to specify a set of attributes that must be present in an X.500 principal
https://issues.jboss.org/browse/ELY-221
=> [ELY-221] X.500 principal mapper improvements

src/main/java/org/wildfly/security/authz/Roles.java, src/main/java/org/wildfly/security/authz/SimplePermissionMapper.java
I realise that it is going to be easier to handle the class loading within the subsystem, from that point we are only one step away from instantiation with the appropriate constructor.  We can then use a java.security.Permissions object to manage creating a bundled PermissionCollection which we can then wrap with a PermissionVerifier.
So the Elytron implementation just becomes a mapping to a list of static PermissionVerifier instances as well as some rules regarding how to combine multiple matches.
=> [ELY-530] Simple PermissionMapper Implementation

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, src/main/java/org/wildfly/security/http/HttpServerMechanismsResponder.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/HttpServerResponse.java, src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java, src/main/java/org/wildfly/security/http/impl/UsernamePasswordAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java
This can either go in now or wait until I have the remaining scenarios implemented.
This mechanism is now at the point where it is working by making use of redirects to redirect the client to the login page and after authentication is complete redirecting back to the secured resource that was originally requested.
Subsequent changes will be made to support: -
Sending the login and error pages directly to the client.
HTTP SPI adjustments to optionally support the server suspending a request / resuming a previous request.
Dispatching login / error page handling to the server.
=> [ELY-470] Form authentication.

src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
Started a chat in HipChat regarding if this would be better ALL:!aNULL:!eNULL or !aNULL:!eNULL:ALL - this PR matches the first form.
If the DEFAULT value is prefixed by a delete fully selector that will have been previously applied so the 'ALL' portion will not add those back in.
=> [ELY-395] First add all the OpenSSL cipher suites so we can remove those with no authentication or encryption.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/callback/MechanismInformationCallback.java, src/main/java/org/wildfly/security/auth/server/AbstractMechanismAuthenticationFactory.java, src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java, src/main/java/org/wildfly/security/auth/server/MechanismAuthenticationFactory.java, src/main/java/org/wildfly/security/auth/server/MechanismConfiguration.java, src/main/java/org/wildfly/security/auth/server/MechanismConfigurationSelector.java, src/main/java/org/wildfly/security/auth/server/MechanismInformation.java, src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java, src/main/java/org/wildfly/security/http/impl/UsernamePasswordAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java, src/main/java/org/wildfly/security/sasl/util/SetMechanismInformationSaslServerFactory.java, src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
This is not complete as it still needs a callback to supply this initial information for selection however this shows leaving selecting the MechanismConfiguration until as late as possible to allow additional information to be provided.
Would probably add some aggregate methods to MechanismConfigurationSelector, also will probably add a method that takes a Predicate<MechanismInformation> - when it comes to our subsystem I think will most likely go for an ordered list of MechanismConfiguration instances and first to match on the MechanismInformation wins.
An additional side effect is that this means MechanismConfiguration no longer drives the availability of mechanisms - I think this is Ok if we make sure we have filters by name available - it also reduces the amount of default …
=> [ELY-554] Switch to using a MechanismConfigurationSelector

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java, src/test/resources/ldap/elytron-credential-tests.ldif
* Test of userPassword change
* Setting identity to null after delete (force reload) (to be consistent with FileSystemRealm)
=> LdapRealm - password change test + null identity after remove

src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java, src/main/java/org/wildfly/security/sasl/util/SetMechanismInformationSaslServerFactory.java
This approach attempts to select the ```MechanismConfiguration``` when setting the ```MechanismInformation```. This allows ```createSaslServer``` to just return ```null``` if the ```MechanismConfiguration``` cannot be resolved. For the HTTP case, we can just return if the ```MechanismConfiguration``` cannot be resolved when evaluating an HTTP request.
=> [ELY-580] Mechanism selection fixes

src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordPasswordUtil.java, src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java
UserPasswordCredentialLoader claimed it support any password, so if this loader was defined before OTP loader, OTP loading/persisting has failed.
Solved by adding test against list of algorithm names.
Related to https://github.com/wildfly-security/elytron-subsystem/pull/185
=> ldap userPassword - support status fix

src/main/java/org/wildfly/security/password/interfaces/RawClearPassword.java
Class RawClearPassword doesn't implement method destroy() from Destroyable interface thus causing warnings in runtime. 
It should be implemented anyway.
=> [ELY-589] RawClearPassword should implement Destroyable interface

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/ldap/CredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/CredentialPersister.java, src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java, src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java, src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java, src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java, src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java, src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java, src/test/java/org/wildfly/security/ldap/PasswordValidationSuiteChild.java, src/test/java/org/wildfly/security/ldap/PrincipalMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/TestEnvironmentSuiteChild.java, src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java
* DirContextFactory replaced by ExceptionSupplier<DirContext, NamingException>
* Required for movement of DirContext definition in subsystem from LDAP realm to standalone block
* Obtaining DirContext, which was done in every CredentialLoader, is now happening just once - in LdapRealm
Changes API - should be merged together with https://github.com/wildfly-security/elytron-subsystem/pull/198
=> [ELY-462] DirContext supplier instead of DirContextFactory

src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
https://issues.jboss.org/browse/ELY-620
=> [ELY-620] Add the ability for SecurityIdentity.createRunAsIdentity() to handle an anonymous authorizationId

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/keystore/LdapKeyStore.java, src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java
Improvements of LdapKeyStore made in relation to integration into subsystem.
**LdapKeyStore**
* added support of recursive LDAP search and search time limit
* removed useless iteratorFilterArgs and certificateChainType attributes (type of certificates in chain must be the same as type of main certificate of alias)
* default values of LDAP filters (based on attribute names)
* added javadoc
=> LdapKeyStore improvements

pom.xml
this will make it work with jdk9 b135 and newer.
=> make it compile and run tests on recent jdk9 builds

src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java, src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
* added useCipherSuitesOrder to the Builder - https://issues.jboss.org/browse/ELY-643
* fixed setting of needClientAuth+wantClientAuth - Zach's issue - https://issues.jboss.org/browse/ELY-646
=> [ELY-643] SSLContext - added useCipherSuitesOrder + needClientAuth fix

src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-654
=> [ELY-654] Ensure that negative values are converted to zero when setting sessionCacheSize and sessionTimeout in SSLSessionContext.

src/main/java/org/wildfly/security/credential/store/impl/KeystorePasswordStore.java
https://issues.jboss.org/browse/ELY-656
=> [ELY-656] while initializing KeystorePasswordStore an NPE is thrown instead of proper log message

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java, src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java
https://issues.jboss.org/browse/ELY-663
* fixed setting of referral mode in DirContext
* LdapRealm - added posibility to set custom search filter to obtain identity by name (need for referral using)
* handling errors of name to LdapName conversion
* the `if (this.name.startsWith(identityMapping.rdnIdentifier))` -condition should be revised yet! (but not related to this issue)- https://github.com/wildfly-security/wildfly-elytron/pull/514
* added more traces
=> [ELY-663] DirContext - referral mode, LdapRealm - custom filter

src/main/java/org/wildfly/security/auth/realm/ldap/CredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java
https://issues.jboss.org/browse/ELY-668
Realm.getCredentialAcquireSupport() was using DirContext, which was causing WildFly/Undertow was unable to start without LDAP server online.
=> [ELY-668] LdapRealm acquire support without DirContext

src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-673
=> [ELY-673] Empty result of password search in Elytron ldap-realm causes NPE

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/auth/client/SetChoiceAuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/SetParameterSpecAuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/SetRealmAuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/SetTrustManagerAuthenticationConfiguration.java, src/main/resources/schema/elytron-1_0.xsd
Also withouts SetCallbackHandlerAuthenticationConfiguration for AuthenticationConfiguration instances that handle a Callback.
Reduced visibility of some methods on the XML parser as the parser.
=> [ELY-696] Update configuration to support using the default realm.

src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
This allows other configured mechanisms an opportunity to authenticate.
=> [ELY-734] Don't report an error if there is no peer cerificate, instead report no authentication in progress and return.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
https://issues.jboss.org/browse/ELY-732
(only change of IOException to RealmUnavailableException here - rest in the subsystem)
=> [ELY-732] properties-realm error messages

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java, src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java, src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java, src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java, src/test/java/org/wildfly/security/ldap/DirectEvidenceVerificationSuiteChild.java, src/test/java/org/wildfly/security/ldap/LdapTestSuite.java, src/test/java/org/wildfly/security/ldap/X509EvidenceVerificationSuiteChild.java, src/test/resources/ldap/elytron-x509-verification.ldif
https://issues.jboss.org/browse/ELY-433
Allows to add X509EvidenceVerifier to the LdapRealm, which will use one or more CertificateVerifiers. Every verifier check same client certificate property (serial number, subject DN or hash of the certificate) against information in LDAP.
=> [ELY-433] LdapRealm - X509 evidence verification

src/main/java/org/wildfly/security/http/impl/NonceManager.java
Also convert the salt to hex to ensure it can be logged.
=> [ELY-750] Protect against NullPointerException where no stalts are provided.

src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java, src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Once more with correct JIRA now (replaces the closed PR #554).
https://issues.jboss.org/browse/ELY-757
=> ELY-757 Testsuite: use Locale parameter in String.toLowerCase() calls

src/main/java/org/wildfly/security/auth/client/MatchSchemeSpecificPartRule.java, src/main/java/org/wildfly/security/sasl/util/DisposedCallbackSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/DisposedCallbackSaslServerFactory.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-731
=> [ELY-731] Coverity static analysis: Missing parent calls in Elytron

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/HttpServerAuthenticationMechanismFactory.java, src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-738
=> [ELY-738] Coverity static analysis: Dereference null return value in SingleSignOnServerMechanismFactory (Elytron)

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/auth/client/SetProtocolAuthenticationConfiguration.java, src/main/resources/schema/elytron-1_0.xsd, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
Also fixes the without(Class,Class) method.
=> [ELY-764] Allow the protocol to be specified.

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/RealmIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-743
=> [ELY-743] Coverity static analysis: Dereference null return value in ServerAuthenticationContext (Elytron)

src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-741
=> [ELY-741] Coverity static analysis: Dereference null return value in SSLConfiguratorImpl (Elytron)

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java, src/main/java/org/wildfly/security/password/spec/DigestPasswordSpec.java, src/main/java/org/wildfly/security/util/DecodeException.java, src/test/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealmTest.java, src/test/java/org/wildfly/security/authz/jacc/AbstractAuthorizationTestCase.java
https://issues.jboss.org/browse/ELY-791
subsystem part: https://github.com/wildfly-security/elytron-subsystem/pull/311
* [ELY-791] handling of password decode exception
* unified "users/passwords" properties file to "users" (API change - require subsystem part)
=> [ELY-791] properties realm error handling

src/main/java/org/wildfly/security/auth/realm/ldap/AttributeMapping.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-749
=> [ELY-749] String.toUpperCase() is used without Locale in AttributeMapping class (Elytron)

src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java, src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
Tests for `ExternalSasl*` implementations. Some tests are ignored with ELY issue number provided.
=> SASL External mechanism tests

src/main/java/org/wildfly/security/EmptyProvider.java, src/main/java/org/wildfly/security/keystore/LdapKeyStore.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-751
=> [ELY-751] Coverity static analysis: Explicit null dereferenced in LdapKeyStore (Elytron)

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/ldap/AttributeMapping.java, src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/AttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/GroupMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java, src/test/java/org/wildfly/security/ldap/RoleMappingSuiteChild.java, src/test/resources/ldap/elytron-role-mapping-tests.ldif
Based on https://github.com/wildfly-security/wildfly-elytron/pull/564 (only "[ELY-804]" commit to review here)
Related subsystem change: https://github.com/wildfly-security/elytron-subsystem/pull/316
https://issues.jboss.org/browse/ELY-804
LdapRealm:
* Added support of direct verification with referred directory
* Added support of THROW referral mode
* realm iterating refactoring: pagination + referrals handling in `LdapSecurityRealm.LdapSearch`
* no pagination/referrals handling outside of LdapSearch object anymore :)
=> [ELY-804] LdapRealm referrals: direct verification + THROW mode + iterating refac

src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-748
=> [ELY-748] Coverity static analysis: Explicit null dereferenced in FileSystemSecurityRealm (Elytron)

pom.xml, src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/auth/client/SetCredentialsConfiguration.java, src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java, src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java, src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java, src/main/resources/schema/elytron-1_0.xsd, src/test/java/org/wildfly/security/auth/realm/token/OAuth2TokenSecurityRealmTest.java, src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientTest.java, src/test/resources/org/wildfly/security/sasl/oauth2/wildfly-oauth2-test-config.xml
The OAuth2 changes have already been reviewed and approved, this PR adds two additional commits so that the configured Provider[] is used for PasswordFactory discovery.
There are a couple of places within the configuration parsing passwords and not using configured Provider[] these will be picked up under https://issues.jboss.org/browse/ELY-837
=> [ELY-840] Use configured Provider[] for PasswordFactory Creation.  Includes [ELY-658] OAuth2 Changes

src/main/java/org/wildfly/security/sasl/external/ExternalSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java, src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java, src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-799
=> [ELY-799] Elytron ExternalSaslServerFactory returns EXTERNAL mechanism name when Sasl.POLICY_PASS_CREDENTIALS provided

src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java, src/test/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealmTest.java, src/test/resources/org/wildfly/security/auth/realm/groups.properties
https://issues.jboss.org/browse/ELY-869
* Loading users from groups file when they dont exist in users file.
* Allowed property realm without users file.
=> [ELY-869] properties realm - users in roles file only

src/main/java/org/wildfly/security/auth/realm/ldap/AttributeMapping.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/AttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/GroupMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java, src/test/java/org/wildfly/security/ldap/RoleMappingSuiteChild.java, src/test/resources/ldap/elytron-role-mapping-tests.ldif
Subsystem part: https://github.com/wildfly-security/elytron-subsystem/pull/347
LdapRealm:
* [ELY-856] added "reference" param (alternative to filter - use value in user LDAP attribute as DN of entry, from where is loaded value of identity attribute - for "memberOf")
* refactored AttributeMapping builder to keep simple
* fixed search identity by DN - added "recursive-search" checking
* fixed role-recursion: prevent cycling when groups contains each other (before recursion-limit, no multiple occurences of the same role) (as Picketbox support it)
* [ELY-794] changed wildcards in attribute filter: {0} for username, {1} for user DN (to be identical with Picketbox)
=> [ELY-856][ELY-794] LdapRealm - memberOf + username wildcard

src/main/java/org/wildfly/security/util/AbstractAlgorithmParametersSpiImpl.java, src/test/java/org/wildfly/security/util/AbstractAlgorithmParametersSpiImplTest.java
`AbstractAlgorithmParametersSpiImpl::engineInit(AlgorithmParameterSpec)`
should use the given AlgorithmParameterSpec not the `parameterSpec`
field.
=> [ELY-870] AbstractAlgorithmParametersSpiImpl::engineInit is using wrong reference

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/auth/client/ModuleLoader.java
Move code related to JBoss Modules in a separate ModuleLoader class
that is only used and loaded when JBoss Modules is actually required.
JIRA: https://issues.jboss.org/browse/ELY-872
=> [ELY-872] JBoss Modules is an optional dependency

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/AttributeMapping.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/AttributeMappingSuiteChild.java, src/test/java/org/wildfly/security/ldap/RoleMappingSuiteChild.java, src/test/resources/ldap/elytron-role-mapping-tests.ldif, src/test/resources/org/wildfly/security/auth/realm/nonldap.properties
* [ELY-881] Fix of {0} behavior on role-recursion
* setting of attribute to be considered role name (to be passed on place of {0} on roles of role search)
* [ELY-869] allowed obtaining authorization identity without existing identity entry (aggregate realm + ldap realm as authorization realm only)
* [ELY-760] attributes should not be obtained before successful authentication (now it is part of obtaining of authorization identity)
https://issues.jboss.org/browse/ELY-881
https://issues.jboss.org/browse/ELY-869
https://issues.jboss.org/browse/ELY-760
Subsystem part: https://github.com/wildfly-security/elytron-subsystem/pull/369
(backward compatible - subsystem PR can be merged later)
=> [ELY-869][ELY-760][ELY-881] LdapRealm fixes

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java, src/main/java/org/wildfly/security/credential/GSSCredentialCredential.java, src/main/java/org/wildfly/security/credential/GSSKerberosCredential.java, src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java, src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java, src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java, src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java, src/main/java/org/wildfly/security/sasl/util/SaslMechanismInformation.java, src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java, src/test/java/org/wildfly/security/sasl/gssapi/GSSSecurityFactorySuiteChild.java
To receive a delegated credential a KerberosTicket is required, allow this to be optionally associated with the GSSCredentialCredential.
Within the SpnegoAuthenticationMechanism assume this ticket is available on the ACC, then associate any delegated credential with the identity.
=> [ELY-875] / [ELY-877] Ongoing SPNEGO Credential Delegation

src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSession.java
https://issues.jboss.org/browse/ELY-892
This fixes lock timeouts when SingleSignOnManager is distributed.
=> ELY-892 Invalidate sso session only from node that started logout

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java
Now that https://github.com/wildfly-security/elytron-web/pull/55 was merged, this constructor is no longer referenced.
=> Drop deprecated DefaultSingleSignOnSessionFactory constructor.

src/main/java/org/wildfly/security/WildFlyElytronProvider.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Support for `PKCS12` KeyStore in format in SunJCE provider requires that
the algorithm id is one of the known OIDs registered with one of the
security providers. Using an unknown OID results in
`java.security.NoSuchAlgorithmException`.
It seems fitting that the algorithm id of `SecretKey` stored in the
underlying KeyStore would be PKCS#7 data (`1.2.840.113549.1.7.1`).
`WildFlyElytronProvider` was extended to add PKCS#7 Data OID as one of
the algorithm identifiers it provides an alias for, which would in turn
be picked up by the `PKCS12` KeyStore implementation.
`KeyStoreCredentialStore` is now using this PKCS#7 Data OID to specify
`SecretKey` type instead of `xxx`.
=> [ELY-876] Support for PKCS12 KeyStore format in KeyStoreCredentialStore

src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
@zregvart Unfortunatly need to disable this test at the moment as it seems to be triggering a failure in the CI environment.
=> [ELY-920] Disable PKCS#12 testing due to failures in CI environment.

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-924
=> [ELY-924] Coverity static analysis: Resource leak in LdapSecurityRealm (Elytron)

src/main/java/org/wildfly/security/sasl/external/ExternalSaslServer.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-803
=> [ELY-803] Elytron ExternalSaslServer must finish with null returned from evaluateResponse method

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/ldap/CredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/CredentialPersister.java, src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java, src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/ThreadLocalSSLSocketFactory.java, src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java, src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
Current LdapRealm implementation fails to authenticated users through referrals.
As context.getAttributes() does not want to work correctly with referrals, only search works ok, I has changed way of obtaining attributes - they are obtained using identity search now.
Does not depend on related subsystem change: https://github.com/wildfly-security/elytron-subsystem/pull/382
(subsystem change is only tests extending)
https://issues.jboss.org/browse/ELY-804
=> [ELY-804] LdapRealm - rework for working referrals

src/main/java/org/wildfly/security/http/HttpConstants.java
https://issues.jboss.org/browse/ELY-905
(no subsystem dependency)
Grren tests will require https://github.com/wildfly-security/elytron-web/pull/63
=> [ELY-905] CLIENT_CERT mechanism name by HttpServletRequest

src/test/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealmTest.java, src/test/resources/org/wildfly/security/auth/realm/specialchars.properties
https://issues.jboss.org/browse/ELY-908
Fixed wrong encoding of specialchars.properties
=> [ELY-908] Fixed LegacyPropertiesSecurityRealmTest

src/main/java/org/wildfly/security/WildFlyElytronProvider.java, src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/key/RawSecretKeyFactory.java, src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java, src/test/java/org/wildfly/security/key/RawSecretKeyFactoryTest.java
Adds RawSecretKeyFactory and adds it as a service of
WildFlyElytronProvider so that Credential store implementation can use
PKCS#12 KeyStore type.
ELY-920 removed PKCS#12 test, after ELY-XXX this re-enables the removed
test. Also added reflection trickery to make JCE think that
WildFlyElytronProvider's JAR file has been verified.
=> ELY-926  PKCS#12 support in CredentialStore with JDK-8005408

src/main/java/org/wildfly/security/http/HttpScope.java, src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
Also updated TRACE logging to check the session actually exists before reporting it's status.
The TRACE logging is still slightly questionable as it assumes the cache is session based but accurate enough for our current implementation, main point being this clears the NPE a user would experience just by enabling TRACE logging making any problem they are trying to debug far worse.
=> [ELY-921] Update session scope implementation to check if the session exists before returning the ID.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java, src/test/java/org/wildfly/security/credential/store/CredentialStoreBuilder.java, src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java, src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
https://issues.jboss.org/browse/ELY-933
This PR will change the default behaviour of KeyStoreCredentialStore to not automatically create new storage file. 
We should enforce this at implementation level rather than on subsystem level as custom implementers might have a different reasons to resolve this as we do.
=> [ELY-933] Add possibility to disable creation of CS storage from scratch

src/main/java/org/wildfly/security/keystore/LdapKeyStore.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-751 (Reopen)
Replaced "LdapRealm" -> "LdapKeyStore"
=> [ELY-751] (Reopen) Coverity static analysis: Explicit null dereferenced in LdapKeyStore (Elytron)

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
This PR contains the Elytron side of automatic outflow.
First the SecurityIdentity has a withSecurityIdentity method added allowing for additional SecurityIdentities to be associated that will also be used for any run calls.
Secondly the anonymousIdentity initialisation is now lazy to allow for any securityIdentityTransformer to be initialised between domain creation and first use.
As outflowing the identity is two lines of code, one of which requiring to be backed by a PrivilegedAction the code handling the flow will live within the subsystem.
=> [ELY-835] Automatic Outflow Preparaton

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOn.java, src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSession.java, src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java, src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java, src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSessionContext.java
[NOTE] It also fixes tests a test failure when we have a cluster and logout fail for one or more nodes. E.g.: when one node is down or failed to process the logout request.
=> [ELY-910] - Remove participant from SSO when remote logout failed

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-739
=> [ELY-739] Coverity static analysis: Dereference null return value in AbstractDigestMechanism (Elytron)

src/main/java/org/wildfly/security/auth/server/IdentityCredentials.java
Fix for https://github.com/wildfly-security/elytron-subsystem/pull/390#issuecomment-279170070
> [8:30 PM] Honza Kalina: about IdentityCredentials.One.getCredential(), should not it create new copy of credential? Currently when I obtain credential from AuthenticationContext and destroy it after, on next obtaining I obtains destroyed credential...
> [9:49 PM] David M. Lloyd: I don't have a certain opinion.  If we create a copy, it becomes impossible to destroy the original.  On the other hand, we really don't want SIs to be mutable
> [9:49 PM] David M. Lloyd: I guess overall copying is better
> [10:02 PM] Darran Lofthouse: Sounds reasonable for the AC to copy, the caller to the AC has no idea where it came from and if accessed through a CBH there is no client side callback to say it is …
=> [ELY-862] IdentityCredentials immutable (return clones)

pom.xml, src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/audit/AuditEndpoint.java, src/main/java/org/wildfly/security/audit/AuditLogger.java, src/main/java/org/wildfly/security/audit/EventPriority.java, src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java, src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java, src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java, src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java, src/main/java/org/wildfly/security/audit/package-info.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/auth/server/event/SecurityAuthenticationEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityAuthenticationFailedEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityAuthenticationSuccessfulEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityDefiniteOutcomeEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java, src/main/java/org/wildfly/security/auth/server/event/SecurityPermissionCheckEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityPermissionCheckFailedEvent.java, src/main/java/org/wildfly/security/auth/server/event/SecurityPermissionCheckSuccessfulEvent.java, src/test/java/org/wildfly/security/audit/JsonSecurityEventFormatterTest.java, src/test/java/org/wildfly/security/audit/SimpleSecurityEventFormatterTest.java
This pull request adds a small set of security events to the security domain.
It adds formatters to convert those events to Strings.
Two audit log endpoints so we can log to file or sent to syslog.
A general AuditLogger to combine the various components.
Once we have an initial solution in place we will need to follow up with: -
1. Completing the set of audit events to be emitted from the domain.
2. Implement the rules and Function that can take an event and map it to a priority (including OFF)
3. Enhance the file audit log for rotation on start up, rotation by time, and rotation by size.
4. Implement our on Syslog client.
5. Performance improvements e.g. non-blocking mode, ThreadLocal managed DateFormat.
6. Allow containers and applications to pass SecurityEvents through the …
=> [ELY-37] Security Events / Listeners / Audit Logging

src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-954
=> [ELY-954] Coverity static analysis, Dereference null return value, OAuth2CredentialSource (Elytron)

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java, src/test/java/org/wildfly/security/ldap/RoleMappingSuiteChild.java, src/test/resources/ldap/elytron-role-mapping-tests.ldif
https://issues.jboss.org/browse/ELY-903
* depth first role recursive search (using recursion) replaced by breadth first search (using queue and cycle) to ensure correct max recursion depth
* fixed/test covered references (memberOf) with role recursion
=> [ELY-903] LdapRealm - role recursion max depth + reference recursion

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
LDAP specification [1]: "Clients that follow referrals MUST ensure that they do not loop between servers. They MUST NOT repeatedly contact the same server for the same request with the same parameters.".
No subsystem dependency.
Related subsystem test extending: https://github.com/wildfly-security/elytron-subsystem/pull/401
https://issues.jboss.org/browse/ELY-909
=> [ELY-909] LdapRealm referral loops handling

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-858
=> [ELY-858] Missing search-base-dn in identity-mapping of Elytron ldap-realm causes NPE 

src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
https://issues.jboss.org/browse/ELY-965
=> [ELY-965] no need to close LdapIdentity

src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/auth/server/event/SecurityAuthenticationFailedEvent.java
https://issues.jboss.org/browse/ELY-972
* emiting AuthenticationFailedEvent on unvalid credential/principal
* information about principal written by user into AuthenticationFailedEvent (because SecurityIdentity is anonymous in that phase)
* refac: consolidation of `if( ! stateRef.compareAndSet` vs `if(stateRef.compareAndSet` between individual parts of SAC - to be comparable better
=> [ELY-972] audit logging on unvalid credential

src/main/java/org/wildfly/security/auth/realm/CachingModifiableSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java, src/test/java/org/wildfly/security/ldap/LdapSecurityRealmIdentityCacheSuiteChild.java
Caching identity attributes and credentials (acquiring, evidence verification kept without cache).
https://issues.jboss.org/browse/ELY-923 (reported as ldap related issue)
https://issues.jboss.org/browse/ELY-915 (the same issue for filesystem realm)
=> [ELY-923] Caching realm - added caching credentials and attributes

src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-955
=> [ELY-955] Coverity static analysis: Dereference null return value in ServerAuthenticationContext (Elytron)

src/main/java/org/wildfly/security/key/KeyUtil.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-958
=> [ELY-958] Coverity static analysis: Dereference null return value in KeyUtil (Elytron)

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
https://issues.jboss.org/browse/ELY-689
https://issues.jboss.org/browse/JBEAP-6630
=> [ELY-689] Remove entry from cache of KeyStoreCredentialStore after successful removal of other entries

src/main/java/org/wildfly/security/key/RawKey.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-961
=> [ELY-961] Coverity: Incorrect definition of RawKey as a parent of Serializable classes

src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java
Jira: https://issues.jboss.org/browse/ELY-989
Tests `replaceRuleConfiguration()` and `replaceRuleSsl()` are ignored due to https://issues.jboss.org/browse/ELY-988
Tests `addRuleCtxConfigurationAtTheStart()`, `addRuleCtxConfigurationInTheMiddle()`, `addRuleCtxSslAtTheStart()`, `addRuleCtxSslInTheMiddle()` are currently ignored and not implemented due to https://issues.jboss.org/browse/ELY-987 - I want to avoid creating tests which actually consider a wrong behavior as correct. I will implement these tests later, when ELY-987 will be resolved.
Method `assertExpectedRuleNode` also includes commented assert for Rules - due to issue https://issues.jboss.org/browse/ELY-986 - it should be uncommented when ELY-986 will be fixed.
=> [ELY-989] Added AuthenticationContextTest

src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/HttpServerRequestWrapper.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/util/PrivilegedServerMechanism.java, src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
I have stuck with getPeerCertificates over requirePeerCertificates as it still remains optional for them to be returned.
I haven't remove access to the SSLSession yet as it is used but if we can port the caching portion over to the HttpScope for SSL_SESSION we may not need to provide access at all.
=> [ELY-621] Client-Cert SSL Session Re-negotiation Support

src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1009
JBEAP: https://issues.jboss.org/browse/JBEAP-9481
=> [ELY-1009] Default settings of SSL session caching for Elytron *-ssl-context are not safe

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/util/PasswordBasedEncryptionUtil.java, src/test/java/org/wildfly/security/util/PasswordBasedEncryptionUtilTest.java
https://issues.jboss.org/browse/ELY-1013
https://issues.jboss.org/browse/JBEAP-9254
PicketBox is encoding bytes to base64 non standard way which cannot be fix simply by PB alphabet.
Therefore I created new compatibility mode to produce the same result.
=> [ELY-1013] PicketBox compatibility mode for PBE utility

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java, src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
* ServerAuthenticationContext should repect RealmCallback and provide adequacy credential (FastUnsupportedCallbackException when no credential for required realm)
* Digest mechanism should not use HOST as default realm, as it can be misused by attacker to reuse URP from different realm
Replaces https://github.com/wildfly-security/wildfly-elytron/pull/732
Tested successfuly in rev **f6a0358** with wildfly-core and wildfly.
=> [ELY-1014] Digest credential realm from mechanism, no HOST realm default

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/http/HttpAuthenticationException.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java
Generally failed mechanisms lead to an internal server error unless we still have mechanisms available that could succeed, additionally having no mechanisms available when authentication if required is an internal server error.
=> [ELY-1034] Additional error handling for HTTP authentication.

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1060
JBEAP: https://issues.jboss.org/browse/JBEAP-8793
=> [ELY-1060] [JBEAP-8793] Coverity static analysis, dereference after null check, KeyStoreCredentialStore (Elytron)

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java, src/main/java/org/wildfly/security/sasl/util/SetMechanismInformationSaslServerFactory.java
* Added warning on missing MechanismConfiguration for given MechanismInformation
* (trace in ServerAuthenticationContext not necessary already - visible in warn cause)
no subsystem part
wildfly-core, wildfly ladybird tests green
=> [ELY-1014] Warn on missing MechanismConfiguration

src/main/java/org/wildfly/security/auth/client/AuthenticationContext.java
https://issues.jboss.org/browse/ELY-987
https://issues.jboss.org/browse/JBEAP-9281
Removed methods as discussed in JBEAP
No depending PRs
=> [ELY-987] removed with(idx, ac) from AuthenticationContext

src/main/java/org/wildfly/security/auth/client/MatchPortRule.java, src/main/java/org/wildfly/security/auth/client/MatchRule.java, src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java
Issue: https://issues.jboss.org/browse/ELY-986
=> [ELY-986] Method equals for MatchRule throws java.lang.IllegalStateException

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-1_0.xsd, src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java, src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config.xml
https://issues.jboss.org/browse/ELY-1083
https://issues.jboss.org/browse/JBEAP-10381
* added possibility to configure used truststore in Elytron client XML
* modified tests of SSL to use Elytron client XML
=> [ELY-1083][JBEAP-10381] trust-store configuration for Elytron client

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1050
JBEAP: https://issues.jboss.org/browse/JBEAP-10077
=> [ELY-1050] Coverity, derefere null return value in KeyStoreCredentialStore.saveSecretKey

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
https://issues.jboss.org/browse/ELY-1095
Related to https://issues.jboss.org/browse/JBEAP-9547
Related to https://github.com/wildfly-security-incubator/wildfly-core/pull/140 but can be merged independently.
Fix to prevent RuntimeException on boot with ldap-realm.
=> [ELY-1095] RealmUnavailableException on iterating when ldap unavailable

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1051
JBEAP: https://issues.jboss.org/browse/JBEAP-10078
=> [ELY-1051] Coverity, derefere null return value in KeyStoreCredentialStore.store

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
issue: https://issues.jboss.org/browse/JBEAP-10476
Different message for case that keyAlias does not exists and case that if exists but is of different type than SecretKey.
=> [JBEAP-10476] [ELY-1097] Different message if keyAlias does not exist.

src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java
Issue: https://issues.jboss.org/browse/ELY-632
This is an amendment to https://github.com/wildfly-security/wildfly-elytron/pull/504
=> [ELY-632] No log messages comming from Elytron - authentication process start

src/main/java/org/wildfly/security/auth/callback/SSLCallback.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, src/main/java/org/wildfly/security/sasl/util/SSLQueryCallbackHandler.java, src/main/java/org/wildfly/security/sasl/util/SSLSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/SSLSaslServerFactory.java
We will probably still need a follow up step to make use of any identity cached on the SSLSession but for now this covers the main approach to get the SSL session into the ServerAuthenticationContext and used  to obtain the certificates to verify as evidence.
=> [ELY-1136] / [ELY-1137] Support for External authentication based on SSL Peer identity.

src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java, src/main/java/org/wildfly/security/audit/RotatingFileAuditEndpoint.java
Although currentSize was declared as volatile, this field modifier is not enough to prevent race conditions. This patch uses an AtomicLong instead.
Jira issues:
https://issues.jboss.org/browse/ELY-1096
https://issues.jboss.org/browse/JBEAP-10473
=> [ELY-1096][JBEAP-10473]: Avoid possible race conditions incrementing the size of Rotating File Audit

src/main/java/org/wildfly/security/credential/store/impl/VaultCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1147
JBEAP: https://issues.jboss.org/browse/JBEAP-10813
=> [ELY-1147] Coverity: Elytron defect: Unguarded read in VaultCredentialStore class

src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/util/CodePointIterator.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
https://issues.jboss.org/browse/ELY-945
* added Base32 encoding of identity names into FileSystemRealm, enabled by default
* improved FileSystemRealm tests (special characters, added disposing)
no core dependency
=> [ELY-945] FileSystemRealm - Base32 names encoding

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Configuration from the XML overrides all default properties.
=> [ELY-1163] Allow mechanism properties to be overriden.

src/main/java/org/wildfly/security/mechanism/scram/ScramClient.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java, src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java, src/main/java/org/wildfly/security/sasl/localuser/LocalUserServer.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java
https://issues.jboss.org/browse/ELY-1151
Null authorizationId handling in SaslClients.
=> [ELY-1151] empty authorization name handling

src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Fix of **RegexValidatingPrincipalTransformerTestCase** failures:
```
Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.088 sec <<< FAILURE! - in org.wildfly.test.integration.elytron.principaltransformers.RegexValidatingPrincipalTransformerTestCase
testMatchTrueAndUsernameDoesNotMatch(org.wildfly.test.integration.elytron.principaltransformers.RegexValidatingPrincipalTransformerTestCase)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected status code returned after the authentication. expected:<401> but was:<500>
```
=> [ELY-1115] ServerAuthenticationContext - InvalidNameState hotfix

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/credential/store/CredentialStoreSpi.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, src/main/java/org/wildfly/security/credential/store/impl/VaultCredentialStore.java
JBEAP: https://issues.jboss.org/browse/JBEAP-10835
ELY: https://issues.jboss.org/browse/ELY-1149
validate given attribute in credential store implementation if it needs to be. 
Default provided implementations KeyStoreCredentialStore and VaultCredentialStore
=> [JBEAP-10835] [ELY-1149] validate given attributes in credential store implementation.

src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
https://issues.jboss.org/browse/ELY-1181
https://issues.jboss.org/browse/JBEAP-9309
=> [ELY-1181] For IBM use a credsType of 'both' instead of 'initiator' to be compatible with using a KeyTab.

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/test/java/org/wildfly/security/auth/client/AuthenticationConfigurationTest.java, src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java, src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java, src/test/java/org/wildfly/security/sasl/digest/DigestCallbackHandlerUtils.java, src/test/java/org/wildfly/security/sasl/entity/EntityTest.java, src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java, src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientTest.java, src/test/java/org/wildfly/security/sasl/otp/OTPTest.java, src/test/java/org/wildfly/security/sasl/plain/PlainTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramCallbackHandlerUtils.java, src/test/java/org/wildfly/security/sasl/test/AnonymousTest.java, src/test/java/org/wildfly/security/sasl/test/LocalUserTest.java
Added method empty() for AuthenticationConfiguration to make things consistent.
=> [Ely 584] used methods, AuthenticationConfiguration.EMPTY is flaged as deprecated

src/main/java/org/wildfly/security/sasl/SaslMechanismSelector.java
https://issues.jboss.org/browse/ELY-1184
https://issues.jboss.org/browse/JBEAP-11067
offset of end bracket ')' is wrongly returned after it's been identified as non name char.
=> [JBEAP-11067][ELY-1184] return correct offset when current char is not name char.

src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
This pull request is a follow up to Stuart's PR: -
https://github.com/wildfly-security/wildfly-elytron/pull/832
If we don't have an SSLSession available to us skip caching entirely.
=> [ELY-1191] CLIENT_CERT Authentication may not have access to SSLSession

src/main/java/org/wildfly/security/http/HttpServerRequest.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
This will also fix CLIENT_CERT in the case where SSL is being terminated at the reverse proxy and the certificate information is being provided by headers.
=> ELY-1191 Undertow CLIENT_CERT via Elytron and HTTP/2 does not work

src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Clearing after hotfix: https://github.com/wildfly-security/wildfly-elytron/pull/821
Using InvalidNameState also when identity does not exist in realm. (Not only when not found in realm.)
Not critical.
=> [ELY-1115] SAC: InvalidNameState for non-existing identities

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Patch to allow creating empty credential stores independently of its modifiable attribute.
https://issues.jboss.org/browse/ELY-1199
https://issues.jboss.org/browse/JBEAP-9211
depends on: https://github.com/wildfly/wildfly-core/pull/2469
=> ELY-1199:Allow creation of empty credential stores

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1195
JBEAP: https://issues.jboss.org/browse/JBEAP-11113
=> [ELY-1195] Coverity, Dereference after null check in KeyStoreCredentialStore (Elytron)

src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServer.java, src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslTest.java
https://issues.jboss.org/browse/ELY-1194
https://issues.jboss.org/browse/JBEAP-11110
By RFC server should fail after receiving client dummy response:
https://tools.ietf.org/html/rfc7628#section-3
(in previous version server didnt sent anything and didnt close connection - connection got trapped in waiting)
=> [ELY-1194][JBEAP-11110] OAuth2SaslServer fail after client dummy response

src/main/java/org/wildfly/security/auth/realm/token/TokenSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/RealmIdentity.java, src/main/java/org/wildfly/security/auth/server/SecurityRealm.java, src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
This PR now avoids using the exists() method entirely during authentication.
Where we do need to find out if a RealmIdentity is usable for authentication we have the getCredentialAcquireSupport and getEvidenceVerifySupport exactly for this purpose.
=> [ELY-1121] Clarify contract of RealmIdentity.exists() and avoid using it in general for authentication.

src/main/java/org/wildfly/security/sasl/SaslMechanismPredicate.java
https://issues.jboss.org/browse/ELY-1218
https://issues.jboss.org/browse/JBEAP-11288
=> [ELY-1218] The mutual SASL mechanism predicate should not require TLS to be used

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/sasl/SaslMechanismSelector.java, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java, src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java, src/test/java/org/wildfly/security/sasl/digest/DigestCallbackHandlerUtils.java, src/test/java/org/wildfly/security/sasl/entity/EntityTest.java, src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java, src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientTest.java, src/test/java/org/wildfly/security/sasl/otp/OTPTest.java, src/test/java/org/wildfly/security/sasl/plain/PlainTest.java, src/test/java/org/wildfly/security/sasl/scram/ScramCallbackHandlerUtils.java, src/test/java/org/wildfly/security/sasl/test/LocalUserTest.java
Removed allowAllSaslMechanisms, allowSaslMechanisms, forbidSaslMechanisms methods of AuthenticationConfiguration as requested in JBEAP-11209.
To simplify their replacing added addMechanisms and forbidMechanisms for adding/forbidding more mechanisms in one call.
https://issues.jboss.org/browse/ELY-1209
https://issues.jboss.org/browse/JBEAP-11209
Need to be merged in coordination with https://github.com/wildfly/wildfly-core/pull/2510
=> [ELY-1209] allow-all-mechanisms, allow/forbid-sasl-mechanisms removing

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-1_0.xsd
As hashed password is unusable for client side, removing hashed-password and crypt-password as suggested in issue.
https://issues.jboss.org/browse/JBEAP-11640
https://issues.jboss.org/browse/ELY-1252
=> [ELY-1252][JBEAP-11640] removed hashed-password and crypt-password from XML

src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java, src/main/java/org/wildfly/security/sasl/digest/DigestServerFactory.java
The RealmCallback is created but not used on the server if ```defaultRealm``` is ```true``` (it is always ```false``` on the client).  While this is not strictly the most efficient solution, it was the best combination of a minimal and safe change that I could come up with.
=> [ELY-1186] Do not establish a realm on the server if only the default realm was offered to the client

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java, src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslServerFactory.java
It was necessary to enable a new property on AuthenticationConfiguration to manage the `remote.connection.node1.connect.options.org.xnio.Options.SASL_PROTOCOL` property. This value now is used to configure the ProtocolSaslClientFactory. 
Jira issues:
https://issues.jboss.org/browse/JBEAP-10996
https://issues.jboss.org/browse/ELY-1250
It depends on https://github.com/jboss-remoting/jboss-remoting/pull/124
=> ELY-1250: Add SASL protocol configuration in AuthenticationConfiguration and use it for SaslClient configuration

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/pem/Pem.java, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
* added private-key parsing
* fixed pem element parsing (`hasText()` does not make sense before `getElementText()` call)
* dead code clearing (dont check end of document in end of authentication-client, as it is not root element already)
https://issues.jboss.org/browse/ELY-1255
https://issues.jboss.org/browse/JBEAP-11695
=> [ELY-1255] Elytron XML certificate private-key parsing

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
Jira: https://issues.jboss.org/browse/ELY-1161
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-10951
=> [ELY-1161] Wrong Exception message when non-existing alias is used for SSL in Elytron Client configuration file

src/main/java/org/wildfly/security/audit/PeriodicRotatingFileAuditEndpoint.java
Jira issues:
https://issues.jboss.org/browse/ELY-1263
https://issues.jboss.org/browse/JBEAP-11774
=> ELY-1263: Minor refactor to avoid potential nullpointer exception using getParentFile()

src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
Issue: https://issues.jboss.org/browse/ELY-1273
=> [ELY-1273] Internal NPE when any attribute from x509-credential-mapper in ldap-realm is missing in LDAP

src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, src/main/java/org/wildfly/security/password/impl/OneTimePasswordAlgorithmParametersSpiImpl.java, src/main/java/org/wildfly/security/password/impl/OneTimePasswordImpl.java, src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java, src/main/java/org/wildfly/security/password/interfaces/OneTimePassword.java, src/main/java/org/wildfly/security/password/interfaces/RawOneTimePassword.java, src/main/java/org/wildfly/security/password/spec/OneTimePasswordAlgorithmSpec.java, src/main/java/org/wildfly/security/password/spec/OneTimePasswordSpec.java, src/main/java/org/wildfly/security/sasl/otp/OTP.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java, src/main/java/org/wildfly/security/sasl/otp/OTPSaslServer.java, src/main/java/org/wildfly/security/sasl/otp/OTPUtil.java, src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java, src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java, src/test/java/org/wildfly/security/sasl/otp/OTPTest.java, src/test/java/org/wildfly/security/util/AbstractAlgorithmParametersSpiImplTest.java
We need to be able to calculate OTP hash value from WFCORE. There is an existing class doing it `org.wildfly.security.sasl.otp.OTPUtil` but it has default class visibility. Instead of change the visibility of that class, I have added the method to `org.wildfly.security.sasl.otp.OTP`, which is already public, reducing the cohesion between them. I think it is better with this change but .. any feedback would be great.
Jira issues:
https://issues.jboss.org/browse/ELY-1268
https://issues.jboss.org/browse/JBEAP-10532
It depends on https://github.com/wildfly/wildfly-core/pull/2590
=> ELY-1268: Create OTPasswords using an algorithm specification and a pass phrase

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
https://issues.jboss.org/browse/ELY-1271
https://issues.jboss.org/browse/JBEAP-11867
=> [ELY-1271] unusable SecurityDomain for SSLContext handling

src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1278
JBEAP: https://issues.jboss.org/browse/JBEAP-11925
=> [ELY-1278] Coverity static analysis: Dereference null return value in ServerAuthenticationContext (Elytron)

src/main/java/org/wildfly/security/ssl/TLSServerEndPointChannelBinding.java
https://issues.jboss.org/browse/ELY-1286
=> [ELY-1286] Rename the "tls-server-endpoint" channel binding type to "tls-server-end-point" to match the IANA channel binding type registry

pom.xml
https://issues.jboss.org/browse/ELY-534
This decreases the number of test errors from 91 to 21 on IBM JDK.
cc @olukas
=> ELY-534 Some tests fail with ExceptionInInitializerError with JMockit

src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
Comparison between certificate subject and LDAP CNs must be done according to RFC 2253. Instead of using a String, we are using now X500Principal which is RFC 2253 compliant.
Jira issues:
https://issues.jboss.org/browse/ELY-1274
https://issues.jboss.org/browse/JBEAP-11903
=> ELY-1274: Fix comparison between X509Certificate subjects and LDAP CNs

src/main/java/org/wildfly/security/auth/util/ElytronAuthenticator.java
* https://issues.jboss.org/browse/JBEAP-12341
* https://issues.jboss.org/browse/JBEAP-12340
* https://issues.jboss.org/browse/ELY-1311
=> [ELY-1311] - Translate password before obtaining clear password spec

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Backport of https://github.com/wildfly-security/wildfly-elytron/pull/925
https://issues.jboss.org/browse/ELY-1313
https://issues.jboss.org/browse/JBEAP-11821
=> [ELY-1313] KeyStoreCredentialStore encrypt initialization fix for BouncyCastle

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1315
https://issues.jboss.org/browse/JBEAP-12569
=> [ELY-1315] KeyStoreCredentialStore not using writeLock when it should be used

pom.xml
Makes build work on JDK9
fixes issues with running standalone-clients that rely on transitive deps to be present.
=> Update & fix build and its dependancies

src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- syncing FIPS mode KeyStore loads on EmptyProvider as the same issue exists Elytron module and Elytron subsystem and domain management
https://issues.jboss.org/browse/ELY-1322
https://issues.jboss.org/browse/JBEAP-11693
=> [ELY-1322] Found multiple secret keys sharing same CKA_LABEL

src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
This is a continuation from https://issues.jboss.org/browse/JBEAP-12460 where a NPE was detected in the FormAuthenticationMechanism once the scope can be null.
=> [ELY-1329] The returned scope can be 'null' if not supported.

pom.xml
Not directly related to a JBEAP issue as this is just a step we need to take before we can create out own Final tag.
=> [ELY-1333] Upgrade remaining component dependencies to their Final versions.

src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
https://issues.jboss.org/browse/ELY-1330
https://issues.jboss.org/browse/JBEAP-12689
=> [ELY-1330] Ensure the server fails authentication if the client sends the "y" channel binding flag even though the server supports channel binding

src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
This PR is a continuation for https://issues.jboss.org/browse/JBEAP-12460
Where we only used connection scope we didn't need to create the scope as it would always exist, now we need to create the scope if it doesn't exist at the correct time.
=> [ELY-1335] Ensure the scope exists before using it to hold the GSSContext

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
This is a minor continuation of https://issues.jboss.org/browse/JBEAP-12631
It would be good at a later point to switch fully to ByteBuffers and NIO Channels, for now however as we are in the final stages of release I have not gone quite this far as it would impact the file size calculation.
For now however I have reduced the visibility of the methods overridden by child implementations to discourage extension so we can freely change these methods in a future release.
=> [ELY-1338] Reduce visibility of methods to avoid custom extensions outside of the package from being created.

src/main/java/org/wildfly/security/util/ByteIterator.java, src/test/java/org/wildfly/security/util/PemTest.java
XmlConfigurationTest.testCertificateInCredentials hangs on IBM JDK
Fixes both https://issues.jboss.org/browse/ELY-1301 and https://issues.jboss.org/browse/ELY-1292
=> [ELY-1301][ELY-1292] Pem.parsePemX509Certificate() hangs on IBM JDK,

src/main/java/org/wildfly/security/_private/ElytronMessages.java
This just comments out unused logger interface methods. I'm not sure if this should be opened on master or the 1.x branch. It's not required for 1.1.0.Final. It will help cut down on the metaspace size of the logger though.
=> [ELY-1344] Remove unused logging/message bundle methods.

src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java, src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java
This change is to support the important use case of allowing one server to trust another server, but still requiring the source server to authenticate.
=> [ELY-1077] Allow separated authorization and authentication forwarding

src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
Revised and fixed CipherSuiteSelector parsing - especially missing EXPORT40 and EXPORT56.
https://issues.jboss.org/browse/ELY-396
https://issues.jboss.org/browse/JBEAP-2204
=> [ELY-396] CipherSuiteSelector parsing revised

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java, src/test/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealmTest.java
LegacyPropertiesRealm should take advantage from "new" parameter of getCredential - AlgorithmParameterSpec. For plain-text property realms will not be digest realm specification in realm configuration or property file necessary, because password hashes will be generated from spec.
(btw... now looking, maybe we could remove creating digested passwords from clear passwords entirely and keep TwoWay to DigestPassword conversion on mechanism - which is already implemented...)
https://issues.jboss.org/browse/ELY-1348
https://issues.jboss.org/browse/JBEAP-8700
=> [ELY-1348] LegacyPropertiesRealm should use spec passed into getCredential

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
Currently waiting for appropriate ACKs on the Jira issue but this is ready for review so we can merge as soon as the paperwork is in place.
https://issues.jboss.org/browse/JBEAP-13113
=> [ELY-1362] Thread.getContextClassLoader() can return null.

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-client-1_1.xsd
At this stage we have just incremented the minor version of the project I have just incremented the minor version within the namespace, this does include a small change to the namespace as well so the filesystem realm can remain on the original schema and evolve independently.
The authentication client parser is updated to accept both version, and also to ensure the namespace remains consistent during parsing to avoid attempts at mixing schemas within a single config.
As new attributes and elements are added we will need to decide if we are lenient and accept them added against the older namespace or strictly enforce the correct namespace.
=> [ELY-1354] Add a new minor version of the schema to allow for the next stage of updates.

src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java, src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
This is just an initial fix focused on checking for null to avoid the NPE.
I have also changed the order we check if we have a username or digest as TBH no username would always have failed and even now will always result in no digest so we have the more specific error first.
https://issues.jboss.org/browse/ELY-1371
This contributes to https://issues.jboss.org/browse/JBEAP-13214 but does not resolve it.
=> [ELY-1371] Verify a username is available before continuing to generate the digest.

pom.xml, src/test/java/org/wildfly/security/ExcludedOnIbmJdk.java, src/test/java/org/wildfly/security/sasl/gssapi/GssapiCompatibilitySuiteChild.java
https://issues.jboss.org/browse/ELY-1298
This excludes `GssapiCompatibilitySuiteChild` on IBM JDK, because I see no better way how to solve this. See https://issues.jboss.org/browse/ELY-1298?focusedCommentId=13454485&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13454485 for details.
=> [ELY-1298] GssapiCompatibilitySuiteChild fails on IBM JDK

src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
('{' is interpretted as capacity, instead of initial string value)
https://issues.jboss.org/browse/ELY-1367
=> [ELY-1367] SimpleSecurityEventFormatter - fix of '{' at begin

src/main/java/org/wildfly/security/x500/X500PrincipalUtil.java
This looks to be the only change required to get building on Java 9 again.
https://issues.jboss.org/browse/ELY-1372
Whilst we would like X500Name to be available to us I don't believe it is out position to make that a requirement.
=> [ELY-1372] Don't throw any error during initialisation as it makes the utility class completely unavailable.

src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslClient.java, src/main/java/org/wildfly/security/sasl/external/ExternalSaslClient.java, src/main/java/org/wildfly/security/sasl/external/ExternalSaslServer.java, src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java, src/main/java/org/wildfly/security/sasl/plain/PlainSaslServer.java, src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java, src/main/java/org/wildfly/security/sasl/util/LocalPrincipalSaslClientFactory.java, src/main/java/org/wildfly/security/sasl/util/SecurityIdentitySaslServerFactory.java
SaslServer/SaslClient.getNegotiatedProperty should by contract throw illegal state exception when calling before negotiation is complete.
https://issues.jboss.org/browse/ELY-1380
https://issues.jboss.org/browse/JBEAP-13265
=> [ELY-1380] getNegotiatedProperty exception when not complete

src/main/java/org/wildfly/security/sasl/digest/DigestClientFactory.java, src/main/java/org/wildfly/security/sasl/digest/DigestServerFactory.java
If com.sun.security.sasl.digest.utf8 is used, a class cast exception is thrown. This patch fixes this problem.
Issue: https://issues.jboss.org/browse/ELY-1404
JBEAP issue: https://issues.jboss.org/browse/JBEAP-13356
=> [ELY-1404] Fixed ClassCastException getting SASL property com.sun.security.sasl.digest.utf8

src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
Fixed problem noticed by @mchoma in https://github.com/wildfly-security/wildfly-elytron/pull/1013#discussion_r147129398
Time of last fail, which is long, should be volatile.
=> [ELY-1406] GSSCredential lastFailTime volatile

src/main/java/org/wildfly/security/mechanism/MechanismUtil.java
Returning method removed from public API (as deprecated).
https://issues.jboss.org/browse/ELY-1452
(Successfully verified using SigTest - API compatible with 1.1.7.Final now.)
=> [ELY-1452] API breaking fix: MechanismUtil.handleCallbacks

src/main/java/org/wildfly/security/auth/realm/SimpleMapBackedSecurityRealm.java, src/test/java/org/wildfly/security/auth/realm/cache/SecurityRealmIdentityCacheTest.java, src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java, src/test/java/org/wildfly/security/authz/jacc/ElytronPolicyEnforcementTest.java, src/test/java/org/wildfly/security/authz/jacc/LinkPolicyConfigurationTest.java, src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
https://issues.jboss.org/browse/ELY-728
- setPasswordMap(Map) renamed to setIdentityMap(Map) (original deprecated)
- as setPasswordMap(...) for single identity maps was used only in tests, I has deprecated them completely to minimize public api
=> [ELY-728] SimpleMapBackedSecurityRealm.setPasswordMap to setIdentityMap

src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java, src/main/java/org/wildfly/security/auth/realm/jdbc/KeyMapper.java, src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
Prior to this change a single username / password authentication attempt could result in the same JDBC query being executed three times by the database if that same query is configured to load credentials and attributes - this change reduces that down to 1.
1. All Credentials are loaded into an IdentityCredential which is subsequently used for all acquisition and validation.
2. The identity loading loop is now optimised to re-use the ResultSet instead of creating it once for attribute loading and then again for credential loading.
This does have a side effect that a single query can now load multiple credentials but that does make sense as one of the columns read specifies the algorithm.
=> [ELY-1456] Minimise hits to database from JDBC realm during authentication.

src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java, src/test/java/org/wildfly/security/http/DigestAuthenticationMechanismTest.java, src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java, src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
* correct digest response calculation for specified qop=auth
* added custom hashing algorithm support  (more algorithms in one mechanism instance not supported)
* covered by compatibility test against RFC examples
* NonceManager made public to allow mocking (stays in private part of elytron module - impl package)
https://issues.jboss.org/browse/ELY-1369
https://issues.jboss.org/browse/JBEAP-10920
=> [ELY-1369] non-MD5 algorithms into HTTP Digest + qop=auth support

src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1475
JBEAP: https://issues.jboss.org/browse/JBEAP-14031
=> [ELY-1475] Empty username for FormAuthenticationMechanism causes IllegalArgumentException

src/main/java/org/wildfly/security/http/HttpAuthenticator.java, src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
Also includes ELY-1463 to ensure we create a session if we are persisting an identity, and ELY-1489 to simplify this within the FormAuthenticationMechanism.
The Elytron Web side of the change can be found here: - https://github.com/wildfly-security/elytron-web/pull/118
The following branch also contains an updated test in the WildFly testsuite to reproduce this error / verify the fix https://github.com/wildfly/wildfly/compare/master...darranl:WFLY-9561
=> [ELY-1462] Moving programatic authentication to Elytron

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1460
JBEAP: https://issues.jboss.org/browse/JBEAP-13441
=> [ELY-1460] External CS, PKCS11 can't be configured with externalPath

src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java, src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java, src/main/java/org/wildfly/security/sasl/WildFlySasl.java, src/main/java/org/wildfly/security/sasl/gssapi/AbstractGssapiMechanism.java, src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java, src/main/java/org/wildfly/security/sasl/gssapi/GssapiServer.java
Added workaround to make native Kerberos working with GSSAPI and SPNEGO mechanisms.
(GS2 mechanism is blocked by another not-workaroundable JDK issue too, so kept without this.)
Also allowed null keyTab in GSSCredentialFactory (when checkKeyTab = false) - set keyTab is ignored when native Kerberos is used.
https://issues.jboss.org/browse/ELY-85
=> [ELY-85] GSSAPI+SPNEGO workaround for JDK-8194073 (native Kerberos)

src/main/java/org/wildfly/security/WildFlyElytronProvider.java, src/main/java/org/wildfly/security/digest/SHA512_256MessageDigest.java, src/main/java/org/wildfly/security/sasl/util/AbstractDelegatingSaslServerFactory.java
This drastically reduces the class loading overhead just to initialise the Provider.
=> [ELY-1471] Rework the WildFlyElytronProvider to be a static definition instead of a dynamically generated definition.

pom.xml
This contains Martin's PR but I have added a commit to split the packages into their own line so we can see future modifications more easily.
Using japicmp tool [1] profile was created to compare two jars of library:
last 1.1.x released jar (currently 1.1.7.Final)
currently SNAPSHOT version (e.g. 1.2.0.Beta12-SNAPSHOT)
Tool comes with lots of options to specify what to check [2]
In this initial version breakBuildBasedOnSemanticVersioning is turned
on. And set of public packages is specified.
This is alternative to #1066
Usage:
mvn verify -DskipTests -PcompatibilityCheck
[1] https://github.com/siom79/japicmp
[2] https://siom79.github.io/japicmp/MavenPlugin.html
=> [ELY-1398] Add support for public API compatibility check using japicmp

src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Also [ELY-1518] Elimination of a stream and lambdas where a for loop can be used.
https://issues.jboss.org/browse/ELY-1503
https://issues.jboss.org/browse/ELY-1518
=> [ELY-1503] Ensure the reference to the GssContext and KerberosTicket can be dropped during Serialization.

src/main/java/org/wildfly/security/_private/ElytronMessages.java, src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
JBEAP (7.1.z): https://issues.jboss.org/browse/JBEAP-13656
Upstream issue: https://issues.jboss.org/browse/ELY-1430
Upstream PR: wildfly-security/wildfly-elytron#1028
=> [ELY-1430] WARN logged during server shutdown when Elytron JACC is set

pom.xml
1.2.x backport of https://github.com/wildfly-security/wildfly-elytron/pull/1105
https://issues.jboss.org/browse/ELY-1523
=> [ELY-1523] JAPICMP checking level independent on version number

pom.xml
(7.1.x) JBEAP: https://issues.jboss.org/browse/JBEAP-14394
Upstream: https://issues.jboss.org/browse/ELY-1533 (PR: https://github.com/wildfly-security/wildfly-elytron/pull/1103)
=> [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron

src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
(7.1.x) https://issues.jboss.org/browse/JBEAP-14395
Upstream: https://issues.jboss.org/browse/ELY-1490
=> [ELY-1490] Use supported hash algorithm in DER encoder test DSA section

src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
The "algorithm" property is required for passwords.
wildfly-elytron: https://issues.jboss.org/browse/ELY-1480
=> [ELY-1480] Coverity, Explicit null dereferenced in FileSystemSecurityRealm

src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1564
=> [ELY-1564] In PasswordKeyMapper an exception is logged with a wrong algorithm name.

pom.xml
Builds and compare on JDK 9, Oracle JDK8 and IBM JDK8 successfully.
https://issues.jboss.org/browse/ELY-1540
=> [ELY-1540] added japicmp dependencies for JDK 9

src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV10Test.java, src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientV11Test.java
https://issues.jboss.org/browse/ELY-1529
=> [ELY-1529] one MockWebServer init per OAuth test for less often binding fails

pom.xml, src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-1_0.xsd, src/main/resources/schema/elytron-1_0_1.xsd, src/main/resources/schema/elytron-client-1_1.xsd, src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java, src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java, src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_1.xml, src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml, src/test/resources/schema/wrapped-elytron-1_0.xsd, src/test/resources/schema/wrapped-elytron-client-1_1.xsd
https://issues.jboss.org/browse/ELY-1589
https://issues.jboss.org/browse/ELY-1568
Parsing of certificate-revocation-list was broken - parsing element as attribute.
I confirm there is no chance to use "resource" or "uri" attributes without parsing error in current version - fixing should be safe.
Opened for 1.3.x as discussed in https://github.com/wildfly-security/wildfly-elytron/pull/1141
=> [ELY-1589][ELY-1568] fixed CRL from resource/uri, XSD fix of provider

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, src/main/resources/schema/elytron-client-1_1.xsd
https://issues.jboss.org/browse/ELY-1588
* handled missing alias in parsing (with info about xml line)
* handled missing store/clear-text already on parsing
* doc into xsd
=> [ELY-1588] credential-store-reference: handled missing alias, xsd doc

src/main/java/org/wildfly/security/pem/Pem.java
As discussed with Martin and Darran, this PR temporarily adds a ```Pem.generatePemX509Certificate()``` method that takes the ```ByteStringBuilder``` from Elytron as a parameter instead of the one from Common. This will prevent the need for [modifying](https://github.com/wildfly/wildfly-core/pull/3316#issuecomment-392540683) ```org.wildfly.extension.elytron.AdvancedModifiableKeyStoreDecorator``` when building Core with the latest Elytron SNAPSHOT version. Since ```org.wildfly.security.pem.Pem``` is private API, we can remove this new method later on to remove the duplication.
https://issues.jboss.org/browse/ELY-1602
=> [ELY-1602] Temporarily add a Pem.generatePemX509Certificate() method that takes the ByteStringBuilder from Elytron as a parameter

src/main/java/org/wildfly/security/http/HttpConstants.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
Added possibility to skip X509Evidence verification against realm - the mechanism check only the presence of the evidence (which also mean validity against SSL truststore) in such case.
https://issues.jboss.org/browse/ELY-1418
https://issues.jboss.org/browse/JBEAP-12417
Usage described in blogspot: https://hkalina.github.io/2017/10/18/client-cert/
=> [ELY-1418] CLIENT_CERT without certificates in security realm

src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
https://issues.jboss.org/browse/ELY-1493
Re-checked and locking seems correct in this test.
Any reason for timeout I see is that testing machine is just really slow :/
Extending timeouts a bit yet.
(timeouts occur only on failure - usual test run will not be prolonged)
=> [ELY-1493] KeyStore test - extended too short timeouts more

src/main/java/org/wildfly/security/password/spec/ClearPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/DigestPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/EncryptablePasswordSpec.java, src/main/java/org/wildfly/security/password/spec/HashPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/IteratedHashPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/IteratedSaltedHashPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/MaskedPasswordSpec.java, src/main/java/org/wildfly/security/password/spec/OneTimePasswordSpec.java, src/main/java/org/wildfly/security/password/spec/SaltedHashPasswordSpec.java
https://issues.jboss.org/browse/ELY-1573
=> [ELY-1573] equals/hashCode methods for PasswordSpec classes

src/main/java/org/wildfly/security/cache/CachedIdentity.java, src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java, src/main/java/org/wildfly/security/mechanism/_private/MechanismUtil.java
https://issues.jboss.org/browse/ELY-1287
=> [ELY-1287] Scope.SSL_SESSION into CLIENT_CERT instead of SSLSession

src/main/java/org/wildfly/security/auth/client/AuthenticationContextConfigurationClient.java, src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java, src/main/java/org/wildfly/security/auth/server/SecurityDomain.java, src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java, src/main/java/org/wildfly/security/manager/StackInspector.java, src/test/java/org/wildfly/security/sasl/test/StringPrepTest.java, src/test/java/org/wildfly/security/util/Base32Test.java, src/test/java/org/wildfly/security/util/Base64Test.java
https://issues.jboss.org/browse/ELY-1596
* improved javadoc to inform about required permissions
* few minor code improvements (to remove built warnings)
=> [ELY-1596] javadoc: required permissions for enabled security manager

src/main/java/org/wildfly/security/ssl/Protocol.java
https://issues.jboss.org/browse/ELY-1618
=> [ELY-1618] Make Protocol.forName() case insensitive to allow TLS to work properly when using the Bouncy Castle JSSE provider

src/main/java/org/wildfly/security/ssl/Protocol.java
https://issues.jboss.org/browse/ELY-1618
=> [ELY-1618] Avoid NPE in Protocol.forName() when the protocol name is null

src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.jboss.org/browse/ELY-1622
=> [ELY-1622] Ensure ConfigurationKeyManager.Builder gets used even when no key-store-ssl-certificate is specified

src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
JBEAP(7.1.x): https://issues.jboss.org/browse/JBEAP-15265
Upstream: https://issues.jboss.org/browse/ELY-1510
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1094
=> [ELY-1510] Bearer authentication sends 401 to unportected resources when no auth in progress

src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java, src/test/java/org/wildfly/security/ssl/CipherSuiteSelectorTest.java
https://issues.jboss.org/browse/ELY-793
=> [ELY-793] Using @STRENGTH keyword in CipherSuiteSelector.fromString should cause descending sorting

pom.xml
https://issues.jboss.org/browse/ELY-1595
Reenabled source compatibility check which was disabled because of japicmp bug.
=> [ELY-1595] Reenabling source compatibility check

src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java, src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
https://issues.jboss.org/browse/ELY-1678
=> [ELY-1678] Avoid NPE in AcmeClientSpi#checkContentType() when the content type is null and try to fix intermittent failures in AcmeClientSpiTest

pom.xml
https://issues.jboss.org/browse/ELY-1671
=> [ELY-1671] Fix to build javadoc on JDK 10 and JDK 11

src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java
https://issues.jboss.org/browse/ELY-1697
=> [ELY-1697] Ensure CompatibilityClientTest removes the credential store file it creates

src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
JBEAP(7.1.x): https://issues.jboss.org/browse/JBEAP-12868
Upstream: https://issues.jboss.org/browse/ELY-1373
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1022
=> [ELY-1373] SPNEGO should not send base challenge on failed authorization

src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java, src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java, src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java
JIRA issues: 
https://issues.jboss.org/browse/EAP7-1154
https://issues.jboss.org/browse/ELY-1466
https://issues.jboss.org/browse/WFLY-11479
Analysis doc: 
https://github.com/wildfly/wildfly-proposals/blob/b970200ba0662d1c98268977c2f77ca3a941c649/security/WFLY-11479_HTTP_Basic_auth_silent_mode.adoc
=> [ELY-1466] Http Basic auth - silent mode

src/main/java/org/wildfly/security/http/HttpAuthenticator.java
https://issues.jboss.org/browse/ELY-1747
=> [ELY-1747] If programmatic authentication is successful associate the credential with the identity.

src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java, src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
JBEAP (7.2.z): https://issues.jboss.org/browse/JBEAP-16150
Upstream: https://issues.jboss.org/browse/ELY-1678
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1199
Upstream: https://issues.jboss.org/browse/ELY-1699
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1214
=> [ELY-1678] Avoid NPE in AcmeClientSpi#checkContentType() and [ELY-1699] Intermittently failing AcmeClientSpiTest

pom.xml, src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
JBEAP (7.2.z): https://issues.jboss.org/browse/JBEAP-16151
Upstream: https://issues.jboss.org/browse/ELY-1702
Upstream PR:  https://github.com/wildfly-security/wildfly-elytron/pull/1214
=> [ELY-1702] Update mockserver-netty to 5.4.1

src/main/java/org/wildfly/security/cache/CachedIdentity.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java
https://issues.jboss.org/browse/JBEAP-16152
This is a continuation of https://github.com/wildfly-security/wildfly-elytron/pull/1224 to also cache the resulting SecurityIdentity.
=> [ELY-1464] Programatic authentication should be caching the SecurityIdentity not the name of the identity

src/main/java/org/wildfly/security/cache/CachedIdentity.java, src/main/java/org/wildfly/security/http/HttpAuthenticator.java
If we are to include more fixes this one may be good to get in.
https://issues.jboss.org/browse/ELY-1464
PR for 1.6.x is also at https://github.com/wildfly-security/wildfly-elytron/pull/1233
=> [ELY-1464] Programatic authentication should be caching the SecurityIdentity not the name of the identity 

src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-1677
=> [ELY-1677] Elytron Bearer Token Authentication - Return a 401 on Invalid Token

pom.xml, tests/base/pom.xml, wildfly-elytron-titan/pom.xml, wildfly-elytron/pom.xml
For successfull javadoc generation it was necessary to specify **sourcepath**, because `manager/base/src/main/java9/` must be before `manager/base/src/main/java/` . Not sure why, but it was true before modularization also: https://github.com/wildfly-security/wildfly-elytron/blob/master/pom.xml#L306. The maven-javadoc-plugin does not support wildcards in **sourcepath**,  so all the paths are listed (I did not find nicer solution in the documentation of javadoc tool or javadoc plugin) .
Usage (it is in the comment of pom.xml also ):
` mvn javadoc:aggregate@api-javadoc` for api-javadoc
` mvn javadoc:aggregate@full-javadoc` for full-javadoc
=> [ELY-1711] Restore JavaDoc Generation

pom.xml
I identified the following new modules: 
* wildfly-security-keystore
* wildfly-security-mechanism-http
* wildfly-security-password-impl
* wildfly-security-tool
* wildfly-security-tests-common
The only new public package is **org.wildfly.security.tool**
I removed wildfly-elytron-tests-common from the config I don't think it needs to be there (as it does not contain any non-test sources).
=> [ELY-1711] Add new modules to japicmp config

sasl/base/src/main/java/org/wildfly/security/sasl/WildFlySasl.java, sasl/base/src/main/java/org/wildfly/security/sasl/util/StringPrep.java, sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java, sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClientFactory.java, tests/base/src/test/java/org/wildfly/security/sasl/plain/PlainTest.java
Add the "org.wildfly.sasl.skip-normalization" property to optionally
skip Unicode normalization.
=> [ELY-1761] Add property to skip normalization

jacc/src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
https://issues.jboss.org/browse/ELY-1810
1.9 variant of https://github.com/wildfly-security/wildfly-elytron/pull/1284
=> [ELY-1810] Only check the permission against the current SecurityIdentity if it is a JACC permission.

src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
JBEAP(7.2.z): https://issues.jboss.org/browse/JBEAP-17004
Upstream issue: https://issues.jboss.org/browse/ELY-1826
This issue has been resolved upstream as part of refactoring in commit [1].
[1] https://github.com/wildfly-security/wildfly-elytron/commit/2cfa1c61346fbd6ad780ba5085c229e875652867#diff-9ad62980379a45e80f38d71d338c2878
=> [ELY-1826] Cannot connect to management interface with Java Security Manager enabled

credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1876
=> [ELY-1876] Log messages are not logged when KeyStoreCredentialStore is initialized with Provider[] in getKeyStoreInstance.

tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
https://issues.jboss.org/browse/ELY-1895
In the future we will need to revisit for a more reliable test.  Mocking the SocketFactory allows a switch to TCP however TCP error handling is different making it incompatible with the test.
=> [ELY-1895] Ignore failure scenario testing as bad UDP host does not trigger the failure in all environments.

LICENSE.txt
https://issues.jboss.org/browse/ELY-1866
=> [ELY-1866] Fixed broken symbolic link to LICENSE.txt

jwt/pom.xml, jwt/src/main/java/org/wildfly/security/mp/jwt/JWTCDIExtension.java, jwt/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension, pom.xml, wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-1884
This is a relatively small addition to WildFly Elytron at this stage, presently it just adds an extension of the CDI Extension to override some behaviour and the descriptor to make it available using ServiceLoader discovery.
Longer term if any closer Elytron integration becomes necessary this project will be the home to keep the subsystem as slim as possible and should alternative implementations to the CDI implementations be required they will also be added here.
This build will presently fail as it requires changes proposed to SmallRye JWT.
=> [ELY-1884] Adding MicroProfile JWT Support

sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java, tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
And ensure it is marked as a CA certificate.
https://issues.redhat.com/browse/ELY-1924
=> [ELY-1924] Correct CA certificate generation for EntityTest so it is only generated once.

sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java, tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
This is to ensure it is only generated once and ensure it is marked as a CA certificate.
https://issues.redhat.com/browse/ELY-1929
=> [ELY-1929] / [ELY-1924] Correct CA certificate generation for EntityTest

http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
https://issues.redhat.com/browse/ELY-1954
=> [ELY-1954] If there is no request path and the application has a context root, redirect to ensure a trailing slash is on the URL.

http/base/src/main/java/org/wildfly/security/http/HttpConstants.java, http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
https://issues.redhat.com/browse/ELY-1519
In clustered environment Security Identity is restored during failover,
load balancer change node (not sticky behavior) and session
passivation/activation. Adding disable-restore-security-identity
configuration option which disables this behavior when set to "true".
=> [ELY-1519] Make restore of SecurityIdentity on replicated session configurable

tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java, tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java, tool/src/test/java/org/wildfly/security/tool/CustomPropertiesCredentialStore.java, tool/src/test/java/org/wildfly/security/tool/CustomPropertiesProvider.java, tool/src/test/resources/META-INF/services/java.security.Provider
Fix for ELY-1953. Some comments:
1. acl attributes are also preserved because previously the fix for ELY-1890 only worked in posix file systems (not windows).
2. The test for ELY-1890 has been modified because previously it always passed (I have modified the executable perm between two sequential calls).
3. To test this specific issue a custom credential store has been added, it doesn't flush the file at creation. The file doesn't exists at the beginning and that triggered the NoSuchFileException.
4. ELY-1890 only restores permissions when using elytron-tool, but the same issue happens with CLI. The real issue is the class [AtomicFileOutputStream](https://github.com/wildfly-security/wildfly-elytron/blob/1.x/util/src/main/java/org/wildfly/security/util/AtomicFileOutputStream.java#L55) …
=> [ELY-1953] Elytron tool command execution fails with java.nio.file.NoSuchFileException

src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
Issue (7.2.z): https://issues.redhat.com/browse/JBEAP-19513
Issue (7.3.z): https://issues.redhat.com/browse/JBEAP-19337
Upstream: https://issues.redhat.com/browse/ELY-1954
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1391
=> [JBEAP-19513] ELY-1954 - Submission for "j_security_check" login does not work if URL has no trailing slash

wildfly-elytron/pom.xml
Debugging a different issue I have found our service definitions are not merged in our shaded jar, we end up with a weird first defined wins behaviour.
https://issues.redhat.com/browse/ELY-1970
Attached to ELY-1970 is a text file showing the differences in the results.
=> [ELY-1970] Ensure multiple service implementations of the same type are aggregated.

_data/authors.yaml, _posts/2020-06-11-advanced-ejb-security.adoc
Note: In the very first link for "ejb-security" I want to add the link to the actual quickstart once it has been merged.
=> Add a blog post that covers Elytron's filesystem realms, credential stores and SASL authentication with EJBs

http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
https://issues.redhat.com/browse/ELY-2004
=> [ELY-2004] Remove handling of delegated credential as it is repeated as soon as `authorizeSrcName(...)` is called.

auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
https://issues.redhat.com/browse/ELY-2009
=> [ELY-2009] Remove loadedIdentities from PrincipalDistributedIdentity since it is unused and correct PrincipalDistributedIdentity#dispose

auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
https://issues.jboss.org/browse/ELY-1851 Elytron ldaps realm fails if a referral is returned inside a search
=> ELY-1851 set ThreadLocalSSLSocketFactory around LdapContext search.

base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java, http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java, http/base/src/main/java/org/wildfly/security/http/HttpConstants.java, http/base/src/main/java/org/wildfly/security/http/HttpExchangeSpi.java, http/base/src/main/java/org/wildfly/security/http/HttpServerRequest.java, http/deprecated/pom.xml, http/deprecated/src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java, http/external/pom.xml, http/external/src/main/java/org/wildfly/security/http/external/ExternalAuthenticationMechanism.java, http/external/src/main/java/org/wildfly/security/http/external/ExternalMechanismFactory.java, http/external/src/main/java/org/wildfly/security/http/external/WildFlyElytronHttpExternalProvider.java, mechanism/base/src/main/java/org/wildfly/security/mechanism/_private/ElytronMessages.java, pom.xml, provider/util/src/main/java/org/wildfly/security/provider/util/ProviderFactory.java, tests/base/pom.xml, tests/base/src/test/java/org/wildfly/security/http/external/ExternalAuthenticationMechanismTest.java, tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java, wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-1921
Supersedes https://github.com/wildfly-security/wildfly-elytron/pull/1386. This PR just combines Ashley's PR with a commit that updates the version in `http/external/pom.xml` to `1.13.0.CR5-SNAPSHOT`.
=> [ELY-1921] Adding External HTTP authentication mechanism

ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java, ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
https://issues.redhat.com/browse/ELY-2026
Under ELY-1979 we did attempt a number of different approaches to implement these methods directly and avoid the use of reflection, unfortunately as the project is built using Java 11 but targeting Java 8 the Java 11 compiler does not agree that these methods are present in Java 8.
We could consider a more complex build that compiles using two different JDKs but that seems overly complex, another option could be to split out an "accessor" class into another project which is built using the latest Java 8 (and has no plans to move to Java 11 soon) but that seems over complex.
Users of Java 9 or later will automatically get the JDKSpecific implementation that uses direct access.
=> [ELY-2026] Use reflection to pass through the new methods if they are now available on the SSLEngine, SSLParameters, and SSLSocket APIs.

_data/authors.yaml, _data/navigation.yml, _layouts/community.html, _posts/2018-08-31-obtaining-certificates-from-lets-encrypt-using-the-wildfly-cli.adoc, _posts/2020-10-14-distributed-and-failover-realms.adoc, _posts/2020-10-14-http-external-mechanism.adoc, _posts/2020-10-14-new-security-features-in-wildfly-21.adoc, _posts/2020-10-14-ssh-auth-for-git-persistence.adoc, _posts/2020-10-14-tls-13-with-wildfly-openssl.adoc
* Added a blog post on TLS 1.3 with OpenSSL
* Added a blog post that gives an overview of the new security features in WildFly 21
* Migrated my blog post on Let's Encrypt over to our website and added a section on how to use the security wrapper commands to obtain a certificate from Let's Encrypt, as suggested by Diana
Will adjust the dates in the posts once WildFly 21 is released.
=> Blog posts for WildFly 21

auth/server/base/src/main/java/org/wildfly/security/auth/callback/PrincipalAuthorizeCallback.java, auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java
Issue: https://issues.redhat.com/browse/ELY-2023
When the certificate mechanism is used behind a web proxy that injects the certificate and SSL info using headers (no cache available), the mechanism uses a `AuthorizeCallback` that fails (because it creates a `NamePrincipal` which is different to the original `X500Principal`). I decided to create a new callback for authorization but using a principal. Let me know if you see something better.
I'm sending the PR against EAP 1.10.x, if you need it against 1.x or other branch please just tell me to do that.
I'm preparing a test PR for wildfly that checks a certificate login using key-store realm.
Wildfly Test PR: https://github.com/wildfly/wildfly/pull/13573
=> [ELY-2023] Elytron ClientCertAuthenticationMechanism does not work when using a web proxy

ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java, ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
https://issues.redhat.com/browse/ELY-2026
https://issues.redhat.com/browse/JBEAP-20313
=> [1.10.x] [ELY-2026] Use reflection to pass through the new methods if they are now available on the SSLEngine, SSLParameters, and SSLSocket APIs.

tests/base/src/test/java/org/wildfly/security/auth/client/MaskedPasswordSSLAuthenticationTest.java, tests/base/src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java, tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java, tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java, tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java, tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java, tests/base/src/test/java/org/wildfly/security/util/PemTest.java, tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
https://issues.redhat.com/browse/ELY-2045
=> [1.10.x] [ELY-2045] Update tests to use SHA256withRSA instead of SHA1withRSA.

auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java, tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
https://issues.redhat.com/browse/ELY-2042
=> [ELY-2042] ElytronXMLParser is not configuring maximum-cert-path in X509RevocationTrustManager

tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-masked-password-ssl-config-v1_4.xml, tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
and do not use ServiceLoader discovery.
https://issues.redhat.com/browse/ELY-2059
=> [ELY-2059] Ensure all SSLContext instances exclusively use the installed providers

.github/workflows/pr-ci.yaml
https://issues.redhat.com/browse/ELY-2056
At the moment this is just a minimal PR to get things going, to test and tweak the PR triggers we really need it set up against a repo that receives PRs to get used to how it behaves so we know what changes it needs.
I haven't added additional items yet for gathering any logs etc.. we can see if we need those but for now all failures I have seen were reproducible locally using a download of the Zulu JDK.
Also for now I have included macOS in the list, we have a concurrency limit of 5 - we may take that one out later but for now contributors may develop on macOS so worth considering.
We already have Elytron Web split out into a separate project and we plan so split Jakarta EE and MicroProfile modules into their own projects so at some point I would …
=> [ELY-2056] Add a new GitHub workflow to trigger CI for pull requests.

_posts/2021-01-12-case-principal-transformer.adoc
Blog post providing an overview for new case principal transformer: https://issues.redhat.com/browse/ELY-1987
Has some missing links to be added once the corresponding quickstart gets merged: https://github.com/wildfly-security-incubator/elytron-examples/pull/29
=> Add a blog post about case-principal-transformer

auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java, credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java, tests/base/src/test/java/org/wildfly/security/auth/client/CredentialStoreSaslAuthenticationTest.java, tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java, tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-credential-sasl-config.xml
Issue: https://issues.redhat.com/browse/JBEAP-20656
Upstream Issue: https://issues.redhat.com/browse/ELY-1976
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1405
Backport of ELY-1976 to 1.10.x branch, needed for JBEAP-20656. Plain cherry-pick changing the version of the test configuration file `wildfly-credential-sasl-config.xml` to `urn:elytron:client:1.4` (in upstream was 1.5 that did not work).
=> [JBEAP-20656] [ELY-1976] Elytron provider not being used with credential store and SASL authentication on the client side

auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
https://issues.redhat.com/browse/ELY-2069
=> [ELY-2069] JWT token validation uses int instead of long for the dates:exp (expiration) and nbf

auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java, auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
Issue: https://issues.redhat.com/browse/ELY-2053
The option `key-store-masked-password` needed to manually add the elytron provider when the `wildfly-config.xml` was used in a standalone app. The change just passes the `providersSupplier` parameter as in all the rest of the calls. It also modifies the related test to not include the provider as before.
PR sent to 1.x if if it is needed in more branches just let me now.
Thanks!
=> [ELY-2053] key-store-masked-password needs the elytron provider to be manually registered

auth/server/base/src/main/java/org/wildfly/security/cache/CachedIdentity.java, auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/SecurityIdentityServerMechanismFactory.java, auth/server/http/src/main/java/org/wildfly/security/auth/server/http/SecurityIdentityServerMechanismFactory.java, http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java, http/base/src/main/java/org/wildfly/security/http/impl/BaseHttpServerRequest.java, http/base/src/main/java/org/wildfly/security/http/impl/package-info.java, http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java, http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java, http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java, http/sso/pom.xml, http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOn.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnManager.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSession.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/ProgrammaticSingleSignOnCache.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnConfiguration.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnManager.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSession.java, http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSessionFactory.java, http/util/src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java, http/util/src/main/java/org/wildfly/security/http/util/SimpleHttpServerCookie.java, http/util/src/main/java/org/wildfly/security/http/util/SocketAddressCallbackServerMechanismFactory.java
I am just raising as a draft PR for now as I have a few tasks to complete but I will need to handle them after the WildFly feature freeze as I need to get back to some feature development work in the meantime but I would like to get the reviews started on this approach to enable SSO for programmatic authentication.
For programmatic authentication this essentially takes the opposite approach to the approach used in the mechanisms and instead completely wraps the SSO access behind an IdentityCache - this does feel like it keeps the SSO session handling quite well constrained.
Debugging this issue did discover some additional issues which are included in this PR.
https://issues.redhat.com/browse/ELY-1626
https://issues.redhat.com/browse/ELY-2076
https://issues.redhat.com/browse/ELY-2077
=> [ELY-1626] Programmatic web authentication (HttpServletRequest.login()) does not trigger sso

auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, tests/base/src/test/java/org/wildfly/security/auth/server/CustomRealmMapperTest.java
https://issues.redhat.com/browse/ELY-2090
=> [ELY-2090] Evidence is not used when getting realm mapping in ServerAuthenticationContext#assignName

wildfly-elytron/pom.xml
Reverts https://github.com/wildfly-security/wildfly-elytron/pull/1495
It turns out that there are places in WildFly Core and WildFly where we were erroneously relying on some non-Elytron classes being included in the shaded JAR so the removal of these classes has resulted in test failures.
We will clean things up properly when we update the Maven dependencies in WildFly Core and WildFly to reference individual Elytron modules (see https://issues.redhat.com/browse/WFCORE-4261 and https://issues.redhat.com/browse/WFLY-11540).
=> Revert "[ELY-2099] Ensure only WildFly Elytron classes are included in the shaded JAR"

auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/TokenSecurityRealm.java
https://issues.redhat.com/browse/ELY-2104
=> [ELY-2104] two calls to introspection endpoint for one request with JWT

auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
Issue: https://issues.redhat.com/browse/JBEAP-20939
Upstream issue: https://issues.redhat.com/browse/ELY-2069
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1479
=> [ELY-2069] JWT token validation uses int instead of long for the dates: exp (expiration) and nbf

pom.xml
https://issues.redhat.com/browse/ELY-2109
=> [ELY-2109] Upgrade JBoss LogManager to 2.1.18.Final.

tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
Issue: https://issues.redhat.com/browse/JBEAP-21588
Upstream issue: https://issues.redhat.com/browse/ELY-2118
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1515
EAP 7.4.x: https://issues.redhat.com/browse/JBEAP-21587
EAP 7.4.x (1.15.x) PR: https://github.com/wildfly-security/wildfly-elytron/pull/1519
=> [ELY-2118] Elytron tool command execution fails with java.lang.UnsupportedOperationException on AIX OS.

auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java, tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
Issue: https://issues.redhat.com/browse/ELY-2111
Fixing issue for jwks parsing  in JwkManager. Test also modified to create the json file as the standard says (base64url, no padding and no sign byte).
PR for 1.10.x branch.
PR for 1.x: https://github.com/wildfly-security/wildfly-elytron/pull/1507
=> [ELY-2111] JwkManager uses incorrect non url-safe Base64 to load the jwks endpoint

ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLServerSocketFactory.java, ssl/src/main/java/org/wildfly/security/ssl/ConfiguredSSLSocketFactory.java
https://issues.redhat.com/browse/ELY-2117
=> [ELY-2117] SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) on IBM JDK after ELY-2026

pom.xml, tool/pom.xml
Issue: https://issues.redhat.com/browse/ELY-2102
We have to include org.slf4j.impl.* and org.jboss.logmanager.* in Elytron tool jar.
=> [ELY-2102] Fix slf4j warning messages when using Elytron Tool

ssl/src/main/java/org/wildfly/security/ssl/Protocol.java, tests/base/src/test/java/org/wildfly/security/ssl/SSLv2HelloAuthenticationTest.java, tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_6.xml
https://issues.redhat.com/browse/ELY-2024
=> [ELY-2024] Elytron server-ssl-context allowed protocols

sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java, sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClient.java, sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServer.java, sasl/plain/src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java, sasl/scram/src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java, sasl/scram/src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java
https://issues.redhat.com/browse/ELY-2127
=> [ELY-2127] Add client side TRACE logging after successful authentication

_posts/2021-06-18-ssl-certificate-revocation-list.adoc
Blog post providing overview on how to configure certificate revocation lists: https://issues.redhat.com/browse/ELY-2033
Has a missing link once the corresponding quickstart gets merged: https://github.com/wildfly-security-incubator/elytron-examples/pull/42
=> Add a blog post about configuring SSL using certificate revocation lists

_posts/2021-06-21-oneway-sslv2hello.adoc
Blog post providing overview on how to enable SSLv2Hello support: https://issues.redhat.com/browse/ELY-2024
Has a missing link once the corresponding quickstart gets merged: https://github.com/wildfly-security-incubator/elytron-examples/pull/40
=> Add blog post about configuring SSLv2Hello

_posts/2021-06-24-hash-charsets-encodings.adoc
Blog post providing overview for new hash-encoding and hash-charset attributes for Elytron Security Realms: https://issues.redhat.com/browse/ELY-2001
Has some missing links once the corresponding quickstart gets merged: https://github.com/wildfly-security-incubator/elytron-examples/pull/30
=> Add a blog post about hash-encodings and hash-charsets

auth/client/src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
https://issues.redhat.com/browse/ELY-2145
=> [ELY-2145] Default platform encoding used in OAuth2IntrospectValidator and OAuth2CredentialSource.

tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
https://issues.redhat.com/browse/ELY-2142
=> [ELY-2142] Elytron Tool: Default platform encoding used in VaultCommand.

.gitignore, _posts/2021-07-01-galleon-cli-keycloak.adoc
Temporarily on hold so we can publish immediately after the WildFly release.
This supersedes the following blog post:
https://github.com/wildfly-security/wildfly-elytron/pull/1455
=> Blog post - Using Galleon to provision the Keycloak client adators.

auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Issue: https://issues.redhat.com/browse/JBEAP-21852
Upstream issue: https://issues.redhat.com/browse/ELY-2120
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1517
=> ELY-2120 Avoid an NPE in ServerAuthenticationContext when the peer's IP address is not known

mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
Currently org.wildfly.security.mechanism.scram.ScramServer uses simple byte comparison to verify the message nonce and client proof.
Simple byte comparison returns on the first mismatch and is therefore susceptible to timing attacks.
[MessageDigest#isEqual(byte[],byte[])](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/MessageDigest.html#isEqual(byte%5B%5D,byte%5B%5D)) should be used to compare message nonces and client proofs in constant time.
=> [ELY-2147] Harden ScramServer against timing attacks

http/digest/src/main/java/org/wildfly/security/http/digest/DigestAuthenticationMechanism.java, http/digest/src/main/java/org/wildfly/security/http/digest/NonceManager.java, sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
https://issues.redhat.com/browse/ELY-2184
=> [ELY-2184] Refactor the Digest mechanisms to use MessageDigest#isEqual instead of Arrays#equals

auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Added parameter validation for hashCharset and hashEncoding in LdapSecurityRealm
[ELY-2153] Add parameter validation to LdapSecurityRealm
https://issues.redhat.com/browse/ELY-2153
=> [ELY-2153] Add parameter validation to LdapSecurityRealm

auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
https://issues.redhat.com/browse/ELY-2189
Note: I did not change the OAuth2Validator default timeouts (0), but, for consistency, they should be the same for both validators.
=> ELY-2189 Token Realm Validator timeouts

ELY_Messages.txt, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/_private/ElytronMessages.java, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java, auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java, tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
Issue: https://issues.redhat.com/browse/ELY-2194
The cache in `JwkManager` has been slightly modified:
* The cache is now just one map that contains the returned keys and the update timestamp all together.
* If the `kid` requested is not present in the cached entry the jwks endpoint is refreshed.
* To avoid lots of requests because of the previous point a new `minTimeBetweenRequests` option is introduced (between that time no requests are allowed to the same jwks endpoint).
@fjuma this is just the PR for the maintenance branch 1.10.x. There are several changes in this part of the code so conflicts will be present in main 1.x and maintenance 1.15.x branches when cherry-picking. If you want me to provide PRs for them just let me know. As always if you see any problem or improvement comments …
=> [ELY-2194] JWK implementation in JwkManager does not work properly on key rotation

tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
https://issues.redhat.com/browse/ELY-2070
=> [ELY-2070] CredentialStore is not able to get data from credential storage in file on IBM JDK 8

pom.xml
https://issues.redhat.com/browse/ELY-2217
=> [ELY-2217] Upgrade jose4j library to 0.7.9

http/basic/src/main/java/org/wildfly/security/http/basic/BasicAuthenticationMechanism.java
https://issues.redhat.com/browse/ELY-2149
Added trace log to indicate the BASIC authentication mechanism is ignored when silent is set and AUTHORIZATION header is not present
=> [ELY-2149] Enhance logging for silent BASIC authentication mechanism

pom.xml
Issue: https://issues.redhat.com/browse/ELY-2200
WF-Core upgrade: https://issues.redhat.com/browse/WFCORE-5538
=> [ELY-2200] Update org.apache.sshd:sshd-common:2.3.0 to 2.7.0 to eliminate CVE-2021-30129

http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java, http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfigurationBuilder.java, http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientContext.java, http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcJsonConfiguration.java, http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcSecurityRealm.java
https://issues.redhat.com/browse/ELY-2234
Add a new OIDC settings key named 'use-realm-role-mappings' to permit more control over role mappings behavior. This key defaults to 'true'.
=> [ELY-2234] Add use-realm-role-mappings OIDC configuration setting

auth/client/pom.xml, pom.xml
https://issues.redhat.com/browse/ELY-2256
=> [ELY-2256] Upgrade to RestEasy Client 4.7.2.Final and use dependency management in parent.

pom.xml
This is just a testsuite dependency.
https://issues.redhat.com/browse/ELY-2255
=> [ELY-2255] Upgrade net.minidev:json-smart to 2.4.7.

http/stateful-basic/pom.xml
https://issues.redhat.com/browse/ELY-2259
=> [ELY-2259] Fix version of wildfly-elytron-http-stateful-basic to be compatible with parent pom

auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java, auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java, auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java, tests/base/src/test/java/org/wildfly/security/auth/JaasSecurityRealmTest.java, tests/base/src/test/java/org/wildfly/security/auth/TestCallbackHandler.java, tests/base/src/test/java/org/wildfly/security/auth/TestLoginModule2.java, tests/base/src/test/resources/org/wildfly/security/auth/jaas-login.config, tests/base/src/test/resources/org/wildfly/security/auth/jaas-login2.config, tests/base/src/test/resources/org/wildfly/security/auth/login.config
https://issues.redhat.com/browse/ELY-2254
=> [ELY-2254] Provide a LoginModule compatible security realm.

_posts/2021-12-17-upcoming-filesystem-encryption-integrity.adoc
Blog post about filesystem encryption and integrity
Will need to change the date on the blog post but currently set to Dec 14 2021 so I could preview it on the github pages deployment
=> Add blog post about upcoming filesystem encryption and integrity features

http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcHttpFacade.java, http/oidc/src/main/java/org/wildfly/security/http/oidc/PublicKeyLocator.java
https://issues.redhat.com/browse/ELY-2286
The Interfaces OidcHttpFacade.Request must be public to allow implementing OidcClientConfigurationResolver.
I assume that's okay since the methods getRequest/getResponse in OidcHttpFacace are public anyway, but not really usable without the type.
It would be nice to have the PublicKeyResolver-Interface public as well, so that we can implement our own.
=> [ELY-2286] make the interfaces OidcHttpFacade.Request/Response and PublicKeyResolver public

http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java, http/oidc/src/test/java/org/wildfly/security/http/oidc/OidcTest.java
Issue: https://issues.redhat.com/browse/ELY-2284
Setting `providerUrl` instead of `authServerBaseUrl` in the OIDC configuration did not calculate the `relativeUrls` and [the implementation refreshed the context](https://github.com/wildfly-security/wildfly-elytron/blob/1.18.1.Final/http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientContext.java#L91-L102) in every request. Now both setters reset the calculated URLs and the relative field. The OIDC test is modified to check that the relative field is correctly set to NEVER with a normal configuration that uses an absolute URL.
@fjuma If you need the PR in another branch different to 1.x just let me know.
=> [ELY-2284] Wildfly OIDC secured App generates a lot of keycloak requests
