- src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java
- src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtils.java
- src/main/java/org/wildfly/security/password/PasswordUtils.java
- src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
- src/main/java/org/wildfly/security/password/impl/SaltedSimpleDigestPasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/SimpleDigestPasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/WildFlyElytronPasswordProvider.java
- src/main/java/org/wildfly/security/password/interfaces/SaltedSimpleDigestPassword.java
- src/main/java/org/wildfly/security/password/interfaces/SimpleDigestPassword.java
- src/main/java/org/wildfly/security/password/spec/SaltedSimpleDigestPasswordSpec.java
- src/main/java/org/wildfly/security/password/spec/SimpleDigestPasswordSpec.java
- src/test/java/org/wildfly/security/ldap/UserPasswordTests.java
- src/test/java/org/wildfly/security/password/impl/SaltedSimpleDigestPasswordTest.java
- src/test/java/org/wildfly/security/password/impl/SimpleDigestPasswordTest.java
Also for the salted form 'Salted' is now the start of the class name.
> [ELY-82] Move password types from TrivialDigest to SimpleDigest

- src/main/java/org/wildfly/security/asn1/ASN1.java
- src/main/java/org/wildfly/security/asn1/ASN1Decoder.java
- src/main/java/org/wildfly/security/asn1/ASN1Encoder.java
- src/main/java/org/wildfly/security/asn1/DERDecoder.java
- src/main/java/org/wildfly/security/asn1/DEREncoder.java
- src/test/java/org/wildfly/security/asn1/DERDecoderTest.java
- src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
* Support for "SET OF" elements
* Support for implicit and explicit tags
* Ability to handle already encoded values
* DEREncoder.hasNextElement() now returns false if the end of a SEQUENCE, SET, SET OF, or explicitly tagged element is reached
> Miscellaneous DER enhancements

- src/main/java/org/wildfly/security/asn1/ASN1Encoder.java
- src/main/java/org/wildfly/security/asn1/DEREncoder.java
- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/digest/SaslQuote.java
- src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslServer.java
- src/main/java/org/wildfly/security/sasl/scram/ScramUtil.java
- src/main/java/org/wildfly/security/sasl/util/StringPrep.java
- src/main/java/org/wildfly/security/util/ByteIterator.java
- src/main/java/org/wildfly/security/util/ByteStringBuilder.java
- src/main/java/org/wildfly/security/util/CodePointIterator.java
- src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
- src/test/java/org/wildfly/security/sasl/test/ByteStringBuilderTest.java
- src/test/java/org/wildfly/security/sasl/test/StringPrepTest.java
I expect this will need a rebase after previous PRs are merged but getting the PR in anyway as technically it is done.
> [ELY-136] Move ByteStringBuilder to the common util package.

- src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
- src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/DelegatingKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/ModifyTrackingKeyStore.java
- src/main/java/org/wildfly/security/keystore/ModifyTrackingKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/PasswordKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/PropertiesKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/UnmodifiableKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/WrappingPasswordKeyStoreSpiImpl.java
- src/main/java/org/wildfly/security/password/impl/WildFlyElytronPasswordProvider.java
- src/test/java/org/wildfly/security/keystore/ModifyTrackingKeyStoreTest.java
- src/test/java/org/wildfly/security/keystore/PropertiesFileKeyStoreTest.java
Also includes some refactoring so we have a common base for these KeyStoreSpi delegation implementations.
> [ELY-164] A KeyStore wrapper to track if modifications have been made to the KeyStore.

- src/main/java/org/wildfly/security/sasl/scram/ScramUtil.java
* Removed unused methods of ScramUtil.
* Access level of xor reduced to package-local.
> ScramUtil - removing dead code

- src/test/java/org/wildfly/security/password/impl/ClearPasswordTest.java
https://issues.jboss.org/browse/ELY-158
> [ELY-158] Add a ClearPassword test

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/asn1/ASN1.java
- src/main/java/org/wildfly/security/sasl/WildFlySasl.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2Util.java
- src/main/java/org/wildfly/security/sasl/util/StringPrep.java
- src/test/java/org/wildfly/security/sasl/gs2/Gs2Test.java
https://issues.jboss.org/browse/ELY-127
> [ELY-127] GS2 SASL client and server implementation and tests

- pom.xml
I don't have time to go through ELY-202 at the moment but realise new code I am writing can use this so sending in the dependency now.
> [ELY-206] Add a dependency on wildfly-common.

- src/main/java/org/wildfly/security/auth/provider/ldap/DirContextFactory.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/SimpleDirContextFactoryBuilder.java
- src/test/java/org/wildfly/security/ldap/UserPasswordSuiteChild.java
> [ELY-24] Initial code (LDAP realm password verification via login support)

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/callback/SecurityIdentityCallback.java
- src/main/java/org/wildfly/security/auth/login/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/login/SecurityIdentity.java
- src/main/java/org/wildfly/security/auth/login/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/KeyStoreBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/SimpleMapBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/spi/AuthorizationIdentity.java
- src/main/java/org/wildfly/security/auth/spi/RealmIdentity.java
- src/main/java/org/wildfly/security/auth/util/NameRewriter.java
- src/main/java/org/wildfly/security/sasl/WildFlySasl.java
- src/main/java/org/wildfly/security/sasl/util/SecurityIdentitySaslServerFactory.java
- src/test/java/org/wildfly/security/auth/JaasSecurityRealmTest.java
Allows things other than SASL to participate in authentication processing.  Provides a SecurityIdentity for completed authentications.  Provides for cleanup in the event of authentication completion or failure.
> Server Authentication Context enhancements.

- src/main/java/org/wildfly/security/auth/util/MappedRegexRealmMapper.java
- src/main/java/org/wildfly/security/auth/util/SimpleRegexRealmMapper.java
- src/main/java/org/wildfly/security/authz/AddPrefixRoleMapper.java
- src/main/java/org/wildfly/security/authz/AddSuffixRoleMapper.java
- src/main/java/org/wildfly/security/authz/RoleMapper.java
Prefix and suffix role mapper implementations, aggregation support for role mappers.
> Various role mappers

- README.md
Please don't reject if the sole comment is that additional information could be provided, additional pull requests welcome to build this out further.
> [ELY-169] Add a README to the project.

- src/main/java/org/wildfly/security/auth/login/RealmInfo.java
- src/main/java/org/wildfly/security/auth/login/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/KeyStoreBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/SimpleMapBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/spi/Attributes.java
- src/main/java/org/wildfly/security/auth/spi/AuthorizationIdentity.java
- src/main/java/org/wildfly/security/auth/spi/MapAttributes.java
- src/main/java/org/wildfly/security/auth/spi/SimpleAttributesEntry.java
- src/main/java/org/wildfly/security/authz/RoleDecoder.java
Use general attributes collections instead of just role sets from the security realm.
> Attributes support

- src/main/java/org/wildfly/security/sasl/WildFlySasl.java
- src/main/java/org/wildfly/security/sasl/util/FilterMechanismSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/FilterMechanismSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/SaslFactories.java
- src/main/java/org/wildfly/security/sasl/util/SaslPredicates.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslServerFactory.java
Predicate-based filtering for SASL mechanism names.
> SASL mechanism selection enhancements

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/callback/KeyTypeCallback.java
- src/main/java/org/wildfly/security/auth/callback/PeerPrincipalCallback.java
- src/main/java/org/wildfly/security/auth/callback/SocketAddressCallback.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationContext.java
- src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordPasswordUtil.java
- src/main/java/org/wildfly/security/auth/server/CredentialDecoder.java
- src/main/java/org/wildfly/security/auth/server/PrincipalDecoder.java
- src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java
- src/main/java/org/wildfly/security/password/PasswordUtil.java
- src/main/java/org/wildfly/security/password/impl/BCryptPasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/SunUnixMD5CryptPasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/UnixSHACryptPasswordImpl.java
- src/main/java/org/wildfly/security/permission/PermissionActions.java
- src/main/java/org/wildfly/security/util/ByteIterator.java
- src/main/java/org/wildfly/security/util/CodePointIterator.java
- src/main/java/org/wildfly/security/util/DefaultTransformationMapper.java
* `nullParameter()` message replaced by **Assert.checkNotNullParam** from common
* same `IllegalStateException` replaced by **Assert.impossibleSwitchCase**
> Using Assert from common

- src/main/java/org/wildfly/security/sasl/util/PropertiesSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/PropertiesSaslServerFactory.java
https://issues.jboss.org/browse/ELY-242
> [ELY-242] PropertiesSaslServerFactory

- src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/JdbcSecurityRealmBuilder.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/QueryBuilder.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/QueryConfiguration.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/mapper/AttributeMapper.java
- src/main/java/org/wildfly/security/auth/provider/jdbc/mapper/PasswordKeyMapper.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/AbstractJdbcSecurityRealmTest.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/AttributeMappingTest.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/AuthorizationIdentityTest.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/DataSourceRule.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/PasswordSupportTest.java
It depends on https://github.com/wildfly-security/wildfly-elytron/pull/224. It should be merged first.
Thanks.
> [ELY-227] - Attribute mapping to the Jdbc Security Realm.

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
Removed unused messages + spellcheck
> Unused Elytron messages clearing

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/SetCallbackHandlerAuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/SetGSSCredentialAuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/SetKeyStoreCredentialAuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/SetPasswordAuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/SetPasswordCallbackHandlerAuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/test/java/org/wildfly/security/sasl/gs2/Gs2Test.java
- src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
There are two things I don't like/am unsure about, I will comment on those in the diff.
> Make Gs2Tests use real callback handlers

- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomainSaslConfiguration.java
Also remove the redundant method from SecurityDomain.
> [ELY-266] Add a getMechanismNames method to the SecurityDomainSaslConfiguration

- src/main/java/org/wildfly/security/auth/provider/jdbc/mapper/PasswordKeyMapper.java
- src/test/java/org/wildfly/security/auth/provider/jdbc/PasswordSupportTest.java
* https://issues.jboss.org/browse/ELY-270
Minor change to the ```JdbcSecurityRealm``` in order to map Bcrypt passwords not only using Modular Crypt format, but also when there are different columns in a table for hash, salt and cost.
> [ELY-270] - Support separated columns for salt and cost when using the PasswordKeyMapper.

- src/main/java/org/wildfly/security/auth/callback/CredentialCallback.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ConfigurationKeyManager.java
- src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
- src/main/java/org/wildfly/security/auth/server/MechanismConfiguration.java
- src/main/java/org/wildfly/security/auth/server/MechanismRealmConfiguration.java
- src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/http/HttpAuthenticator.java
- src/test/java/org/wildfly/security/apacheds/LdapService.java
- src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
This is only for merging after https://github.com/wildfly-security/wildfly-elytron/pull/311 
This PR will then be for a single commit.
> [ELY-349] Ensure all Builders can be created from a static builder() method.

- src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/CredentialLoader.java
- src/main/java/org/wildfly/security/auth/provider/ldap/CredentialPersister.java
- src/main/java/org/wildfly/security/auth/provider/ldap/DirContextFactory.java
- src/main/java/org/wildfly/security/auth/provider/ldap/DirectEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/EvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/IdentityCredentialPersister.java
- src/main/java/org/wildfly/security/auth/provider/ldap/IdentityEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java
- src/main/java/org/wildfly/security/auth/provider/ldap/OtpCredentialLoader.java
- src/main/java/org/wildfly/security/auth/provider/ldap/SimpleDirContextFactoryBuilder.java
- src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java
- src/main/java/org/wildfly/security/auth/server/RealmIdentity.java
- src/test/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealmTest.java
- src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingTest.java
- src/test/java/org/wildfly/security/ldap/AttributeMappingTest.java
- src/test/java/org/wildfly/security/ldap/GroupMappingTest.java
- src/test/java/org/wildfly/security/ldap/PasswordSupportTest.java
- src/test/java/org/wildfly/security/ldap/PasswordValidationTest.java
- src/test/java/org/wildfly/security/ldap/PrincipalMappingTest.java
- src/test/java/org/wildfly/security/ldap/RoleMappingTest.java
Please just review and add +1s if appropriate, once the +1s are in I will merge at the same time as related subsystem changes.
> [ELY-347] Eliminating hard coded credential names and specially formatted credentials.

- src/main/java/org/wildfly/security/auth/provider/JaasSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/CredentialLoader.java
- src/main/java/org/wildfly/security/auth/provider/ldap/CredentialPersister.java
- src/main/java/org/wildfly/security/auth/provider/ldap/DirContextFactory.java
- src/main/java/org/wildfly/security/auth/provider/ldap/DirectEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/EvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/IdentityCredentialPersister.java
- src/main/java/org/wildfly/security/auth/provider/ldap/IdentityEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealmBuilder.java
- src/main/java/org/wildfly/security/auth/provider/ldap/OtpCredentialLoader.java
- src/main/java/org/wildfly/security/auth/provider/ldap/SimpleDirContextFactoryBuilder.java
- src/main/java/org/wildfly/security/auth/provider/ldap/UserPasswordCredentialLoader.java
- src/main/java/org/wildfly/security/auth/server/RealmIdentity.java
- src/test/java/org/wildfly/security/auth/provider/LegacyPropertiesSecurityRealmTest.java
- src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingTest.java
- src/test/java/org/wildfly/security/ldap/AttributeMappingTest.java
- src/test/java/org/wildfly/security/ldap/GroupMappingTest.java
- src/test/java/org/wildfly/security/ldap/PasswordSupportTest.java
- src/test/java/org/wildfly/security/ldap/PasswordValidationTest.java
- src/test/java/org/wildfly/security/ldap/PrincipalMappingTest.java
- src/test/java/org/wildfly/security/ldap/RoleMappingTest.java
Only the most recent commit needs reviewing on this one as the remainder are covered by https://github.com/wildfly-security/wildfly-elytron/pull/317 - as with https://github.com/wildfly-security/wildfly-elytron/pull/317 please just comment and add +1s as appropriate and I will merge along with subsystem changes,
> [ELY-357] Convert groups loaded from properties files to an Attribute on the AuthorizationIdentity

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingTest.java
- src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
https://issues.jboss.org/browse/ELY-336
> [ELY-336] Enable LoginPermission checks and make sure all users performing authentication in the test suite are granted this permission

- pom.xml
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/provider/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/oauth2/OAuth2SecurityRealm.java
- src/main/java/org/wildfly/security/auth/provider/oauth2/OAuth2Util.java
- src/main/java/org/wildfly/security/evidence/BearerTokenEvidence.java
- src/test/java/org/wildfly/security/auth/provider/oauth2/OAuth2SecurityRealmTest.java
* I've introduced a new dependency to JSR-353 (JSON-P) API. The reason is that we can use it to better handle JSON and it is also provided by JEE 7 or higher.
> [ELY-404] - OAuth2-based Security Realm

- src/main/java/org/wildfly/security/auth/provider/ldap/SimpleDirContextFactoryBuilder.java
- src/test/java/org/wildfly/security/ldap/AbstractAttributeMappingSuiteChild.java
- src/test/java/org/wildfly/security/ldap/AttributeMappingSuiteChild.java
- src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
- src/test/java/org/wildfly/security/ldap/GroupMappingSuiteChild.java
- src/test/java/org/wildfly/security/ldap/LdapTestSuite.java
- src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
- src/test/java/org/wildfly/security/ldap/PasswordSupportSuiteChild.java
- src/test/java/org/wildfly/security/ldap/PasswordValidationSuiteChild.java
- src/test/java/org/wildfly/security/ldap/PrincipalMappingSuiteChild.java
- src/test/java/org/wildfly/security/ldap/RoleMappingSuiteChild.java
- src/test/java/org/wildfly/security/ldap/TestEnvironmentSuiteChild.java
https://issues.jboss.org/browse/ELY-290
https://issues.jboss.org/browse/ELY-358
> [ELY-290][ELY-358] LDAP timeout and testsuite

- src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
Fix for test case issue https://issues.jboss.org/browse/ELY-481
> [ELY-481] Fixed SSLAuthenticationTest for IBM JDK

- src/main/java/org/wildfly/security/credential/store/impl/KeystorePasswordStore.java
Issues discovered while testing integration with elytron-subsytem.
> Small fixies to KeystorePasswordStore

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Just a simple formatting cleanup, no semantic changes at all.
> Clean up redundant class qualifiers

- src/test/java/org/wildfly/security/auth/realm/ldap/UserPasswordPasswordUtilTest.java
- src/test/java/org/wildfly/security/auth/realm/oauth2/OAuth2SecurityRealmTest.java
- src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java
- src/test/java/org/wildfly/security/sasl/scram/ScramClientCompatibilityTest.java
- src/test/java/org/wildfly/security/sasl/scram/ScramServerCompatibilityTest.java
https://issues.jboss.org/browse/ELY-334
> [ELY-334] specified charset in tests

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/ModifiableSecurityRealm.java
My older branch:
+ CloseableIterator as official output of ModifiableSecurityRealm
+ small refactoring of LdapSecurityRealm
> CloseableIterator as output of ModifiableSecurityRealm

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/callback/BearerTokenCallback.java
- src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
- src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2InitialClientMessage.java
- src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Server.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClient.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServer.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServerFactory.java
- src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslTest.java
*  #359 is a pre-requisite for this PR. Here, the commit https://github.com/wildfly-security/wildfly-elytron/commit/ae8ea404b9e5a4f8d7eec87bf4f4bb1d95fc766d is provided by that PR.
> [ELY-203] - Add OAuth2 SASL Mechanism.

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
- src/test/java/org/wildfly/security/sasl/gssapi/GSSSecurityFactory.java
- src/test/java/org/wildfly/security/sasl/gssapi/GssapiTestSuite.java
The SPNEGO mechanism is to follow but this is the generic SecurityFactory portion.
> [ELY-377] Add a SecurityFactory<Credential> implementation that creates and returns a GSSCredential

- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/credential/store/impl/KeystorePasswordStore.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/ssl/ProtocolSelector.java
- src/main/java/org/wildfly/security/util/URIUtil.java
Some problems were found using static analysis.  This is a bulk PR to fix several of them.
> Static analysis fixes

- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServerFactory.java
https://issues.jboss.org/browse/ELY-593
> [ELY-593] Optimizations in Gs2SaslClientFactory and Gs2SaslServerFactory

- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
https://issues.jboss.org/browse/ELY-619
> [ELY-619] Add a method to SecurityIdentity that sets the security identity for additional domains prior to running an action

- src/main/java/org/wildfly/security/permission/AbstractNamedPermission.java
https://issues.jboss.org/browse/ELY-626 ([WFLY-7082] before moving)
> [ELY-626] NamedPermission name null checking

- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
- src/main/java/org/wildfly/security/permission/ElytronPermission.java
- src/test/java/org/wildfly/security/authz/jacc/SecurityIdentityRule.java
https://issues.jboss.org/browse/ELY-623
> [ELY-623] SecurityIdentity - anonymous/name principal

- pom.xml
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/callback/ExclusiveNameCallback.java
- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/IdentitySharedExclusiveLock.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/sasl/WildFlySasl.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslServer.java
- src/main/java/org/wildfly/security/sasl/util/AuthenticationTimeoutSaslServerFactory.java
- src/test/java/org/wildfly/security/auth/FileSystemSecurityRealmTest.java
- src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
- src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
- src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
https://issues.jboss.org/browse/ELY-558
> [ELY-558] Introduce generalized support for authentication timeout of mechanisms

- src/main/java/org/wildfly/security/ssl/MechanismDatabase.java
- src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
https://issues.jboss.org/browse/ELY-647
> [ELY-647] MechanismDatabase SSL_ aliases fix

- src/main/java/org/wildfly/security/authz/PermissionMapper.java
- src/main/java/org/wildfly/security/authz/SimplePermissionMapper.java
https://issues.jboss.org/browse/ELY-641
> [ELY-641] constant-permission-mapper

- pom.xml
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
- src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStoreSpi.java
- src/main/java/org/wildfly/security/keystore/FilteringKeyStoreSpi.java
- src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
- src/main/java/org/wildfly/security/ssl/SecurityDomainTrustManager.java
- src/main/java/org/wildfly/security/x500/X500AttributePrincipalDecoder.java
- src/test/resources/logging.properties
https://issues.jboss.org/browse/WFLY-7193
> [WFLY-7193][ELY-634][ELY-637] logging - SSL + mappings

- src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/AttributeMapper.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-664
> [ELY-664] Ensure that the "index" attribute in AttributeMapper is greater than 1.

- .travis.yml
Add static code analysis to the process.
> Add Travis CI Coverity scan

- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java
- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
- src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java
Based on https://github.com/wildfly-security/wildfly-elytron/pull/510 [ELY-663]
* https://issues.jboss.org/browse/ELY-671
* https://issues.jboss.org/browse/ELY-672
* checking if user DN inside of search DN (if search DN specified)
> [ELY-671][ELY-672] LdapRealm - DN as username fixes

- src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java
- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
- src/main/java/org/wildfly/security/keystore/LdapKeyStoreSpi.java
Based on https://github.com/wildfly-security/wildfly-elytron/pull/510
https://issues.jboss.org/browse/ELY-669
> [ELY-669] LDAP referrals following - SSLSocketFactory setting

- src/main/java/org/wildfly/security/ssl/Protocol.java
https://issues.jboss.org/browse/ELY-627
> [ELY-627] standard SSL protocols names

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
Based on https://github.com/wildfly-security/wildfly-elytron/pull/516
https://issues.jboss.org/browse/ELY-680
> [ELY-680] Kerberos logging

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-690
> [ELY-690] NPE in SPNEGO fix

- src/test/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealmTest.java
- src/test/resources/org/wildfly/security/auth/realm/colondelimiter.properties
- src/test/resources/org/wildfly/security/auth/realm/specialchars.properties
https://issues.jboss.org/browse/ELY-692
> [ELY-692] Added tests for special chars in LegacyPropertiesSecurityRealm

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/sasl/util/SetMechanismInformationSaslServerFactory.java
https://issues.jboss.org/browse/ELY-702
> [ELY-702] multiple SetMechanismInformationSaslServerFactory using

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
SPNEGO authentication reworked to fulfil test of mchoma.
https://issues.jboss.org/browse/ELY-693
> [ELY-693] SPNEGO continuation required fixes

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/callback/AvailableRealmsCallback.java
- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/NonceManager.java
- src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
- src/main/java/org/wildfly/security/http/impl/UsernamePasswordAuthenticationMechanism.java
- src/main/java/org/wildfly/security/mechanism/digest/DigestQuote.java
- src/main/java/org/wildfly/security/mechanism/digest/DigestUtil.java
- src/main/java/org/wildfly/security/password/impl/DigestPasswordImpl.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java
- src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java
This pull request is specifically for RFC2609, this mechanism will be enhanced to add support for RFC2617 and RFC7616.
Some utility code related to Digest handling has been split into a mechanism independent utility class, there is more to split out but will need to also get to the following issue: -
https://issues.jboss.org/browse/ELY-722
> [ELY-713] RFC2069 Based HTTP Digest Mechanism

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Based on https://github.com/wildfly-security/wildfly-elytron/pull/434
https://issues.jboss.org/browse/ELY-712
> [ELY-712] GSSCredential propagation

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-690
* Different response for authorization fail and for null initiator name
* Not only UNAUTHORIZED responses should contain Negotiation headers
> [ELY-690] SPNEGO response headers fixes

- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-733
> [ELY-733] Coverity static analysis: Useless call in Elytron

- src/main/java/org/wildfly/security/mechanism/digest/DigestQuote.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-737
> [ELY-737] Coverity static analysis: Operands don't affect result in Elytron

- src/main/java/org/wildfly/security/asn1/DEREncoder.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-740
> [ELY-740] Coverity static analysis: Dereference null return value in EntityUtil (Elytron)

- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
(to identify issues like the that Zach's one)
> Logging - traces of ClientCert authentication

- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
https://issues.jboss.org/browse/ELY-797
> [ELY-797] LdapRealm - DirContext closing in finally block

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
- src/main/java/org/wildfly/security/auth/client/CredentialStoreReference.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/credential/source/CredentialStoreCredentialSource.java
- src/main/resources/schema/elytron-1_0.xsd
- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
- src/test/java/org/wildfly/security/sasl/digest/CompatibilityClientTest.java
https://issues.jboss.org/browse/ELY-449
> [ELY-449] Add CredentialStore support to Elytron client configuration

- pom.xml
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
- src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
- src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
- src/main/resources/schema/elytron-1_0.xsd
- src/test/java/org/wildfly/security/auth/realm/token/OAuth2TokenSecurityRealmTest.java
- src/test/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientTest.java
- src/test/resources/org/wildfly/security/sasl/oauth2/wildfly-oauth2-test-config.xml
I've added a test dependency `com.squareup.okhttp3:mockwebserver` that provides a mock for web servers.
> [ELY-658] - OAuth2 Resource Owner Password Credentials Client Configuration

- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-830
> [ELY-830] Coverity static analysis: Resource leak in KeyStoreCredentialStore (Elytron)

- src/main/java/org/wildfly/security/asn1/OidsUtil.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-831
> [ELY-831] Coverity static analysis: Resource leak in OidsUtil (Elytron)

- src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealmBuilder.java
https://issues.jboss.org/browse/ELY-850
Subsystem part: https://github.com/wildfly-security/elytron-subsystem/pull/357
> [ELY-850] LdapRealm - blank password disallowing

- src/main/java/org/wildfly/security/auth/principal/AnonymousPrincipal.java
- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/SimpleMapBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/UsernamePasswordAuthenticationMechanism.java
Issue: https://issues.jboss.org/browse/ELY-632
This is a request for comments at the moment. I'm looking for an opinion if that's what is expected/wanted from this issue and, if not, what should be changes before I commit to a full PR.
> [ELY-632] No log messages comming from Elytron - authentication process start

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
(should be backward compatible - mergable without subsystem part)
https://issues.jboss.org/browse/ELY-862
Subsystem part: https://github.com/wildfly-security/elytron-subsystem/pull/353
> [ELY-862] CredentialSource into DirContext

- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestFactory.java
- src/main/java/org/wildfly/security/sasl/digest/DigestClientFactory.java
- src/main/java/org/wildfly/security/sasl/digest/DigestServerFactory.java
- src/main/java/org/wildfly/security/sasl/entity/EntitySaslClient.java
- src/main/java/org/wildfly/security/sasl/entity/EntitySaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/entity/EntitySaslServer.java
- src/main/java/org/wildfly/security/sasl/entity/EntitySaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/gssapi/AbstractGssapiMechanism.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserServer.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/otp/OTP.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSasl.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
- src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java
https://issues.jboss.org/browse/ELY-788
> [ELY-788] SASL mechs null handling

- src/main/java/org/wildfly/security/cache/CachedIdentity.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOn.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnEntry.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnManager.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSession.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java
- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionIdentifierFactory.java
- src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOn.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnEntry.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnManager.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnServerMechanismFactory.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSessionContext.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOnSessionFactory.java
https://issues.jboss.org/browse/ELY-878
> ELY-878 Refactor single sign on mechanism to accomodate a distributed implementation.

- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java
Consolidate DefaultSingleSignOnSessionFactory constructor parameters.
> Don't use a permissive HostnameVerifier by default for sso logout connections

- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-800
> [ELY-800] Elytron ExternalSaslServerFactory.createSaslServer should return null for unsupported policies

- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOnSessionFactory.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-919
> [ELY-919] Coverity: default platform encoding used in DefaultSingleSignOnSessionFactory

- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-916
This will give us opportunity to use custom KeyStore (for example for FIPS certified CredentialStore).
> [ELY-916] Add ability to use specified Provider[] when creating KeyStore instance in KeyStoreCredentialStore

- src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java
- src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
https://issues.jboss.org/browse/ELY-902
> [ELY-902] LdapRealm - dont require LDAP to check evidence verify support

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
https://issues.jboss.org/browse/ELY-862
Subsystem part (this not depends on it): https://github.com/wildfly-security/elytron-subsystem/pull/390
> [ELY-862] AuthenticationContext into DirContext

- src/main/java/org/wildfly/security/credential/store/CredentialStore.java
- src/main/java/org/wildfly/security/credential/store/CredentialStoreSpi.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- src/main/java/org/wildfly/security/credential/store/impl/MapCredentialStore.java
- src/main/java/org/wildfly/security/credential/store/impl/VaultCredentialStore.java
- src/test/java/org/wildfly/security/credential/store/CredentialStoreBuilder.java
- src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
I have missed changes originally. Sorry.
> [ELY-916] missing API changes for injecting Provider[] to CredentialStore

- src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java
- src/test/java/org/wildfly/security/sasl/digest/_private/DigestUtilTest.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-946
> [ELY-946] Coverity static analysis, suspicious bitwise logical expression, DigestUtil (Elytron)

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
- src/test/resources/logging.properties
https://issues.jboss.org/browse/ELY-912
In the end fixed not only for logging but for passing into env too.
> [ELY-912] DirContext - fix of passing arrays into env

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
- src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordCredentialLoader.java
- src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
Reworked direct verification (by picketbox implementation) to work correctly with FOLLOW mode.
https://issues.jboss.org/browse/ELY-971
> [ELY-971] LdapRealm - direct evidence verification in FOLLOW mode

- src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java
- src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
Changes related to:
* https://issues.jboss.org/browse/ELY-788
* https://issues.jboss.org/browse/ELY-800
* https://issues.jboss.org/browse/ELY-803
* https://issues.jboss.org/browse/ELY-982
* https://issues.jboss.org/browse/ELY-983
> Update ignored tests for EXTERNAL SASL Mechanism

- src/main/java/org/wildfly/security/http/util/sso/DefaultSingleSignOn.java
- src/main/java/org/wildfly/security/http/util/sso/SingleSignOn.java
https://issues.jboss.org/browse/ELY-957
Supersedes https://github.com/wildfly-security/wildfly-elytron/pull/690
> ELY-957 Clarify semantics of SingleSignOn.setIdentity(...).

- src/main/java/org/wildfly/security/password/impl/BSDUnixDESCryptPasswordImpl.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-960
> [ELY-960] Coverity static analysis: Suspicious integer expression in BSDUnixDESCryptPasswordImpl (Elytron)

- src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
Wildfly Elytron: https://issues.jboss.org/browse/ELY-964
> [ELY-964] Coverity static analysis, Resource leak on an exceptional path, FileAuditEndpoint (elytron)

- src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
Accordingly with the specs, providers are not required to resolve permissions associated with a subject or protection domain. But that doesn't mean we should throw an exception in case someone wants to do so.
This change still keep the read-only behavior of the returned {{PermissionCollection}}, but delegates to the wrapped provider the resolution of permissions.
Clients are still forced to use implies if they want to actually check for permissions.
> [ELY-181] - getPermissions should return empty elements instead of throwing exception

- src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-997
> [ELY-997] Form authentication - added missing resumeRequest

- src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
https://issues.jboss.org/browse/ELY-995
> [ELY-995] - fix SIMPLE audit log

- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
- src/test/java/org/wildfly/security/sasl/gssapi/GSSSecurityFactorySuiteChild.java
https://issues.jboss.org/browse/ELY-674
Related subsystem PR: https://github.com/wildfly-security/elytron-subsystem/pull/273
> [ELY-674] Krb5LoginModule options

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
https://issues.jboss.org/browse/ELY-996
https://issues.jboss.org/browse/WFCORE-2369
> [ELY-996] - add module to dir context to allow different CL to be used

- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
This fixes https://issues.jboss.org/browse/JBEAP-9555
> Fix issue with digest auth from older remoting versions

- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-709
> [ELY-709] custom GSSManager in SPNEGO

- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Fix for https://issues.jboss.org/browse/ELY-1016
Cache in KeyStoreCredentialStore must work with lowercase aliases (keys) too.
> [ELY-1016] Cache in KeyStoreCredentialStore must work with lowercase aliases (keys) too

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
https://issues.jboss.org/browse/ELY-912
no related subsystem change
> [ELY-912] DirContext properties logging fix

- src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/IdentityCredentials.java
- src/test/java/org/wildfly/security/ldap/LdapSecurityRealmIdentityCacheSuiteChild.java
https://issues.jboss.org/browse/ELY-923
Added caching of evidences into caching realm.
> [ELY-923] Caching realm - evidence verification caching

- src/main/java/org/wildfly/security/auth/client/ModuleLoader.java
https://issues.jboss.org/browse/ELY-1039
Fix LGPL->ASL copyright header.
> [ELY-1039] copyright header

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/http/util/AggregateServerMechanismFactory.java
- src/main/java/org/wildfly/security/http/util/FilterServerMechanismFactory.java
- src/main/java/org/wildfly/security/http/util/SecurityProviderServerMechanismFactory.java
- src/main/java/org/wildfly/security/http/util/ServiceLoaderServerMechanismFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslServerFactory.java
- src/main/java/org/wildfly/security/ssl/SSLUtils.java
https://issues.jboss.org/browse/ELY-1002
no subsystem part
> [ELY-1002] Elytron non-providing provider log message

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1041
https://issues.jboss.org/browse/EAP7-277
> [ELY-1041] Add support for PKCS11 in KeyStoreCredentialStore

- src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java
@kwart , I believe it is just C&P mistake
> SaslFactoriesApiTest, fix for C&P bug

- src/main/java/org/wildfly/security/http/util/SetMechanismInformationMechanismFactory.java
...in SetMechanismInformationMechanismFactory
https://issues.jboss.org/browse/ELY-1040
https://issues.jboss.org/browse/JBEAP-9975
> ELY-1040 Wrong IPv6 address extraction

- src/main/java/org/wildfly/security/password/impl/BSDUnixDESCryptPasswordImpl.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1019
JBEAP: https://issues.jboss.org/browse/JBEAP-9741
> [ELY-1019] Elytron, ensure BSDUnixDESCryptPasswordImpl don't suffer on sign-extension bug

- src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
I added some tests for Credential Store.
There are tests for these Jira issues:
* https://issues.jboss.org/browse/ELY-820
* https://issues.jboss.org/browse/WFLY-7742
* https://issues.jboss.org/browse/ELY-653 RESOLVED
> add tests for Credential store

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1049
JBEAP: https://issues.jboss.org/browse/JBEAP-10076
> [ELY-1049] Coverity, division by zero in KeyStoreCredentialStore (Elytron)

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
Links for the Jiras:
https://issues.jboss.org/browse/ELY-1073
https://issues.jboss.org/browse/ELY-1074
> [ELY-1073] Add support for kerberos security factory in AuthenticationConfiguration

- src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
https://issues.jboss.org/browse/ELY-1022
https://issues.jboss.org/browse/JBEAP-9770
related subsystem PR: https://github.com/wildfly-security-incubator/wildfly-core/pull/120
> [ELY-1022] SSL into SyslogAuditEndpoint

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
- src/main/java/org/wildfly/security/audit/RotatingFileAuditEndpoint.java
- src/test/java/org/wildfly/security/audit/RotatingFileAuditEndpointTest.java
https://issues.jboss.org/browse/ELY-1006
https://issues.jboss.org/browse/JBEAP-9623
related subsystem change: https://github.com/wildfly-security-incubator/wildfly-core/pull/119
> [ELY-1006][JBEAP-9623] audit logs rotation

- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousClientFactory.java
- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousServerFactory.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestFactory.java
- src/main/java/org/wildfly/security/sasl/digest/DigestClientFactory.java
- src/main/java/org/wildfly/security/sasl/digest/DigestServerFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiClientFactory.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiServerFactory.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/otp/OTP.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSasl.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/AbstractSaslFactory.java
> [ELY-983] wildfly.sasl.mechanism-query-all should only influence getMechanismNames and not createSasl* methods.

- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- src/main/java/org/wildfly/security/permission/ElytronPermission.java
https://issues.jboss.org/browse/ELY-1055
https://issues.jboss.org/browse/JBEAP-10116
> [ELY-1055] privileged blocks in FileSystemRealm

- src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
https://issues.jboss.org/browse/ELY-1011
> [ELY-1011] JsonSecurityEventFormatter - null principal handling

- src/main/java/org/wildfly/security/credential/store/impl/VaultCredentialStore.java
https://issues.jboss.org/browse/ELY-1043
https://issues.jboss.org/browse/JBEAP-10005
> [ELY-1043] support getAliases() to perform full conversion from Vault format

- src/main/java/org/wildfly/security/http/util/SecurityProviderServerMechanismFactory.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1079
JBEAP: https://issues.jboss.org/browse/JBEAP-10305
> [ELY-1079] SecurityProviderServerMechanismFactory incorrect log message

- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1101
https://issues.jboss.org/browse/JBEAP-10459
> [ELY-1101] Wrong offset causing padding check to throw BadPaddingException

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1048
JBEAP: https://issues.jboss.org/browse/JBEAP-10075
> [ELY-1048] Coverity, ignoring number of bytes read

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/server/NameRewriter.java
- src/main/java/org/wildfly/security/auth/util/RegexNameRewriter.java
- src/main/java/org/wildfly/security/auth/util/RegexNameValidatingRewriter.java
- src/main/java/org/wildfly/security/authz/SimplePermissionMapper.java
https://issues.jboss.org/browse/ELY-1115
https://issues.jboss.org/browse/JBEAP-9628
related but not dependency: https://github.com/wildfly-security-incubator/wildfly-core/pull/152
> [ELY-1115][JBEAP-9628] principal-transformers null handling

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.jboss.org/browse/ELY-1106
https://issues.jboss.org/browse/JBEAP-10591
> [ELY-1106] - fix parser to match XSD(cipher-suite and protocol)

- src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java
https://issues.jboss.org/browse/ELY-1110
Updated AuthenticationContextTest due to ELY-987 has been resolved.
> [ELY-1110] Updated AuthenticationContextTest

- src/main/java/org/wildfly/security/auth/client/RuleNode.java
- src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java
https://issues.jboss.org/browse/JBEAP-9293
ELY issue https://issues.jboss.org/browse/ELY-988
> [JBEAP-9293] [ELY-988] Fix RuleNode replacing logic.

- src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
https://issues.jboss.org/browse/ELY-1022
https://issues.jboss.org/browse/JBEAP-9770
related core PR: https://github.com/wildfly-security-incubator/wildfly-core/pull/155
Added possibility to set SSLSocketFactory for syslog audit logger.
> [ELY-1022][JBEAP-9770] custom SocketFactory to the SyslogAuditEndpoint

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
Fix of RegexValidatingPrincipalTransformerTestCase broken by [ELY-1115].
Null principal should be considered wrong username passed by user, as discussed.
Replaces https://github.com/wildfly-security/wildfly-elytron/pull/798 and https://github.com/wildfly-security-incubator/wildfly-core/pull/156
> [ELY-1115] null principal handling in ServerAuthenticationContext

- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java
- src/test/java/org/wildfly/security/auth/client/AuthenticationContextTest.java
- src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java
- src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
https://issues.jboss.org/browse/ELY-983
https://issues.jboss.org/browse/JBEAP-9231
> [ELY-983] fix the MECHANISM_QUERY_ALL handling in ExternalSaslServerFactory and unignore regression tests

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
https://issues.jboss.org/browse/ELY-1062
Enabler: https://issues.jboss.org/browse/JBEAP-9684
> [ELY-1062] - add way to defer listener registration

- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
https://issues.jboss.org/browse/ELY-1146
https://issues.jboss.org/browse/JBEAP-10812
> Fix copy/paste issue (Coverity discovered)

- src/test/java/org/wildfly/security/http/ServerMechanismFactoryImplContractTest.java
Test covers ServerMechanismFactoryImpl compliance of contract defined by  HttpServerAuthenticationMechanismFactory interface.
> [ELY-1061] Test ServerMechanismFactoryImpl fulfills contract

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1144
https://issues.jboss.org/browse/JBEAP-10803
> [ELY-1144] Introduce externalPath initial attribute to handle 'external' case with different storage file location

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/credential/store/CredentialStore.java
- src/main/java/org/wildfly/security/util/ProviderUtil.java
- src/main/resources/schema/elytron-1_0.xsd
This is ready for reviews but please hold off merging for the moment as I will coordinate with tags and backports to WildFly Core as it is an API breaking change.
> [ELY-1152] Rework AuthenticationClient Provider handling.

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/resources/schema/elytron-1_0.xsd
- src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config.xml
https://issues.jboss.org/browse/ELY-1138
https://issues.jboss.org/browse/JBEAP-10772
> [ELY-1138][JBEAP-10772] certificate-revocation-list into Elytron XML

- src/main/java/org/wildfly/security/ssl/CipherSuitePredicate.java
- src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
https://issues.jboss.org/browse/JBEAP-9871
https://issues.jboss.org/browse/ELY-1182
> [ELY-1182] Update the 'DEFAULT' cipher suite filter to "ALL:!EXPORT:!LOW:!aNULL:!eNULL:!SSLv2"

- src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
https://issues.jboss.org/browse/ELY-990
https://issues.jboss.org/browse/JBEAP-9297
> [ELY-990] Ensure Throwables are logges as Throwables and not Object.toString();

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Fix of PR https://github.com/wildfly-security/wildfly-elytron/pull/780
https://issues.jboss.org/browse/ELY-1038
https://issues.jboss.org/browse/JBEAP-9250
This PR renders: #742 obsolete.
> [ELY-1038] - use config entries rather than callback - fix

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
Issue: https://issues.jboss.org/browse/ELY-1177
> [ELY-1177] Using rewrite-user-name-regex element in Elytron client configuration file causes NPE

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
Checking KeyTab / key in KeyTab availability in GSSCredentialSecurityFactory
https://issues.jboss.org/browse/ELY-1117
> [ELY-1117] KeyTab checking in GSSCredential factory

- src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
- src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
https://issues.jboss.org/browse/ELY-1193
> [ELY-1193] unsecured JWT fix

- src/main/java/org/wildfly/security/auth/client/MatchPurposeRule.java
- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
https://issues.jboss.org/browse/ELY-1202
(no PR deps)
> [ELY-1202] MatchPurposeRule - null handling

- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
https://issues.jboss.org/browse/ELY-1185
Only test improvement in the end, as the issue alone was already fixed by ELY-1184 fix.
> [ELY-1184][ELY-1185] Elytron XML test coverage

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
Trivial multiple providers URLs handling for DirContext builder.
(by discussion with @darranl on Hipchat)
> DirContext fix for multiple providers URL

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/util/URIUtil.java
- src/main/resources/schema/elytron-1_0.xsd
- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
- src/test/java/org/wildfly/security/util/URIUtilTest.java
https://issues.jboss.org/browse/ELY-1207
https://issues.jboss.org/browse/JBEAP-11149
> [ELY-1207][JBEAP-11149] match-user instead of match-userinfo

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
- src/main/java/org/wildfly/security/auth/server/RealmInfo.java
- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
- src/main/java/org/wildfly/security/authz/AuthorizationIdentity.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
- src/main/java/org/wildfly/security/util/_private/Arrays2.java
https://issues.jboss.org/browse/ELY-680
https://issues.jboss.org/browse/JBEAP-6498
> [ELY-680] kerberos logging improvement

- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
https://issues.jboss.org/browse/ELY-1117
https://issues.jboss.org/browse/JBEAP-10653
related (but not depends) to https://github.com/wildfly/wildfly-core/pull/2486
> [ELY-1117] keytab file check made optional (and disabled by default)

- src/main/java/org/wildfly/security/mechanism/scram/ScramClient.java
- src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserServer.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslServer.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslServer.java
- src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
https://issues.jboss.org/browse/ELY-1151
https://issues.jboss.org/browse/JBEAP-10871
> [ELY-1151] Empty authorization name - server side fix

- src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
- src/main/java/org/wildfly/security/ssl/SecurityDomainTrustManager.java
https://issues.jboss.org/browse/ELY-1217
https://issues.jboss.org/browse/JBEAP-11177
Dependency of https://github.com/wildfly/wildfly-core/pull/2496
> [ELY-1217] MechanismConfigurationSelector into SSLContext

- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
https://issues.jboss.org/browse/ELY-1223
https://issues.jboss.org/browse/JBEAP-11355
> [ELY-1223] Update Gs2SaslServer to use ServerCredentialCallback to obtain the GSSCredential

- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
Easy fix to mismatched file path
https://issues.jboss.org/browse/JBEAP-10803
https://issues.jboss.org/browse/ELY-1144
> [ELY-1144] wrong key containing keystore location

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
- src/main/java/org/wildfly/security/auth/server/SaslAuthenticationFactory.java
Improved traces to log impl class of mechanism
https://issues.jboss.org/browse/ELY-1225
> [ELY-1225] SASL mech class in traces

- src/main/java/org/wildfly/security/sasl/localuser/LocalUserServer.java
https://issues.jboss.org/browse/ELY-1214
https://issues.jboss.org/browse/JBEAP-11240
> [ELY-1214] Remove finalizer for LocalUserServer

- src/main/resources/schema/elytron-1_0.xsd
This is not an urgent fix but flagging as 'Critical' as resolving PR conflicts will likely involve repeating these changes from scratch each time until it is merged.
> [ELY-1241] Re-order main sections of elytron-1_0.xsd.

- src/main/java/org/wildfly/security/sasl/util/SortedMechanismClientServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/SortedMechanismSaslServerFactory.java
Needs to be coordinated with https://github.com/wildfly/wildfly-core/pull/2540
https://issues.jboss.org/browse/ELY-1215
https://issues.jboss.org/browse/JBEAP-11262
> [ELY-1215] Update the wrapper factories that support sorting of mechanism names to also accept a given ordering of mechanism names

- src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- src/main/java/org/wildfly/security/http/HttpExchangeSpi.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/util/SecurityProviderServerMechanismFactory.java
- src/main/java/org/wildfly/security/http/util/ServiceLoaderServerMechanismFactory.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslServerFactory.java
Jira: https://issues.jboss.org/browse/ELY-1233
Thorough checking so that `logger.trace()`, `logger.debug()` won't lose cause stack trace.
> [ELY-1233] Elytron revise why exception stacktrace is not logged in some cases

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
If the client sent a response we can not handle challenging again is not going to result in a better message.
The end result is that we can also reach the states where we return either an internal server error or forbidden status code in the event that negotiation is not possible /.fails and no other mechanisms are available to take over authentication.
> [ELY-1256] Make SPNEGO fail quickly if the call to acceptSecContext fails.

- src/main/java/org/wildfly/security/auth/util/ElytronAuthenticator.java
Jira issues:
https://issues.jboss.org/browse/ELY-1259
https://issues.jboss.org/browse/JBEAP-11726
> ELY-1259: Add log traces for ElytronAuthenticator exceptions

- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServerFactory.java
- src/test/java/org/wildfly/security/sasl/external/ExternalSaslClientTest.java
- src/test/java/org/wildfly/security/sasl/external/ExternalSaslServerTest.java
https://issues.jboss.org/browse/ELY-982
https://issues.jboss.org/browse/JBEAP-9230
> [ELY-982] Fix property filtering for the EXTERNAL SASL mechanism

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- src/main/java/org/wildfly/security/sasl/util/SSLQueryCallbackHandler.java
These changes relies on https://github.com/jboss-remoting/jboss-remoting/pull/127. Without it, PLUS mechs won't work.
> [ELY-1232] - Minor fixes to get PLUS mech working

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
- src/main/java/org/wildfly/security/auth/server/RealmIdentity.java
- src/main/java/org/wildfly/security/auth/server/SecurityRealm.java
- src/main/java/org/wildfly/security/authz/Roles.java
- src/main/java/org/wildfly/security/sasl/util/AbstractDelegatingSaslClient.java
- src/main/java/org/wildfly/security/sasl/util/AbstractDelegatingSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/AbstractDelegatingSaslServer.java
- src/main/java/org/wildfly/security/sasl/util/AbstractDelegatingSaslServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityProviderSaslServerFactory.java
- src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLContextSpi.java
Delegated object in toString of delegating object
https://issues.jboss.org/browse/ELY-1225
https://issues.jboss.org/browse/JBEAP-11307
> [ELY-1225] Logging improvement - toString of delegating objects

- src/main/java/org/wildfly/security/ssl/SecurityDomainTrustManager.java
https://issues.jboss.org/browse/ELY-1275
https://issues.jboss.org/browse/JBEAP-11904
> [ELY-1275] SecurityDomainTrustManager fix for verifiable-only realm

- src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1235
JBEAP: https://issues.jboss.org/browse/JBEAP-11424
> [ELY-1235] Coverity, Dereference null return value, JdbcSecurityRealm (Elytron)

- src/main/java/org/wildfly/security/sasl/gs2/Gs2Util.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslServerFactory.java
https://issues.jboss.org/browse/ELY-1283
https://issues.jboss.org/browse/JBEAP-12108
> [ELY-1283] Ensure the SCRAM and GS2 SASL server and client factories offer the PLUS mechanisms before the non-PLUS variants

- src/main/java/org/wildfly/security/util/ServiceLoaderSupplier.java
Jira issues:
https://issues.jboss.org/browse/ELY-1284
https://issues.jboss.org/browse/JBEAP-12111
> ELY-1284: Allow ServiceLoaderSupplier to load services in a privileged block

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- src/main/java/org/wildfly/security/password/impl/OneTimePasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
- src/main/java/org/wildfly/security/password/interfaces/OneTimePassword.java
- src/main/java/org/wildfly/security/sasl/otp/OTP.java
- src/main/java/org/wildfly/security/sasl/otp/OTPUtil.java
https://issues.jboss.org/browse/ELY-1290
https://issues.jboss.org/browse/JBEAP-12113
(no deps)
> [ELY-1290] More digest algorithms into OneTimePassword

- src/main/java/org/wildfly/security/auth/realm/ldap/OtpCredentialLoader.java
- src/test/resources/ldap/elytron-otp-tests.ldif
https://issues.jboss.org/browse/JBEAP-12140
https://issues.jboss.org/browse/ELY-1289
(no deps)
> [ELY-1289] OTP seed without base64 encoding

- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1237
JBEAP: https://issues.jboss.org/browse/JBEAP-11446
> [ELY-1237] Coverity, Resource leak in SecurityIdentity (Elytron)

- src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
- src/main/java/org/wildfly/security/audit/PeriodicRotatingFileAuditEndpoint.java
- src/main/java/org/wildfly/security/audit/SizeRotatingFileAuditEndpoint.java
- src/test/java/org/wildfly/security/audit/PeriodicRotatingFileAuditEndpointTest.java
- src/test/java/org/wildfly/security/audit/SizeRotatingFileAuditEndpointTest.java
- src/test/java/org/wildfly/security/util/TestClock.java
https://issues.jboss.org/browse/ELY-1293
> ELY-1293 System.currentTimeMillis() cannot be mocked on IBM JDK

- src/main/java/org/wildfly/security/credential/source/CredentialStoreCredentialSource.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
https://issues.jboss.org/browse/ELY-1308
https://issues.jboss.org/browse/JBEAP-11821
> [ELY-1308] KeyStoreCredentialStore encrypt initialization fix for BouncyCastle

- src/test/java/org/wildfly/security/ldap/X509EvidenceVerificationSuiteChild.java
https://issues.jboss.org/browse/ELY-1299
Note that there are more `*.pem` files with non-PEM content there in `src/test/resources/ca/certs`. Changing those has not brought any change on IBM JDK. Hence left them untouched.
> ELY-1299 X509EvidenceVerificationSuiteChild.testX509Auth() fails on IBM

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java
- src/main/java/org/wildfly/security/sasl/otp/OTPSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SaslMechanismInformation.java
https://issues.jboss.org/browse/ELY-1316
Fixes for OTP SASL mechanism.
> [ELY-1316] Fix OTP SASL mechanism support

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Predominantly https://issues.jboss.org/browse/JBEAP-12460 but also addresses https://issues.jboss.org/browse/JBEAP-12432.
https://issues.jboss.org/browse/ELY-1312
> [ELY-1312] SPNEGO Cache SecurityIdentity and make scope configurable.

- src/main/java/org/wildfly/security/auth/realm/ldap/LdapSecurityRealm.java
Resubmitt of https://github.com/wildfly-security/wildfly-elytron/pull/937 / https://github.com/wildfly-security/wildfly-elytron/pull/938 for 1.1.x
Fix of NPE caused by closing not opened LDAP connection.
1.1.x by discussion with @olukas + triage call
https://issues.jboss.org/browse/ELY-1321
https://issues.jboss.org/browse/JBEAP-12623
> [ELY-1321] LDAP realm - closing only successfully opened connections

- src/main/java/org/wildfly/security/x500/X500PrincipalUtil.java
https://issues.jboss.org/browse/ELY-437
@darranl could you please review?
@dmlloyd is this what you meant with bundling a "stub" version of the class? Note that the stub is there only during the compilation and is removed afterwards.
The present PR fixes just the compilation on IBM Java 8. There are still many tests failing on IBM JDK. I'd report and eventually also fix those unless @darranl vetoes.
> ELY-437 Elytron compilation fails with IBM JDK

- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2Util.java
https://issues.jboss.org/browse/ELY-1328
https://issues.jboss.org/browse/JBEAP-12688
> [ELY-1328] Ensure the gs2-header that's sent to the server does not contain the channel binding data

- src/main/java/org/wildfly/security/util/ServiceLoaderSupplier.java
https://issues.jboss.org/browse/ELY-1337
https://issues.jboss.org/browse/EJBCLIENT-254
https://issues.jboss.org/browse/JBEAP-12752
> [1.1] ELY-1337 Bootclassloader defined services lead to NPE

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
One final continuation for https://issues.jboss.org/browse/JBEAP-12460
> [ELY-1339] If authorization failed start the authentication process again.

- src/main/java/org/wildfly/security/auth/client/CallbackKind.java
documented as requested by @jfdenise in https://github.com/wildfly/wildfly-core/pull/2713#discussion_r133396472
> [ELY-1341] Javadoc: callback types association with callback kinds

- src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
> [ELY-1315] add writeLock test

- pom.xml
commit 362aa0e
https://issues.jboss.org/browse/ELY-1345
> [ELY-1345] ExceptionInInitializerError in tests on IBM reintroduced by

- src/main/java/org/wildfly/security/credential/source/LocalKerberosCredentialSource.java
- src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
CredentialStore obtaining GSSCredential from Kerberos cache (ticket visible from klist etc)
https://issues.jboss.org/browse/ELY-1066
> [ELY-1066] LocalKerberosCredentialSource

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
Added privileged block around default ServiceLoaderSupplier to prevent need of regular deployment to have read permission to wildfly-elytron JAR. (Privileged block must not be around general ServiceLoaderSupplier obtaining with custom classloader - would be security vulnerability)
https://issues.jboss.org/browse/ELY-1349
https://issues.jboss.org/browse/JBEAP-12913
(resubmit of https://github.com/wildfly-security/wildfly-elytron/pull/972 against 1.1.x, as requested by @kabir, already reviewed by @dmlloyd in old PR)
> [ELY-1349] privileged obtaining of Elytron ServiceLoaderSupplier

- src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
related subsystem change: https://github.com/wildfly/wildfly-core/pull/2753
https://issues.jboss.org/browse/ELY-1351
https://issues.jboss.org/browse/JBEAP-11498
> [ELY-1351] SecurityDomain without realms support

- src/main/java/org/wildfly/security/ssl/CipherSuitePredicate.java
- src/main/java/org/wildfly/security/ssl/MechanismDatabase.java
- src/main/java/org/wildfly/security/ssl/MechanismDatabase.properties
- src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
https://issues.jboss.org/browse/ELY-386
https://issues.jboss.org/browse/JBEAP-2125
> [ELY-386] MechanismDatabase - ciphersuit with more openssl names

- src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
https://issues.jboss.org/browse/JBEAP-13108
> [ELY-1364] - Missing WWW-Authenticate header on unauthorized responses

- src/main/java/org/wildfly/security/credential/source/CommandCredentialSource.java
https://issues.jboss.org/browse/ELY-1368
https://issues.jboss.org/browse/JBEAP-13145
> [ELY-1368] Redirect error output to 'NUL' or '/dev/null'

- pom.xml
https://issues.jboss.org/browse/ELY-681
> [ELY-681] Public and private javadoc generating

- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
No review required but don't merge - just submitting as a PR to check no CI jobs break as a result of the sync from 1.1.x.
> Merge 1 1 x

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2.java
- src/main/resources/schema/elytron-client-1_1.xsd
- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
- src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java
* local-kerberos added into client config xml and AuthenticationConfiguration
* one place where are SPNEGO_OID/KRB5_OID constants defined -> OidsUtil
https://issues.jboss.org/browse/ELY-1357
> [ELY-1357] local-kerberos credential into XML

- src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1359
JBEAP: https://issues.jboss.org/browse/JBEAP-13039
> [ELY-1359] Mask password when logging LDAP connection environment

- src/main/java/org/wildfly/security/x500/cert/SubjectKeyIdentifierExtension.java
https://issues.jboss.org/browse/ELY-1384
> [ELY-1384] Fix the DER encoding of the subject key identifier extension

- src/main/resources/schema/elytron-1_0.xsd
- src/main/resources/schema/elytron-1_0_1.xsd
- src/main/resources/schema/elytron-client-1_1.xsd
wildfly-elytron: https://issues.jboss.org/browse/ELY-1391
JBEAP: https://issues.jboss.org/browse/JBEAP-13416
> [ELY-1391] Check if all elements in elytron-1_0.xsd are parsed correctly in ElytronXmlParser.

- pom.xml
https://issues.jboss.org/browse/ELY-1397
> [ELY-1397] pom.xml - full javadoc generating fix

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/resources/schema/elytron-1_0.xsd
- src/main/resources/schema/elytron-1_0_1.xsd
- src/main/resources/schema/elytron-client-1_1.xsd
- src/test/java/org/wildfly/security/auth/client/XmlConfigurationTest.java
First round of fixes / enhancements for Authentication Client XML handling after reviewing whilst documenting the implementation in the previous version.
> [ELY-1395] / [ELY-1388] / [ELY-1394] / [ELY-1378] Authentication Client Xml Handling

- src/main/java/org/wildfly/security/credential/store/CredentialStore.java
Placing this one on hold for now since it hasn't been ACKed yet.
https://issues.jboss.org/browse/ELY-1031
https://issues.jboss.org/browse/JBEAP-13470
> [ELY-1031] Make the CredentialStore class final

- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslClient.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClient.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServer.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslServer.java
- src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
- src/main/java/org/wildfly/security/sasl/util/LocalPrincipalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityIdentitySaslServerFactory.java
Revert "[ELY-1380] getNegotiatedProperty exception when not complete"
This reverts commit d795c6e6f6a08b0d46c771fc0f66e065ce2bd0b9.
> [ELY-1411] Revert the fix for ELY-1380.

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/util/ProviderUtil.java
- src/main/resources/schema/elytron-client-1_1.xsd
Some further enhancements regarding overriding the algorithm for the TrustManager and using configured Providers for the KeyStore and TrustManager.
> [ELY-1379] / [ELY-1385] / [ELY-1170] TrustManager and KeyStore Provider / Algorithm Handling

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/asn1/ASN1Decoder.java
- src/main/java/org/wildfly/security/asn1/DERDecoder.java
- src/test/java/org/wildfly/security/asn1/DERDecoderTest.java
- src/test/java/org/wildfly/security/asn1/DEREncoderTest.java
https://issues.jboss.org/browse/ELY-1403
> [ELY-1403] Add the ability to decode an ASN.1 boolean value

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-1373
https://issues.jboss.org/browse/JBEAP-12868
> [ELY-1373] SPNEGO should not send base challenge on failed authorization

- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslClient.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslClient.java
- src/main/java/org/wildfly/security/sasl/external/ExternalSaslServer.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslServer.java
- src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
- src/main/java/org/wildfly/security/sasl/util/LocalPrincipalSaslClientFactory.java
- src/main/java/org/wildfly/security/sasl/util/SecurityIdentitySaslServerFactory.java
Once JBoss Remoting contains this PR https://github.com/jboss-remoting/jboss-remoting/pull/157 we should be able to re-apply.
Keep this one on hold until we know Remoting is ready.
> [ELY-1412] Re-apply [ELY-1380] 

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/util/GSSCredentialSecurityFactory.java
Related to (but not depends on): https://github.com/wildfly/wildfly-core/pull/2891
https://issues.jboss.org/browse/JBEAP-11055
https://issues.jboss.org/browse/ELY-1406
> [ELY-1406] GSSCredential obtaining fails caching

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/asn1/ASN1.java
- src/main/java/org/wildfly/security/pem/Pem.java
- src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
- src/test/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequestTest.java
https://issues.jboss.org/browse/ELY-132
> [ELY-132] Add support for generating certificate signing requests

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/asn1/ASN1.java
- src/main/java/org/wildfly/security/x500/cert/AccessDescription.java
- src/main/java/org/wildfly/security/x500/cert/AuthorityInformationAccessExtension.java
- src/main/java/org/wildfly/security/x500/cert/CertUtil.java
- src/main/java/org/wildfly/security/x500/cert/KeyUsage.java
- src/main/java/org/wildfly/security/x500/cert/KeyUsageExtension.java
- src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
- src/main/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKey.java
- src/main/java/org/wildfly/security/x500/cert/SubjectInformationAccessExtension.java
- src/test/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKeyTest.java
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1012
https://issues.jboss.org/browse/ELY-1424
> [ELY-1424] Add the ability to generate self-signed X.509 certificates

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestFactory.java
- src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java
- src/test/java/org/wildfly/security/password/impl/DigestPasswordTest.java
issue: https://issues.jboss.org/browse/ELY-1304
JBEAP issue: https://issues.jboss.org/browse/JBEAP-12316
> [ELY-1304] Elytron subsystem does not expose digest-sha-384 for digest password

- src/main/java/org/wildfly/security/http/impl/BasicAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/BearerTokenAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/ClientCertAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/FormAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslClient.java
- src/main/java/org/wildfly/security/sasl/anonymous/AnonymousSaslServer.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiServer.java
- src/main/java/org/wildfly/security/sasl/localuser/LocalUserServer.java
- src/main/java/org/wildfly/security/sasl/oauth2/OAuth2SaslClient.java
- src/main/java/org/wildfly/security/sasl/plain/PlainSaslClient.java
- src/main/java/org/wildfly/security/sasl/scram/ScramSaslClient.java
- src/main/java/org/wildfly/security/sasl/util/LocalPrincipalSaslClientFactory.java
- src/test/java/org/wildfly/security/sasl/gssapi/SubjectWrappingSaslClient.java
- src/test/java/org/wildfly/security/sasl/gssapi/SubjectWrappingSaslServer.java
* HTTP/SASL mechanisms implementations final
* unnecessary methods private/package-local (affects only non-exported packages http.impl, sasl)
https://issues.jboss.org/browse/ELY-659
> [ELY-659] Mechanism implementations final

- src/main/java/org/wildfly/security/x500/cert/CertUtil.java
- src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
- src/main/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKey.java
- src/test/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKeyTest.java
https://issues.jboss.org/browse/ELY-1447
> [ELY-1447] Ensure the subject key identifier extension gets added if it isn't specified when generating a self-signed certificate

- src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java
- src/test/java/org/wildfly/security/sasl/test/LocalUserTest.java
https://issues.jboss.org/browse/ELY-1156
> [ELY-1156] LocalUserClient - unsupported NameCallback support

- src/main/java/org/wildfly/security/sasl/localuser/LocalUserClient.java
**Fix of broken build in master** - unsufficient modification on rebase after sasl loggin rework - sorry for that.
Fixing merged change
https://github.com/wildfly-security/wildfly-elytron/pull/1024/files#diff-67fefed1fc801ba8b35e39fa238169feR122
> [ELY-1156] fix of broken build related to sasl logging rework

- src/main/java/org/wildfly/security/auth/server/event/RealmDefiniteOutcomeAuthenticationEvent.java
https://issues.jboss.org/browse/ELY-1453
> [ELY-1453] hidden class RealmDefiniteOutcomeAuthenticationEvent fix

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1430
JBEAP: https://issues.jboss.org/browse/JBEAP-13656
> [ELY-1430] WARN logged during server shutdown when Elytron JACC is set

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/x500/GeneralName.java
- src/test/java/org/wildfly/security/x500/cert/SelfSignedX509CertificateAndSigningKeyTest.java
https://issues.jboss.org/browse/ELY-1458
> [ELY-1458] Ensure the URI name is valid when attempting to create a GeneralName.URIName

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/main/java/org/wildfly/security/mechanism/digest/PasswordDigestObtainer.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/test/java/org/wildfly/security/sasl/digest/DigestCallbackHandlerUtils.java
- src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
https://issues.jboss.org/browse/ELY-991 (change how are callbacks used - by @dmlloyd design)
https://issues.jboss.org/browse/ELY-1426 (fix of URP generating - for username, not for authzid)
> [ELY-991][ELY-1426] Digest callback handling rework and fix

- src/main/java/org/wildfly/security/authz/jacc/ElytronPolicyConfiguration.java
https://issues.jboss.org/browse/ELY-609
In the end, synchronization block is not needed to add into getters - references was set volatile instead (equivalent to atomic reference).
> [ELY-609] ElytronPolicyConfiguration synchronization

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.jboss.org/browse/ELY-849
> [ELY-849] Rename setMechanismProperties to setSaslMechanismProperties

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- src/main/java/org/wildfly/security/digest/Sha512_256MessageDigest.java
- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/main/java/org/wildfly/security/http/impl/ServerMechanismFactoryImpl.java
- src/main/java/org/wildfly/security/mechanism/digest/DigestUtil.java
- src/main/java/org/wildfly/security/password/impl/DigestPasswordImpl.java
- src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
- src/main/java/org/wildfly/security/password/interfaces/DigestPassword.java
- src/main/java/org/wildfly/security/sasl/SaslMechanismPredicate.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestFactory.java
- src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- src/main/java/org/wildfly/security/sasl/digest/_private/DigestUtil.java
- src/main/java/org/wildfly/security/sasl/util/SaslMechanismInformation.java
- src/main/java/org/wildfly/security/util/ByteIterator.java
- src/test/java/org/wildfly/security/digest/Sha512_256MessageDigestTest.java
- src/test/java/org/wildfly/security/http/DigestAuthenticationMechanismTest.java
- src/test/java/org/wildfly/security/http/HttpAuthenticatorTest.java
- src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
- src/test/java/org/wildfly/security/password/impl/DigestPasswordTest.java
Based on https://github.com/wildfly-security/wildfly-elytron/pull/990
https://issues.jboss.org/browse/ELY-302
> [ELY-302] SHA-512-256 digest algorithm and SASL mech

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/digest/DigestServerFactory.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
- src/main/java/org/wildfly/security/sasl/gssapi/GssapiServer.java
- src/test/java/org/wildfly/security/sasl/digest/DigestTest.java
- src/test/java/org/wildfly/security/sasl/gs2/Gs2SuiteChild.java
- src/test/java/org/wildfly/security/sasl/gssapi/BaseGssapiTests.java
- src/test/java/org/wildfly/security/sasl/gssapi/GssapiCompatibilitySuiteChild.java
- src/test/java/org/wildfly/security/sasl/gssapi/JaasUtil.java
- src/test/java/org/wildfly/security/sasl/gssapi/JdkClientJdkServerSuiteChild.java
- src/test/java/org/wildfly/security/sasl/gssapi/JdkClientWildFlyServerSuiteChild.java
- src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientJdkServerSuiteChild.java
- src/test/java/org/wildfly/security/sasl/gssapi/WildFlyClientWildFlyServerSuiteChild.java
https://issues.jboss.org/browse/ELY-124
> [ELY-124] SASL unbound server name (digest, gssapi, gs2)

- pom.xml
https://issues.jboss.org/browse/ELY-1491
> ELY-1491 [JDK10] - update build props for java 10

- src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java
https://issues.jboss.org/browse/ELY-1492
> [ELY-1492] GSSAPI test fix - path to krb5.conf

- src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
https://issues.jboss.org/browse/ELY-1493
(keeping 1s where timeout is expected to not prolong test run time)
> [ELY-1493] KeyStore test - extended too short timeouts

- src/main/java/org/wildfly/security/credential/source/FactoryCredentialSource.java
https://issues.jboss.org/browse/ELY-1500
> [ELY-1500] FactoryCredentialSource acquire support fix

- src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
https://issues.jboss.org/browse/ELY-1507
> [ELY-1507] JwtValidator issuer and audience check ignoring does not work

- src/main/java/org/wildfly/security/credential/store/CredentialStorePermission.java
- src/main/java/org/wildfly/security/manager/WildFlySecurityManagerPermission.java
- src/main/java/org/wildfly/security/permission/ElytronPermission.java
- src/main/java/org/wildfly/security/sasl/util/SortedMechanismClientServerFactory.java
- src/main/java/org/wildfly/security/sasl/util/SortedMechanismSaslServerFactory.java
- src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
Especially enumeration of names for *Permission.
https://issues.jboss.org/browse/ELY-1509
> [ELY-1509] Javadoc fixes

- src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
https://issues.jboss.org/browse/ELY-1494
* disabled testing of PKCS12 for all non-Oracle JDKS (OpenJDK is Oracle)
* removed workaround for older Oracle JDK 8 (not needed already) and IBM (not sufficient for PKCS12) - see issue comment
> [ELY-1494] disabled PKCS12 KeyStore test for HP, removed unnecessary workaround

- src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslServer.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1479
JBEAP: https://issues.jboss.org/browse/JBEAP-14149
> [ELY-1479] Coverity, Missing call to superclass in AbstractGssapiMechanism

- pom.xml
This is an example of a PR based off a commit common both to master and the maintenance branch, PRs can be submitted to both branches and merged independently - when we later merge the maintenance branch to master as the change is the same commit we avoid duplication in master.
> [ELY-1515] Update JAPICMP Check version to 1.2.0.Final and update includes to match latest public packages.

- pom.xml
This is an example of a PR based off a commit common both to master and the maintenance branch, PRs can be submitted to both branches and merged independently - when we later merge the maintenance branch to master as the change is the same commit we avoid duplication in master.
> 1.2.x [ELY-1515] Update JAPICMP Check version to 1.2.0.Final and update includes to match latest public packages.

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
Also [ELY-1518] Elimination of a stream and lambdas where a for loop can be used.
https://issues.jboss.org/browse/ELY-1503
https://issues.jboss.org/browse/ELY-1518
> [ELY-1503] Ensure the reference to the GssContext and KerberosTicket can be dropped during Serialization.

- src/main/resources/schema/elytron-client-1_1.xsd
wildfly-elytron: https://issues.jboss.org/browse/ELY-1082
JBEAP: https://issues.jboss.org/browse/JBEAP-10373
Adding documentation to xsd.
> [ELY-1082] Documentation is missing in elytron-1_0.xsd

- pom.xml
https://issues.jboss.org/browse/ELY-1533
> 1.2.x [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron

- pom.xml
https://issues.jboss.org/browse/ELY-1533
> [ELY-1533] Prevent SNAPSHOT versions of json-smart from being downloaded when building Elytron

- pom.xml
https://issues.jboss.org/browse/ELY-1523
> [ELY-1523] JAPICMP checking level independent on version number

- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
backport of https://github.com/wildfly-security/wildfly-elytron/pull/1097 / https://github.com/wildfly-security/wildfly-elytron/pull/1098 into 1.1.x
https://issues.jboss.org/browse/ELY-1503
https://issues.jboss.org/browse/JBEAP-14152
> [ELY-1503] Wrap the GSSContext and KerberosTicket to work with distributed session

- src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
wildfly-elytron: https://issues.jboss.org/browse/ELY-1436
> [ELY-1436] Log jdbc-realm key-mapper processing

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.jboss.org/browse/ELY-1553
> [ELY-1553] Wrap WildFlyElytronProvider construction in a privileged block

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.jboss.org/browse/ELY-1557
> [ELY-1557] ElytronXMLParser use == comparison for strings

- src/main/java/org/wildfly/security/audit/FileAuditEndpoint.java
Allowed to enable/disable flush/sync independently.
Related subsystem change: https://github.com/wildfly/wildfly-core/pull/3186
https://issues.jboss.org/browse/ELY-1550
https://issues.jboss.org/browse/JBEAP-10639
> [ELY-1550] FileAuditEndpoint - independent flush/sync

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/mechanism/oauth2/OAuth2Client.java
https://issues.jboss.org/browse/ELY-657
> [ELY-657] Updated OAuth2Client error message for unsupported callbacks

- src/main/java/org/wildfly/security/auth/realm/jdbc/mapper/PasswordKeyMapper.java
- src/test/java/org/wildfly/security/auth/realm/jdbc/PasswordSupportTest.java
https://issues.jboss.org/browse/ELY-1582
Added possibility to use HEX and BASE64 encoding for digest and salt in JDBC realm.
> [ELY-1582] hex/base64 encoding of password in JDBC

- src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
- src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
https://issues.jboss.org/browse/ELY-1583
Improvement of TRACEs coverage in keystore realm and properties realm based on troubleshooting with @ppalaga.
Realms has not provided enough info to be easy to troubleshot CLIENT-CERT authentication.
+ small refactoring: returning NON_EXISTENT identity from properties realm allowed to remove few null checks
> [ELY-1583] adding more TRACEs into keystore and properties realms

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- src/test/java/org/wildfly/security/sasl/gssapi/CommunicationSuiteChild.java
https://issues.jboss.org/browse/ELY-1570
> [ELY-1570] handling null classloader in WildFlyElytronProvider

- src/main/java/org/wildfly/security/WildFlyElytronProvider.java
https://issues.jboss.org/browse/ELY-1603
> [ELY-1603] Add missing HTTP mechanisms to the WildFlyElytronProvider initialisation.

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/authz/MappedRoleMapper.java
- src/main/java/org/wildfly/security/authz/MappedRoles.java
- src/test/java/org/wildfly/security/authz/RoleMappingTest.java
https://issues.jboss.org/browse/ELY-1591
> [ELY-1591] Provide Elytron alternative to RoleMappingLoginModule

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/http/HttpConstants.java
- src/main/java/org/wildfly/security/http/impl/DigestAuthenticationMechanism.java
- src/test/java/org/wildfly/security/http/DigestAuthenticationMechanismTest.java
https://issues.jboss.org/browse/ELY-1599
> [ELY-1599] support of username* into Digest HTTP mechanism

- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
- src/test/java/org/wildfly/security/auth/server/IdentityPropagationTest.java
- src/test/java/org/wildfly/security/auth/server/IdentitySwitchingTest.java
https://issues.jboss.org/browse/ELY-1601
> [ELY-1601] SecurityIdentity.withSecurityIdentity null handling + tests

- src/main/java/org/wildfly/security/auth/client/AuthenticationContext.java
- src/main/java/org/wildfly/security/auth/server/FlexibleIdentityAssociation.java
- src/main/java/org/wildfly/security/auth/server/Scoped.java
- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
https://issues.jboss.org/browse/ELY-1531
> [ELY-1531] runAs operations sync between Scoped/SecurityIdentity and AC

- index.html
HTML preview: http://htmlpreview.github.io/?https://github.com/justinmcook/wildfly-elytron/blob/gh-pages/index.html
> Modified index to be a table

- src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
https://issues.jboss.org/browse/ELY-1625
> [ELY-1625] Fix ECPublicKey import

- src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
https://issues.jboss.org/browse/ELY-1630
> [ELY-1630] Ensure that any blank lines in the PEM certificate chain returned by an ACME server get ignored to avoid parsing issues on IBM JDK

- src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
https://issues.jboss.org/browse/ELY-1633
> [ELY-1633] Incorrect double checked locking in AuthenticationConfiguration

- src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
- src/main/java/org/wildfly/security/cache/LRURealmIdentityCache.java
- src/main/java/org/wildfly/security/http/impl/NonceManager.java
- src/test/java/org/wildfly/security/sasl/test/BaseTestCase.java
https://issues.jboss.org/browse/ELY-1632
> [ELY-1632] Fix compiler warnings

- src/main/java/org/wildfly/security/x500/cert/acme/AcmeChallenge.java
https://issues.jboss.org/browse/ELY-1636
> [ELY-1636] Update AcmeChallenge.Type to be able to handle unknown challenge types

- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
With this change I just want to log some of the steps taken to load the configuration as at the moment it is easy for locating the configuration to fail without useful information being available as to which step failed.
https://issues.jboss.org/browse/ELY-1647
> [ELY-1647] Add TRACE messages to allow debugging of the loading of the client side configuration.

- pom.xml
https://issues.jboss.org/browse/ELY-1652
> [ELY-1652] Remove generation time metadata from Javadoc

- src/main/java/org/wildfly/security/ssl/SSLUtils.java
https://issues.jboss.org/browse/ELY-1664
> [ELY-1664] Fix trace logging in SSLUtils

- src/main/java/org/wildfly/security/auth/realm/ldap/DirContextFactory.java
https://issues.jboss.org/browse/ELY-1637
> [ELY-1637] Change ReferralMode.toString to return value

- src/main/java/org/wildfly/security/auth/realm/ldap/DelegatingLdapContext.java
https://issues.jboss.org/browse/ELY-1634
> [ELY-1634] LDAPS referrals broken

- src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
https://issues.jboss.org/browse/ELY-1676
> [ELY-1676] Add missing ARIA encryption to CipherSuiteSelector

- src/main/java/org/wildfly/security/ssl/SSLUtils.java
https://issues.jboss.org/browse/ELY-1681
> [ELY-1681] Include the thrown exception in the trace logging in SSLUtils#createSslContextFactory

- src/main/java/org/wildfly/security/ssl/SSLUtils.java
https://issues.jboss.org/browse/ELY-1683
> [ELY-1683] Add more trace logging in SSLUtils#createSslContextFactory to indicate which protocols and providers are attempted

- pom.xml
- src/test/java/org/wildfly/security/ldap/X509EvidenceVerificationSuiteChild.java
ELY-1695 Jira: https://issues.jboss.org/browse/ELY-1695
ELY-1692 Jira: https://issues.jboss.org/browse/ELY-1692
> [ELY-1692] Tests are not run with -Djava8.home java

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java
- src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
- src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
- src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
- src/test/java/org/wildfly/security/auth/realm/token/RsaJwk.java
- src/test/resources/org/wildfly/security/auth/realm/token/wildfly-jwt-test-config.xml
https://issues.jboss.org/browse/ELY-1551
> [ELY-1551] JwtValidator jku and kid header parameters

- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/ssl/SNIContextMatcher.java
- src/main/java/org/wildfly/security/ssl/SNISSLContext.java
- src/main/java/org/wildfly/security/ssl/SNISSLContextSpi.java
- src/main/java/org/wildfly/security/ssl/SNISSLEngine.java
- src/main/java/org/wildfly/security/ssl/SNISSLExplorer.java
- src/main/java/org/wildfly/security/ssl/_private/SelectingContext.java
https://issues.jboss.org/browse/ELY-1661
The two SSLExplorers can likely be merged at some point but they have diverged at the moment.
> [ELY-1661] Port the SNI SSLContext into the WildFly Elytron project.

- pom.xml
Jira: https://issues.jboss.org/browse/ELY-1698
> [ELY-1698] Add profile for skipping default-tests

- src/main/java/org/wildfly/security/http/HttpAuthenticator.java
- src/main/java/org/wildfly/security/http/impl/SpnegoAuthenticationMechanism.java
JBEAP(7.1.z): https://issues.jboss.org/browse/JBEAP-4114
Upstream: https://issues.jboss.org/browse/ELY-1547
JBEAP(7.1.z): https://issues.jboss.org/browse/JBEAP-14188
Upstream: https://issues.jboss.org/browse/ELY-1549
Upstream PR: wildfly-security/wildfly-elytron#1116
> [ELY-1547][ELY-1549] SPNEGO - sending negState=rejected token

- src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
JBEAP (7.1.z): https://issues.jboss.org/browse/JBEAP-2204
Upstream: https://issues.jboss.org/browse/ELY-396
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/970
> [ELY-396] CipherSuiteSelector parsing revised

- pom.xml
- src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
- src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
https://issues.jboss.org/browse/ELY-1693
This PR also incorporates https://github.com/wildfly-security/wildfly-elytron/pull/1211:
https://issues.jboss.org/browse/ELY-1702
https://issues.jboss.org/browse/ELY-1699
> [ELY-1693] Update AcmeClientSpi to make use of POST-as-GET requests instead of GET requests and update tests accordingly

- src/main/java/org/wildfly/security/ssl/SSLUtils.java
https://issues.jboss.org/browse/ELY-1663
> [ELY-1663] Ensure the map of preferred providers by algorithm is case insensitive in SSLUtils#createSslContextFactory

- pom.xml
- src/main/java/org/wildfly/security/_private/ElytronMessages.java
- src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
- src/main/java/org/wildfly/security/keystore/KeyStoreUtil.java
- src/main/resources/schema/elytron-client-1_3.xsd
- src/test/java/org/wildfly/security/keystore/AtomicLoadKeyStoreTest.java
- src/test/java/org/wildfly/security/keystore/KeyStoreUtilTest.java
- src/test/resources/schema/wrapped-elytron-client-1_3.xsd
https://issues.jboss.org/browse/ELY-1650
https://issues.jboss.org/browse/ELY-1696
> [ELY-1650][ELY-1696] Automatic detection of file based KeyStore types, Dead code removal

- wildfly-elytron/pom.xml
https://issues.jboss.org/browse/ELY-1753
> [ELY-1753] Ensure the sources jar is produced for org.wildfly.security.wildfly-elytron

- src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
Jira: 
https://issues.jboss.org/browse/ELY-1691
> [ELY-1691] Add test if Mechansim Database cover cipher suites from JDK

- src/test/java/org/wildfly/security/ldap/PrincipalMappingSuiteChild.java
Jira: https://issues.jboss.org/browse/ELY-1703
> [ELY-1703] Intermittent failure of PrincipalMappingSuiteChild#testDnToDnVerify

- tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
- tool/src/test/java/org/wildfly/security/tool/FileSystemRealmCommandTest.java
- tool/src/test/java/org/wildfly/security/tool/MaskCommandTest.java
Jira: https://issues.jboss.org/browse/ELY-1756
Jira: https://issues.jboss.org/browse/ELY-1757
> [ELY-1756] [ELY-1757] Fix Elytron-Tool Test Failures on Windows

- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/ElytronMessages.java
- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/UserPasswordPasswordUtil.java
- credential/base/src/main/java/org/wildfly/security/credential/_private/ElytronMessages.java
- credential/base/src/main/java/org/wildfly/security/password/util/ModularCrypt.java
- credential/base/src/test/java/org/wildfly/security/password/util/PasswordBasedEncryptionUtilTest.java
- tests/base/src/test/java/org/wildfly/security/apacheds/CryptCompatibilityTest.java
- tests/base/src/test/java/org/wildfly/security/util/PasswordBasedEncryptionUtilTest.java
Jira: https://issues.jboss.org/browse/ELY-1760
> [ELY-1760] Make ModularCrypt alphabets package private

- pom.xml
https://issues.jboss.org/browse/ELY-1767
> [ELY-1767] Upgrade org.apache.commons.commons-lang3 to 3.8

- mechanism/base/src/main/java/org/wildfly/security/mechanism/MechanismUtil.java
Jira: https://issues.jboss.org/browse/ELY-1763
> [ELY-1763] Return deprecated Public API 'org.wildfly.security.mechanism.MechanismUtil' class

- password/impl/src/main/java/org/wildfly/security/password/impl/PasswordFactorySpiImpl.java
https://issues.jboss.org/browse/ELY-1769
> [ELY-1769] Add missing SCRAM password algorithms for translation.

- base/src/main/java/org/wildfly/security/WildFlyElytronHttpBearerProvider.java
https://issues.jboss.org/browse/ELY-1774
> [ELY-1774] Reference the factory instead of the mechanism directly.

- pom.xml
- wildfly-elytron/pom.xml
https://issues.jboss.org/browse/ELY-1779
> [ELY-1779] Make the package 'org.wildfly.security.password.util' public API.

- pom.xml
https://issues.jboss.org/browse/ELY-1786
https://issues.jboss.org/browse/ELY-1787
> [ELY-1786] / [ELY-1787] Logging and WildFly Common Component Upgrades

- tests/base/pom.xml
Jira: https://issues.jboss.org/browse/ELY-1789
> [ELY-1789] Add a global property for the Maven XML plugin in the tests module

- .travis.yml
- pom.xml
Jira: https://issues.jboss.org/browse/ELY-1788
> [ELY-1788] Update minimum JDK build version to 11

- audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
https://issues.jboss.org/browse/ELY-1793
> [ELY-1793] Cache JsonProvider

- http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
https://issues.jboss.org/browse/ELY-1794
> [ELY-1794] Check if we have a FORM submission before attempting to restore an identity.

- tool/pom.xml
https://issues.jboss.org/browse/ELY-1790
> [ELY-1790] Include 'wildfly-elytron-password-impl' in the Tool distribution.

- .travis-settings.xml
- .travis.yml
- pom.xml
https://issues.jboss.org/browse/ELY-1798
https://issues.jboss.org/browse/ELY-1799
https://issues.jboss.org/browse/ELY-1801
> [ELY-1798] / [ELY-1799] / [ELY-1801] JBoss Parent and Checkstyle Config Upgrades.

- auth/client/src/main/java/org/wildfly/security/auth/util/ElytronAuthenticator.java
- auth/client/src/main/java/org/wildfly/security/auth/util/ElytronMessages2.java
https://issues.jboss.org/browse/ELY-1807
> [ELY-1807] Ensure we don't have two ElytronMessages definitions with the same fully qualified name.

- tests/common/pom.xml
https://issues.jboss.org/browse/ELY-1816
> [ELY-1816] generate sources for wildfly-elytron-tests-common tests.jar

- asn1/src/main/java/org/wildfly/security/asn1/DERDecoder.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
- keystore/src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
https://issues.jboss.org/browse/ELY-613
> [ELY-613] Changed some inner classes to be static nested classes

- base/src/main/java/org/wildfly/security/WildFlyElytronBaseProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpBasicProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpBearerProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpClientCertProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpDigestProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpFormProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronHttpSpnegoProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
- http/basic/src/main/java/org/wildfly/security/http/basic/WildFlyElytronHttpBasicProvider.java
- http/bearer/src/main/java/org/wildfly/security/http/bearer/WildFlyElytronHttpBearerProvider.java
- http/cert/src/main/java/org/wildfly/security/http/cert/WildFlyElytronHttpClientCertProvider.java
- http/digest/src/main/java/org/wildfly/security/http/digest/WildFlyElytronHttpDigestProvider.java
- http/form/src/main/java/org/wildfly/security/http/form/WildFlyElytronHttpFormProvider.java
- http/spnego/src/main/java/org/wildfly/security/http/spnego/WildFlyElytronHttpSpnegoProvider.java
- http/util/src/main/java/org/wildfly/security/http/util/SecurityProviderServerMechanismFactory.java
- provider/util/src/main/java/org/wildfly/security/provider/util/ProviderUtil.java
- sasl/anonymous/src/main/java/org/wildfly/security/sasl/anonymous/WildFlyElytronSaslAnonymousProvider.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/WildFlyElytronSaslDigestProvider.java
- sasl/entity/src/main/java/org/wildfly/security/sasl/entity/WildFlyElytronSaslEntityProvider.java
- sasl/external/src/main/java/org/wildfly/security/sasl/external/WildFlyElytronSaslExternalProvider.java
- sasl/gs2/src/main/java/org/wildfly/security/sasl/gs2/WildFlyElytronSaslGs2Provider.java
- sasl/gssapi/src/main/java/org/wildfly/security/sasl/gssapi/WildFlyElytronSaslGssapiProvider.java
- sasl/oauth2/src/main/java/org/wildfly/security/sasl/oauth2/WildFlyElytronSaslOAuth2Provider.java
- sasl/otp/src/main/java/org/wildfly/security/sasl/otp/WildFlyElytronSaslOTPProvider.java
- sasl/plain/src/main/java/org/wildfly/security/sasl/plain/WildFlyElytronSaslPlainProvider.java
- sasl/scram/src/main/java/org/wildfly/security/sasl/scram/WildFlyElytronSaslScramProvider.java
A set of related performance optimisations, collectively they reduce contention during HTTP authentication where high demand was placed on the Wildfly Elytron Provider.
https://issues.jboss.org/browse/ELY-1818
https://issues.jboss.org/browse/ELY-1820
https://issues.jboss.org/browse/ELY-1823
https://issues.jboss.org/browse/ELY-1824
> [ELY-1818] / [ELY-1820] / [ELY-1821] / [ELY-1823] / [ELY-1824] Performance optimisations

- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- pom.xml
- ssl/src/main/java/org/wildfly/security/ssl/ElytronMessages.java
- ssl/src/main/java/org/wildfly/security/ssl/X509CRLExtendedTrustManager.java
- ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
- tests/base/pom.xml
- tests/base/src/main/resources/schema/elytron-client-1_4.xsd
- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
- tests/base/src/test/java/org/wildfly/security/ssl/TestingOcspServer.java
- tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-db.properties
- tests/base/src/test/resources/org/wildfly/security/ssl/ocsp-responder.xml
- tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_1.xml
- tests/base/src/test/resources/schema/wrapped-elytron-client-1_4.xsd
https://issues.jboss.org/browse/ELY-1617
> [ELY-1617] Support SSL Certificate revocation using OCSP

- auth/server/base/src/main/java/org/wildfly/security/auth/callback/EvidenceDecodePrincipalCallback.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/EvidenceDecoder.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/ModifiableSecurityRealm.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityRealm.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- credential/base/src/main/java/org/wildfly/security/evidence/Evidence.java
- credential/base/src/main/java/org/wildfly/security/evidence/X509PeerCertificateChainEvidence.java
- http/cert/src/main/java/org/wildfly/security/http/cert/ClientCertAuthenticationMechanism.java
- sasl/base/src/main/java/org/wildfly/security/sasl/util/TrustManagerSaslServerFactory.java
- sasl/entity/src/main/java/org/wildfly/security/sasl/entity/EntitySaslServer.java
- tests/base/src/test/java/org/wildfly/security/x500/X509PeerCertificateChainEvidenceDecoderTest.java
- x500/principal/src/main/java/org/wildfly/security/x500/principal/X500SubjectEvidenceDecoder.java
- x500/principal/src/main/java/org/wildfly/security/x500/principal/X509SubjectAltNameEvidenceDecoder.java
https://issues.jboss.org/browse/ELY-1800
> [ELY-1800] Add the ability to decode the Principal from Evidence

- pom.xml
https://issues.jboss.org/browse/ELY-1844
> [ELY-1844] Upgrade Apache commons-cli to version 1.4

- base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
https://issues.jboss.org/browse/ELY-1847
>  [ELY-1847] Use correct class name for 'BearerMechanismFactory'.

- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/WildFlyElytronSaslDigestProvider.java
https://issues.jboss.org/browse/ELY-1849
> [ELY-1849] Ensure all the 'digest' password types are available from the provider.

- auth/server/deprecated/src/main/java/org/wildfly/security/auth/server/HttpAuthenticationFactory.java
- auth/server/http/src/main/java/org/wildfly/security/auth/server/http/HttpAuthenticationFactory.java
- http/base/src/main/java/org/wildfly/security/http/HttpServerAuthenticationMechanismFactory.java
- http/digest/src/main/java/org/wildfly/security/http/digest/DigestMechanismFactory.java
- http/digest/src/main/java/org/wildfly/security/http/digest/NonceManager.java
https://issues.jboss.org/browse/ELY-1843
> [ELY-1843] - Adding ability to specify custom ScheduledExecutorService and to shut down ScheduledExecutorService in NonceManager

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateAttributes.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateAttributesTest.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmTest.java
- auth/server/base/src/main/java/org/wildfly/security/authz/AuthorizationIdentity.java
https://issues.jboss.org/browse/ELY-1804
> [ELY-1804] Add support for aggregating attributes from multiple security realms.

- ELY_Messages.txt
https://issues.jboss.org/browse/ELY-1856
> [ELY-1856] Update a message ID for wildly-elytron-mechanism-gssapi in ELY_Messages.txt

- ELY_Messages.txt
- audit/pom.xml
- audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
- audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
- audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
- audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
- auth/server/base/pom.xml
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/Rfc3164SyslogEvent.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/Rfc5424SyslogEvent.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SyslogAuditEvent.java
- pom.xml
- tests/base/pom.xml
- tests/base/src/test/java/org/wildfly/security/audit/JsonSecurityEventFormatterTest.java
- tests/base/src/test/java/org/wildfly/security/audit/SimpleSyslogServer.java
- tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
https://issues.jboss.org/browse/ELY-1712
> [ELY-1712] Enhanced Audit Logging - RFC Support and Configuring Reconnects

- jacc/src/main/java/org/wildfly/security/authz/jacc/JaccDelegatingPolicy.java
https://issues.jboss.org/browse/ELY-1873
> [ELY-1873] Allow for modifications to the permissions in the returned PermissionCollection.

- manager/base/src/main/java/org/wildfly/security/manager/JDKSpecific.java
- manager/base/src/main/java/org/wildfly/security/manager/StackInspector.java
- manager/base/src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java
- manager/base/src/main/java9/org/wildfly/security/manager/JDKSpecific.java
https://issues.jboss.org/browse/ELY-1877
> [ELY-1877] Correct JDKSpecific handling of the call stack.

- ELY_Messages.txt
- credential/store/src/main/java/org/wildfly/security/credential/store/_private/ElytronMessages.java
- credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- credential/store/src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
Port changes from https://github.com/wildfly-security/wildfly-elytron/pull/1330 to 1.x
> [ELY-1872] elytron-tool.sh usage with symbolic links

- pom.xml
Upgrades for various micro increments of components: -
https://issues.jboss.org/browse/ELY-1885
> [ELY-1885] Component Upgrades

- pom.xml
https://issues.jboss.org/browse/ELY-1886
https://issues.jboss.org/browse/ELY-1887
> [ELY-1886][ELY-1887] Switch to the JBoss / Jakarta Fork for JACC and JASPI

- auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/MechanismConfiguration.java
- auth/server/base/src/main/java/org/wildfly/security/credential/source/CredentialSource.java
https://issues.jboss.org/browse/ELY-1898
> [ELY-1898] Update usages of SecurityFactory<Credential> to SecurityFactory<? extends Credential>

- pom.xml
https://issues.jboss.org/browse/ELY-1901
> [ELY-1901] Upgrade JBoss Modules to 1.9.2.Final

- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
https://issues.jboss.org/browse/ELY-1905
> [ELY-1905] Refactor SSL Session validation in SSLAuthenticationTest

- audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
https://issues.jboss.org/browse/ELY-1908
> [ELY-1908] Typo in SimpleSecurityEventFormatter

- audit/src/main/java/org/wildfly/security/audit/JsonSecurityEventFormatter.java
- audit/src/main/java/org/wildfly/security/audit/SimpleSecurityEventFormatter.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityRealmUnavailableEvent.java
https://issues.jboss.org/browse/ELY-1903
> [ELY-1903] Emit SecurityEvent when RealmUnavailableException is thrown

- pom.xml
https://issues.redhat.com/browse/ELY-1913
> [ELY-1913] Upgrade nimbus-jose-jwt to 8.2.1.

- pom.xml
https://issues.redhat.com/browse/ELY-1914
> [ELY-1914] Upgrade org.jboss.logging tools to 2.2.1.Final

- ELY_Messages.txt
- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronMessages.java
- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- auth/client/src/main/resources/schema/elytron-client-1_5.xsd
- auth/client/src/test/java/org/wildfly/security/auth/client/ElytronXmlParserTest.java
- auth/client/src/test/resources/org/wildfly/security/auth/client/test-wildfly-config-v1_5.xml
- ssl/src/main/java/org/wildfly/security/ssl/CipherSuiteSelector.java
- ssl/src/main/java/org/wildfly/security/ssl/ElytronMessages.java
- ssl/src/main/java/org/wildfly/security/ssl/MechanismDatabase.java
- ssl/src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
- ssl/src/main/java/org/wildfly/security/ssl/SSLExplorer.java
- ssl/src/main/java/org/wildfly/security/ssl/TLS13MechanismDatabase.properties
- ssl/src/test/java/org/wildfly/security/ssl/CipherSuiteSelectorTest.java
- ssl/src/test/java/org/wildfly/security/ssl/MechanismDatabaseTest.java
- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
- tests/base/src/test/java/org/wildfly/security/ssl/TLS13AuthenticationTest.java
- tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_5.xml
https://issues.jboss.org/browse/ELY-1706
https://issues.jboss.org/browse/ELY-1754
>  [ELY-1706] Add support for TLS 1.3 cipher suites

- pom.xml
https://issues.redhat.com/browse/ELY-1920
> [ELY-1920] Upgrade SmallRye JWT to 2.0.12

- auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
https://issues.redhat.com/browse/ELY-1923
> [ELY-1923] Ensure webServicesProperties is not `null` before accessing.

- pom.xml
- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
https://issues.redhat.com/browse/ELY-1922
> [ELY-1922] Upgrade BouncyCastle to 1.64

- ELY_Messages.txt
- asn1/src/main/java/org/wildfly/security/asn1/DERDecoder.java
- auth/realm/base/pom.xml
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FileSystemSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/JaasSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/LegacyPropertiesSecurityRealm.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmEvidenceTest.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateRealmTest.java
- auth/server/base/pom.xml
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/event/SecurityEventVisitor.java
- auth/server/sasl/src/main/java/org/wildfly/security/auth/server/sasl/SaslAuthenticationFactory.java
- keystore/src/main/java/org/wildfly/security/keystore/AtomicLoadKeyStore.java
- sasl/base/src/main/java/org/wildfly/security/sasl/util/AuthenticationTimeoutSaslServerFactory.java
- tests/base/src/test/java/org/wildfly/security/sasl/test/SaslAuthenticationTimeoutTest.java
- tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
Double checking the status of master some fixes are presently missing, these fixes are already approved so don't need a review I just want to run through CI and will then merge.
> Missing commits from 1.x

- pom.xml
https://issues.redhat.com/browse/ELY-1928
> [ELY-1928] Update WildFly Common to 1.5.3.Final

- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
Issue: https://issues.jboss.org/browse/ELY-1890
> [ELY-1890] Keep file permissions when modifying an existing credential store

- jwt/pom.xml
- jwt/src/main/java/org/wildfly/security/mp/jwt/JWTCDIExtension.java
- jwt/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- pom.xml
- wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-1935
> [ELY-1935] Backport MicroProfile JWT Module

- src/main/java/org/wildfly/security/auth/realm/ldap/DirectEvidenceVerifier.java
Issue: https://issues.redhat.com/browse/ELY-1940
This is the fix targeting `1.6.x` branch which is used by `EAP 7.2.z`.
> [ELY-1940] Elytron LDAP Squashes Authentication Exception

- .travis.yml
https://issues.redhat.com/browse/ELY-1941
> [ELY-1941] Update the Travis configuration to use OpenJDK 8

- pom.xml
https://issues.redhat.com/browse/ELY-1943
> [ELY-1943] Upgrade WildFly Common 1.5.4.Final

- _data/navigation.yml
- _layouts/community.html
- _posts/2020-03-18-new-security-features-in-wildfly-19.adoc
- _posts/2020-03-18-tls-13-with-wildfly.adoc
- _posts/2020-03-18-ws-elytron-client-integration.adoc
We'll hold off on merging this until WildFly 19 is actually released.
> Add an overview blog post for WildFly 19 and a blog post on TLS 1.3

- wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-1944
> [ELY-1944] Exclude the JWT module from the `wildfly-elytron` module.

- http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
- http/base/src/main/java/org/wildfly/security/http/HttpScope.java
- http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
- http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
https://issues.redhat.com/browse/ELY-1945
> [ELY-1945] Change Session ID on authentication.

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/AggregateAttributesTest.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityIdentity.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- auth/server/base/src/main/java/org/wildfly/security/authz/AggregateAttributes.java
- auth/server/base/src/main/java/org/wildfly/security/authz/AuthorizationIdentity.java
- auth/server/base/src/main/java/org/wildfly/security/authz/RoleDecoder.java
- auth/server/base/src/main/java/org/wildfly/security/authz/SourceAddressRoleDecoder.java
- auth/server/base/src/test/java/org/wildfly/security/authz/RoleDecoderTest.java
- tests/base/src/test/java/org/wildfly/security/auth/server/SourceAddressRuntimeAttributesTest.java
https://issues.jboss.org/browse/ELY-1894
> [ELY-1894] Add the ability to make use of the IP address of a remote client when making authorization decisions

- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
- tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
- tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
https://issues.redhat.com/browse/ELY-1838
> [ELY-1838] Differentiate actions and parameters

- pom.xml
https://issues.redhat.com/browse/ELY-1931
https://github.com/smallrye/smallrye-jwt/compare/2.0.12...2.0.13
> [ELY-1931] Upgrade to SmallRye JWT 2.0.13

- audit/src/main/java/org/wildfly/security/audit/SyslogAuditEndpoint.java
- auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/CredentialLoader.java
- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/EvidenceVerifier.java
- auth/server/base/src/main/java/org/wildfly/security/authz/MappedRoleMapper.java
- keystore/src/main/java/org/wildfly/security/keystore/AliasFilter.java
- password/impl/src/main/java/org/wildfly/security/password/impl/BCryptPasswordImpl.java
- password/impl/src/main/java/org/wildfly/security/password/impl/ScramDigestPasswordImpl.java
- pom.xml
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslClient.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- sasl/gs2/src/main/java/org/wildfly/security/sasl/gs2/Gs2SaslClient.java
- sasl/otp/src/main/java/org/wildfly/security/sasl/otp/OTPSaslClient.java
- x500/cert/base/src/main/java/org/wildfly/security/x500/cert/InhibitAnyPolicyExtension.java
- x500/cert/base/src/main/java/org/wildfly/security/x500/cert/NameConstraintsExtension.java
- x500/cert/base/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java
- x500/principal/src/main/java/org/wildfly/security/x500/principal/X509SubjectAltNameEvidenceDecoder.java
https://issues.redhat.com/browse/ELY-1960
> [ELY-1960] Correct Javadoc generation warnings and failure.

- pom.xml
https://issues.redhat.com/browse/ELY-1961
> [ELY-1961] Upgrade JBoss LogManager to 2.1.15.Final

- pom.xml
https://issues.redhat.com/browse/ELY-1962
> [ELY-1962] Upgrade JBoss Threads to 2.3.4.Final

- ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
- ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
- ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
- tests/base/src/test/java/org/wildfly/security/ssl/SSLConfiguratorImplTest.java
> [ELY-1952] SSLConfigurator ignores some of the SSLParameters passed in

- ELY_Messages.txt
- auth/server/base/src/main/java/org/wildfly/security/auth/server/_private/ElytronMessages.java
- auth/server/base/src/main/java/org/wildfly/security/authz/RegexRoleMapper.java
- auth/server/base/src/main/java/org/wildfly/security/authz/RegexRoles.java
- auth/server/base/src/test/java/org/wildfly/security/authz/RegexRoleMapperTest.java
https://issues.jboss.org/browse/ELY-1909
> [ELY-1909] Using regex for role in Elytron

- x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/Acme.java
- x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
- x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/ElytronMessages.java
- x500/cert/acme/src/test/java/org/wildfly/security/x500/cert/acme/AcmeClientSpiTest.java
https://issues.redhat.com/browse/ELY-1968
> [ELY-1968] Update error message returned by AcmeClientSpi#getLocation

- pom.xml
- ssl/pom.xml
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
- ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
https://issues.redhat.com/browse/ELY-1979
> [ELY-1979] Additional methods as added for JEPS-244

- pom.xml
- ssl/pom.xml
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
- ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
- ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
- ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
https://issues.redhat.com/browse/ELY-1979
> [ELY-1979] Convert ALPN Method Access to Java 9 and boyond.

- ssl/pom.xml
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLEngine.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLParameters.java
- ssl/src/main/java/org/wildfly/security/ssl/AbstractDelegatingSSLSocket.java
- ssl/src/main/java/org/wildfly/security/ssl/JDKSpecific.java
- ssl/src/main/java/org/wildfly/security/ssl/SSLConfiguratorImpl.java
- ssl/src/main/java/org/wildfly/security/ssl/SelectingServerSSLEngine.java
- ssl/src/main/java9/org/wildfly/security/ssl/JDKSpecific.java
- tests/base/src/test/java/org/wildfly/security/ssl/SSLConfiguratorImplTest.java
Issue (7.3.z): https://issues.redhat.com/browse/JBEAP-19640
Upstream issue: https://issues.redhat.com/browse/ELY-1979
Issue(7.3.z): https://issues.redhat.com/browse/JBEAP-19641
Upstream issue: https://issues.redhat.com/browse/ELY-1981
Upstream PRs: https://github.com/wildfly-security/wildfly-elytron/pull/1404 and https://github.com/wildfly-security/wildfly-elytron/pull/1406
Note: https://issues.redhat.com/browse/ELY-1952 is included because the above PR depends on the changes from https://github.com/wildfly-security/wildfly-elytron/pull/1384
> Backport ELY-1979, ELY-1981 and ELY-1952

- auth/client/src/main/java/org/wildfly/security/auth/client/CredentialStoreFactory.java
- credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- tests/base/src/test/java/org/wildfly/security/auth/client/CredentialStoreSaslAuthenticationTest.java
- tests/base/src/test/java/org/wildfly/security/sasl/test/SaslServerBuilder.java
- tests/base/src/test/resources/org/wildfly/security/auth/client/wildfly-credential-sasl-config.xml
https://issues.redhat.com/browse/ELY-1976
> [ELY-1976] Elytron provider not being used with credential store and SASL authentication on the Client Side

- pom.xml
https://issues.redhat.com/browse/ELY-1997
> [ELY-1997] Upgrade jboss-logmanager to 2.1.16.Final

- pom.xml
https://issues.redhat.com/browse/ELY-1999
> [ELY-1999] Upgrade JBoss Threads to 2.3.5.Final

- ssl/src/main/java/org/wildfly/security/ssl/SSLContextBuilder.java
https://issues.redhat.com/browse/ELY-1982
> [ELY-1982] TLS with BCJSSE Provider does not work

- sasl/gssapi/src/main/java/org/wildfly/security/sasl/gssapi/GssapiClient.java
https://issues.redhat.com/browse/ELY-2000
> [ELY-2000] Additional TRACE logging where GssCredential obtained from CredentialCallback.

- http/util/src/main/java/org/wildfly/security/http/util/SocketAddressCallbackServerMechanismFactory.java
https://issues.redhat.com/browse/ELY-1984
> [ELY-1984] Add a wrapper HttpServerAuthenticationMechanismFactory that sets the peer address using the current authentication request

- pom.xml
https://issues.redhat.com/browse/ELY-2003
> [ELY-2003] Upgrading jboss-logmanager to 2.1.17.Final

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/ServerAuthenticationContext.java
- tests/base/src/test/java/org/wildfly/security/auth/realm/DistributedSecurityRealmTest.java
https://issues.redhat.com/browse/ELY-1932
> [ELY-1932] Support for multiple realms - Distributed Identities

- pom.xml
https://issues.redhat.com/browse/ELY-2011
> [ELY-2011] Upgrade jboss-threads to 2.3.6.Final

- pom.xml
https://issues.redhat.com/browse/ELY-2013
> [ELY-2013] Upgrade JBoss Threads to 2.4.0.Final

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/ElytronMessages.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FailoverSecurityRealm.java
- auth/realm/base/src/test/java/org/wildfly/security/auth/realm/FailoverRealmTest.java
- auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
- auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/_private/ElytronMessages.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/_private/ElytronMessages.java
- permission/src/main/java/org/wildfly/security/permission/ElytronPermission.java
https://issues.jboss.org/browse/ELY-1902
> [ELY-1902] Support for multiple security realms - Failover

- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/SimpleDirContextFactoryBuilder.java
https://issues.redhat.com/browse/ELY-2029
> [ELY-2029] Checking String equality using != in SimpleDirContextFactoryBuilder

- auth/jaspi/src/main/java/org/wildfly/security/auth/jaspi/impl/JaspiAuthenticationContext.java
https://issues.redhat.com/browse/ELY-2028
> [ELY-2028] Resource leak in JaspiAuthenticationContext

- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.redhat.com/browse/ELY-2025
> [ELY-2025] Resource leak in ElytronXmlParser.

- tool/src/main/java/org/wildfly/security/tool/FileSystemRealmCommand.java
https://issues.redhat.com/browse/ELY-2030
> [ELY-2030] Possible NullPointerException in FileSystemRealmCommand

- pom.xml
https://issues.redhat.com/browse/ELY-1707
> [ELY-1707] Running tests on JDK11 for branch 1.6.x

- auth/server/base/src/main/java/org/wildfly/security/auth/server/IdentityCredentials.java
- tests/base/src/test/java/org/wildfly/security/auth/server/IdentityCredentialsTest.java
Issue: https://issues.redhat.com/browse/JBEAP-20426
Upstream issue: https://issues.redhat.com/browse/ELY-2031
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1456
> ELY-2031 Allow loose credential matches in IdentityCredentials.Many

- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- tests/base/src/test/java/org/wildfly/security/sasl/digest/CompatibilityServerTest.java
Issue: https://issues.redhat.com/browse/JBEAP-20425
Upstream issue: https://issues.redhat.com/browse/ELY-2036
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1459
> ELY-2036 Support DigestSaslServer.getNegotiatedProperty() for QOP and STRENGTH

- auth/util/src/main/java/org/wildfly/security/auth/util/CaseNameRewriter.java
- tests/base/src/test/java/org/wildfly/security/auth/server/CaseNameRewriterTest.java
https://issues.redhat.com/browse/ELY-1987
> [ELY-1987] Add the ability to adjust the case of a user name using an Elytron principal transformer

- manager/base/src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java
- manager/base/src/main/java/org/wildfly/security/manager/_private/SecurityMessages.java
Fixes [ELY-2049](https://issues.redhat.com/browse/ELY-2049)
> ELY-2049 Add WildFly SecurityManager findAccessDenial trace capability

- ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
https://issues.redhat.com/browse/ELY-2057
https://issues.redhat.com/projects/ELY/issues/ELY-2058
> [ELY-2057] No acceptedIssuers sent when CRLs are configured

- credential/base/src/main/java/org/wildfly/security/password/interfaces/MaskedPassword.java
- password/impl/src/test/java/org/wildfly/security/password/impl/MaskedPasswordTest.java
https://issues.redhat.com/browse/ELY-2063
> [ELY-2063] Masked password interface contains 8 algorithms unavailable on IBM JDK 8

- pom.xml
Fixes [ELY-2050](https://issues.redhat.com/browse/ELY-2050)
> ELY-2050 Update bouncycastle to 1.67

- _data/navigation.yml
- _layouts/community.html
- _posts/2021-01-14-auto-self-signed-certificate-generation.adoc
I'll update the date in the title and in the file itself once WildFly 22 is released.
> Add a blog post on automatic self-signed certificate generation

- http/util/src/main/java/org/wildfly/security/http/util/AggregateServerMechanismFactory.java
https://issues.redhat.com/browse/ELY-2043
> [ELY-2043] Improving http-server-mechanism-factory logging

- pom.xml
- tests/base/src/test/java/org/wildfly/security/apacheds/LdapService.java
- tests/base/src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
- tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
- tests/base/src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
- tests/base/src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java
https://issues.redhat.com/browse/ELY-2071
https://issues.redhat.com/browse/ELY-2073
> [ELY-2071] Upgrade Apache DS to version AM26

- jwt/pom.xml
- pom.xml
https://issues.redhat.com/browse/ELY-2068
> [ELY-2068] Upgrade to MicroProfile JWT 1.2

- ELY_Messages.txt
- audit/src/main/java/org/wildfly/security/audit/ElytronMessages.java
- base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- credential/store/pom.xml
- credential/store/src/main/java/org/wildfly/security/credential/store/WildFlyElytronCredentialStoreProvider.java
- credential/store/src/main/java/org/wildfly/security/credential/store/_private/ElytronMessages.java
- credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
- credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
- encryption/pom.xml
- encryption/src/main/java/org/wildfly/security/encryption/CipherUtil.java
- encryption/src/main/java/org/wildfly/security/encryption/Common.java
- encryption/src/main/java/org/wildfly/security/encryption/ElytronMessages.java
- encryption/src/main/java/org/wildfly/security/encryption/SecretKeyUtil.java
- encryption/src/main/java/org/wildfly/security/encryption/package-info.java
- encryption/src/test/java/org/wildfly/security/encryption/CipherUtilTest.java
- encryption/src/test/java/org/wildfly/security/encryption/SecretKeyUtilTest.java
- pom.xml
- tests/base/src/test/java/org/wildfly/security/audit/SyslogAuditEndpointTest.java
- tool/pom.xml
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- tool/src/main/java/org/wildfly/security/tool/ElytronTool.java
- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
- tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
- tool/src/test/java/org/wildfly/security/tool/SecretKeyCommandTest.java
- wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-1842
https://issues.redhat.com/browse/ELY-2055
https://issues.redhat.com/browse/ELY-2081
https://issues.redhat.com/browse/ELY-2086
One point possibly still to visit is test cases for interactive input when using the tool and clear text values to be encrypted containing spaces being passed in to the tool.
> [ELY-1842] / [ELY-2055] / [ELY-2081] / [ELY-2086] SecretKey manipulation and encrypted expression support.

- credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- credential/store/src/test/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStoreTest.java
https://issues.redhat.com/browse/ELY-2092
> [ELY-2092] Removal of an entry of a specific type is corrupting the cache of entries.

- encryption/src/main/java/org/wildfly/security/encryption/CipherUtil.java
- encryption/src/main/java/org/wildfly/security/encryption/ElytronMessages.java
- encryption/src/main/java/org/wildfly/security/encryption/SecretKeyUtil.java
https://issues.redhat.com/browse/ELY-2091
> [ELY-2091] Wrap any error reported decoding the Base64 token.

- README.md
https://issues.redhat.com/browse/ELY-1783
> [ELY-1783] Update getting started guide in README

- credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
- credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/test/java/org/wildfly/security/tool/SecretKeyCommandTest.java
https://issues.redhat.com/browse/ELY-2093
https://issues.redhat.com/browse/ELY-2094
https://issues.redhat.com/browse/ELY-2095
> [ELY-2093] / [ELY-2094] / [ELY-2095] Additional tests and minor fixes.

- wildfly-elytron/pom.xml
https://issues.redhat.com/browse/ELY-2099
> [ELY-2099] Ensure only WildFly Elytron classes are included in the shaded JAR

- _data/navigation.yml
- _layouts/community.html
- _posts/2021-03-19-automatic-registration-of-client-side-jvm-wide-default-sslcontext.adoc
- _posts/2021-03-19-new-security-features-in-wildfly-23.adoc
- _posts/2021-03-19-new-ssl-features.adoc
- _posts/2021-03-19-normalization-of-EJB-principal-propagation.adoc
- _posts/2021-03-19-sslcontext-delegation-to-alternate-instances-based-on-peer.adoc
- _posts/2021-03-19-upcoming-hash-encodings.adoc
This is an aggregation of the following PRs and includes a blog post that highlights the features that went into WildFly 23 and also the features that are in progress:
https://github.com/wildfly-security/wildfly-elytron/pull/1497
https://github.com/wildfly-security/wildfly-elytron/pull/1498
https://github.com/wildfly-security/wildfly-elytron/pull/1499
https://github.com/wildfly-security/wildfly-elytron/pull/1501
> Aggregate PR

- mechanism/http/src/main/java/org/wildfly/security/mechanism/http/UsernamePasswordAuthenticationMechanism.java
- tests/base/src/test/java/org/wildfly/security/http/impl/AbstractBaseHttpTest.java
Issue: https://issues.redhat.com/browse/ELY-2108
Just moving the creation of the `ClearPassword` before the callback that is destroying the password. The password is destroyed if not needed for the credential at the end.
Finally I saw how to test this in the test-suite. The callback is now destroying the evidence in `HttpAuthenticatorTest` (like ldap realm is doing) and the password in the `IdentityCredentialCallback` is checked to be OK.
> [ELY-2108] Subject private credentials have zeroes when passed to elytron-enabled datasource

- base/src/main/java/org/wildfly/security/WildFlyElytronBaseProvider.java
- base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
https://issues.redhat.com/browse/ELY-2115
> [ELY-2115] Use a single list of masked password algorithms as the list was out of sync across four locations.

- ELY_Messages.txt
- http/base/src/main/java/org/wildfly/security/http/HttpConstants.java
- http/form/src/main/java/org/wildfly/security/http/form/ElytronMessages.java
- http/form/src/main/java/org/wildfly/security/http/form/FormAuthenticationMechanism.java
- http/form/src/main/java/org/wildfly/security/http/form/FormMechanismFactory.java
- http/spnego/src/main/java/org/wildfly/security/http/spnego/ElytronMessages.java
- http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoAuthenticationMechanism.java
- http/spnego/src/main/java/org/wildfly/security/http/spnego/SpnegoMechanismFactory.java
https://issues.redhat.com/browse/ELY-2113
> [ELY-2113] Add a configuration property to make it possible to disable changing the session ID after authentication.

- pom.xml
https://issues.redhat.com/browse/ELY-2126
> [ELY-2126] Upgrade to smallrye-jwt 3.1.1

- pom.xml
- tests/base/src/test/java/org/wildfly/security/apacheds/LdapService.java
- tests/base/src/test/java/org/wildfly/security/credential/store/KeystorePasswordStoreTest.java
- tests/base/src/test/java/org/wildfly/security/ldap/DirContextFactoryRule.java
- tests/base/src/test/java/org/wildfly/security/ldap/ModifiabilitySuiteChild.java
- tests/base/src/test/java/org/wildfly/security/sasl/gssapi/TestKDC.java
https://issues.redhat.com/browse/ELY-2071
https://issues.redhat.com/browse/ELY-2073
Reverts commit ce1bfc7d5d1e4b0ac6a873546f36e54baf130e68 and be7f5e642170ad64603ecc542486cdd214da13ac
Revert caused by: https://issues.redhat.com/browse/WFCORE-5432
> [ELY-2071] / [ELY-2073] Revert ELY-2071 and ELY-2073

- credential/store/src/main/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStore.java
- credential/store/src/test/java/org/wildfly/security/credential/store/impl/PropertiesCredentialStoreTest.java
https://issues.redhat.com/browse/ELY-2123
> [ELY-2123] secret-key-credential-store does not make parent directories when being created

- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- auth/client/src/main/resources/schema/elytron-client-1_7.xsd
- ssl/src/main/java/org/wildfly/security/ssl/X509RevocationTrustManager.java
- tests/base/pom.xml
- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
- tests/base/src/test/resources/org/wildfly/security/ssl/wildfly-ssl-test-config-v1_7.xml
- tests/base/src/test/resources/schema/wrapped-elytron-client-1_7.xsd
- tests/common/src/test/java/org/wildfly/security/ssl/test/util/CAGenerationTool.java
https://issues.redhat.com/browse/ELY-2033
https://issues.redhat.com/browse/EAP7-1548
Includes commit to add version 1.7 of the Elytron Client Schema
https://issues.redhat.com/browse/ELY-2044
> [ELY-2033] Certificate Revocation Lists 

- http/sso/src/main/java/org/wildfly/security/http/util/sso/ImmutableSingleSignOn.java
- http/sso/src/main/java/org/wildfly/security/http/util/sso/SingleSignOnManager.java
https://issues.redhat.com/browse/ELY-2088
> [ELY-2088] Revert "[ELY-1626] Temporary commit to preserve API compatibility with the WildFly integration."

- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
https://issues.redhat.com/browse/ELY-2131
> [ELY-2131] Possible NullPointerException in JwtValidator when validating token with jku claim and SSL is not configured.

- getting-started-for-developers.adoc
Adding more information on getting started with Elytron Web and WildFly OpenSSL ahead of the Grace Hopper Open Source Event.
> Adding information about getting started with Elytron Web and WildFly OpenSSL

- pom.xml
https://issues.redhat.com/browse/ELY-2138
https://issues.redhat.com/browse/ELY-2139
> [ELY-2138] / [ELY-2139] Logging component upgrades.

- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
https://issues.redhat.com/browse/ELY-2140
> [ELY-2140] Elytron Tool: Mask command will fail when secret is not provided.

- tool/src/main/java/org/wildfly/security/tool/Command.java
https://issues.redhat.com/browse/ELY-2141
> [ELY-2141] Elytron Tool: Default platform encoding used in Command.

- pom.xml
https://issues.redhat.com/browse/ELY-2148
This was just a small maintenance release correcting Javadoc and the doucumentation:
https://github.com/eclipse/microprofile-jwt-auth/compare/1.2...1.2.1
> [ELY-2148] Upgrade MicroProfile JWT API to 1.2.1

- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
https://issues.redhat.com/browse/ELY-2132
> [ELY-2132] Cleanup dead code and unused variable in ElytronXmlParser.

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingModifiableSecurityRealm.java
- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/CachingSecurityRealm.java
https://issues.redhat.com/browse/ELY-2143
> [ELY-2143] The constructor of CachingSecurityRealm is not correctly implemented.

- auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
https://issues.redhat.com/browse/ELY-2137
> [ELY-2137] Possible NullPointerException in AuthenticationConfiguration

- mechanism/scram/src/main/java/org/wildfly/security/mechanism/scram/ScramServer.java
Issue: https://issues.redhat.com/browse/JBEAP-22222, https://issues.redhat.com/browse/JBEAP-22218
Upstream issue: https://issues.redhat.com/browse/ELY-2147
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1549
> [ELY-2147] Harden ScramServer against timing attacks

- credential/base/src/main/java/org/wildfly/security/password/spec/Encoding.java
https://issues.redhat.com/browse/ELY-2154
> [ELY-2154] Add javadoc for org.wildfly.security.password.spec.Encoding

- README.md
[ELY-2152] Add link to Elytron Website in Elytron README
https://issues.redhat.com/browse/ELY-2152?filter=12364234
> [ELY-2152] Add link to Elytron Website in Elytron README

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/AggregateSecurityRealm.java
[ELY-2157] Add parameter validation for AggregateSecurityRealm
> [ELY-2157] Add parameter validation for AggregateSecurityRealm

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/FailoverSecurityRealm.java
[ELY-2156] Add parameter validation for FailoverSecurityRealm
https://issues.redhat.com/browse/ELY-2156
> [ELY-2156] Add parameter validation for FailoverSecurityRealm

- tests/base/src/test/java/org/wildfly/security/ssl/SSLAuthenticationTest.java
https://issues.redhat.com/browse/ELY-2193
> [ELY-2193] Broken pipe exception thrown in testsuite

- sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
Fixes https://issues.redhat.com/browse/ELY-2196
> [ELY-2196] Null pointers should not be dereferenced

- ELY_Messages.txt
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/_private/ElytronMessages.java
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
- tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
Issue: https://issues.redhat.com/browse/ELY-2194
Merge of ELY-2194 into 1.x branch. I have just merged the 1.10.x branch with the fix into the 1.x branch, resolved the conflicts and sent the PR. I think this is what you want for maintenance issues. It is the first time I do this so if you see any issue let me know.
In 1.15.x there are no conflicts, plain 1.10.x fix can be applied without any issue. The conflicting change is ELY-2189 which is more or less recent.
PR for 1.10.x: https://github.com/wildfly-security/wildfly-elytron/pull/1562
> [ELY-2194] JWK implementation in JwkManager does not work properly on key rotation

- asn1/src/main/java/org/wildfly/security/asn1/ASN1.java
- audit/src/main/java/org/wildfly/security/audit/AuditEndpoint.java
- auth/client/src/main/java/org/wildfly/security/auth/client/AuthenticationConfiguration.java
- auth/client/src/main/java/org/wildfly/security/auth/client/ElytronXmlParser.java
- auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/JdbcSecurityRealm.java
- auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/DirContextFactory.java
- auth/server/base/src/main/java/org/wildfly/security/authz/MappedRoleMapper.java
- base/src/main/java/org/wildfly/security/WildFlyElytronProvider.java
- credential/source/impl/src/main/java/org/wildfly/security/credential/source/impl/CommandCredentialSource.java
- http/base/src/main/java/org/wildfly/security/http/HttpServerAuthenticationMechanism.java
- password/impl/src/main/java/org/wildfly/security/password/impl/SunUnixMD5CryptPasswordImpl.java
- sasl/base/src/main/java/org/wildfly/security/sasl/SaslMechanismSelector.java
- sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslClient.java
- sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslParticipant.java
- sasl/base/src/main/java/org/wildfly/security/sasl/util/AbstractSaslServer.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/AbstractDigestMechanism.java
- sasl/digest/src/main/java/org/wildfly/security/sasl/digest/DigestSaslServer.java
- sasl/entity/src/main/java/org/wildfly/security/sasl/entity/EntityUtil.java
- sasl/otp/src/main/java/org/wildfly/security/sasl/otp/OTPUtil.java
- ssl/src/main/java/org/wildfly/security/ssl/SNISSLExplorer.java
- ssl/src/main/java/org/wildfly/security/ssl/SSLExplorer.java
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
Fixes https://issues.redhat.com/browse/ELY-2198
> [ELY-2198] Remove old unused private code

- auth/client/src/main/java/org/wildfly/security/credential/source/OAuth2CredentialSource.java
- auth/jaspi/src/main/java/org/wildfly/security/auth/jaspi/impl/JaspiAuthenticationContext.java
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwkManager.java
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java
- auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/OAuth2IntrospectValidator.java
- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
- http/base/src/main/java/org/wildfly/security/http/HttpAuthenticator.java
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- x500/cert/acme/src/main/java/org/wildfly/security/x500/cert/acme/AcmeClientSpi.java
Fixes https://issues.redhat.com/browse/ELY-2197
> [ELY-2197] Close resource - potential resource leak

- docs.adoc
https://issues.redhat.com/browse/ELY-2151
> [ELY-2151] fix typos in website

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/KeyStoreBackedSecurityRealm.java
- tests/base/src/test/java/org/wildfly/security/sasl/entity/EntityTest.java
Issue: https://issues.redhat.com/browse/ELY-2155
> [ELY-2155] Add parameter validation for KeyStoreBackedSecurityRealm

- pom.xml
Issue: https://issues.redhat.com/browse/ELY-2216
> [ELY-2216] Upgrade FasterXML/jackson to 2.11.4

- auth/realm/jdbc/src/main/java/org/wildfly/security/auth/realm/jdbc/QueryBuilder.java
https://issues.redhat.com/browse/ELY-2176
> [ELY-2176] Add parameter validation in QueryBuilder

- auth/realm/base/src/main/java/org/wildfly/security/auth/realm/DistributedSecurityRealm.java
[ELY-2158] Added parameter validation for DistributedSecurityRealm
Link to the Jira issue: https://issues.redhat.com/browse/ELY-2158
> [ELY-2158] Added parameter validation for DistributedSecurityRealm

- util/src/main/java/org/wildfly/security/util/StringEnumeration.java
[ELY-2150] Added parameter validation for DistributedSecurityRealm
Link to the Jira issue: https://issues.redhat.com/browse/ELY-2150
> [ELY-2150] Added parameter validation in StringEnumeration class

- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/main/java/org/wildfly/security/tool/VaultCommand.java
Issue: https://issues.redhat.com/browse/ELY-2183
> [ELY-2183] The vault command prompts for the password twice

- pom.xml
https://issues.redhat.com/browse/ELY-2218
> [ELY-2218] Upgrade Microprofile JWT API to 1.2.2

- tool/README.md
https://issues.redhat.com/browse/ELY-2219?filter=12364234
> [ELY-2219] Update wildfly-elytron/tool README to not include info about github issues for tool

- .github/workflows/pr-ci.yaml
- pom.xml
https://issues.redhat.com/browse/ELY-2223
https://issues.redhat.com/browse/ELY-2225
> [ELY-2223] Update the Ubuntu version that gets used by GitHub Actions

- keystore/pom.xml
- keystore/src/main/java/org/wildfly/security/keystore/KeyStoreUtil.java
- keystore/src/test/java/org/wildfly/security/keystore/KeyStoreUtilTest.java
- tests/base/src/test/java/org/wildfly/security/util/PemTest.java
- x500/cert/base/src/main/java/org/wildfly/security/pem/Pem.java
https://issues.redhat.com/browse/ELY-2212
> ELY-2212 Support private RSA keys in PEM parser

- auth/util/src/main/java/org/wildfly/security/auth/util/RegexNameRewriter.java
- auth/util/src/main/java/org/wildfly/security/auth/util/RegexNameValidatingRewriter.java
https://issues.redhat.com/browse/ELY-2160
> [ELY-2160] Add parameter validation in RegexNameRewriter and RegexNameValidatingRewriter

- tests/base/src/test/java/org/wildfly/security/auth/server/CaseNameRewriterTest.java
- tests/base/src/test/java/org/wildfly/security/auth/server/MutableNameRewriterTest.java
- tests/base/src/test/java/org/wildfly/security/auth/server/ServerUtils.java
https://issues.redhat.com/browse/ELY-2169
> [ELY-2169] Add test for MutableNameRewriter

- credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStore.java
- credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStoreSpi.java
- credential/store/src/main/java/org/wildfly/security/credential/store/impl/KeyStoreCredentialStore.java
- tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/test/java/org/wildfly/security/tool/AbstractCommandTest.java
- tool/src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
https://issues.redhat.com/browse/ELY-1850
> [ELY-1850] CredentialStore API missing ability to check alias types

- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfigurationBuilder.java
- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientContext.java
- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcJsonConfiguration.java
- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcSecurityRealm.java
https://issues.redhat.com/browse/ELY-2234
Original PR merged to master, this PR cherry picked commit for merge to 1.x
> [ELY-2234] Allow merge of resource & realm roles on OIDC Client

- tool/pom.xml
https://issues.redhat.com/browse/ELY-2251
> [ELY-2251] Create a separate shaded jar for elytron-tool for testing purposes

- pom.xml
Issue: https://issues.redhat.com/browse/JBEAP-22650
Upstream issue: https://issues.redhat.com/browse/ELY-2200
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1614
> [ELY-2200] Update org.apache.sshd:sshd-common:2.3.0 to 2.7.0

- auth/server/base/src/main/java/org/wildfly/security/auth/server/SecurityDomain.java
https://issues.redhat.com/browse/ELY-2195
> [ELY-2195] Use daemon threads in default ScheduledExecutorService

- .github/workflows/pr-ci.yaml
https://issues.redhat.com/browse/ELY-2270
> [ELY-2270] Update pr-ci.yaml to include the 2.x branch

- .github/workflows/pr-ci.yaml
https://issues.redhat.com/browse/ELY-2278
> [ELY-2278] Add 1.17.x branch to pr-ci.yaml for Github Actions

- _layouts/blog.html
- _layouts/post.html
https://issues.redhat.com/browse/ELY-2262
> [ELY-2262] Added spaces between each tag

- _posts/2021-12-17-client-side-jvm-wide-default-sslcontext.adoc
Preview: https://skyllarr.github.io/wildfly-elytron/blog/client-side-jvm-wide-default-sslcontext/
> Add blog post about upcoming client side default ssl context provider

- _layouts/community.html
- _posts/2021-12-17-client-side-jvm-wide-default-sslcontext.adoc
- _posts/2021-12-17-new-security-features-wildfly.adoc
- _posts/2021-12-17-securing-wildfly-apps-openid-connect.adoc
- docs.adoc
Can be previewed here:
https://fjuma.github.io/wildfly-elytron/blog/securing-wildfly-apps-openid-connect/
http://fjuma.github.io/wildfly-elytron/blog/new-security-features-wildfly/
> Add a blog post on OpenID Connect and a release blog post for WildFly 26

- http/base/src/main/java/org/wildfly/security/http/HttpServerCookie.java
https://issues.redhat.com/browse/ELY-2253
> [ELY-2253] Add a simple implementation of HttpServerCookie

- pom.xml
https://issues.redhat.com/browse/ELY-2281
> [ELY-2281] Upgrade resteasy-client to 4.7.4.Final

- tool/src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- tool/src/main/java/org/wildfly/security/tool/MaskCommand.java
- tool/src/test/java/org/wildfly/security/tool/MaskCommandTest.java
- util/src/main/java/org/wildfly/security/util/PasswordUtil.java
https://issues.redhat.com/browse/ELY-2180
> [ELY-2180] Mask command default iteration count, salt dynamically generated

- http/oidc/src/main/java/org/wildfly/security/http/oidc/ElytronMessages.java
- http/oidc/src/main/java/org/wildfly/security/http/oidc/OidcClientConfiguration.java
https://issues.redhat.com/browse/ELY-2290
> [ELY-2290] Update OidcClientConfiguration#resetUrls to handle the case where the provider-url or auth-server-url isn't valid
